<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">
<link rel="stylesheet" type="text/css" href="css/jsDatePick_ltr.min.css">


<div id="indexpage" class="indexpage">
    <h1>产品评测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");
        
        include 'sidebar_enterprise.phtml'; 
        ?>            
        </div>

        <div id="mid" class="span8 mid">
            <div class="linkbtns">
                <form action="/evaluate/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="产品评测">
                </form>
            </div>
            <div>
                <form action="/evaluate/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要评测">
                </form>
            </div>
            <div id="evaedit">
                <div>
                    <h4>新建订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'evaluate', 
                    array(
                        'action' => 'add',
                    )
                ));
                $arr_products = array( '' => '' );
                foreach ($products as $p)
                {
                    $arr_products[$p->id_product] = $p->name;
                }
                $form->add(array(
                    'name' => 'fk_product',
                    'type'  => 'Zend\Form\Element\Select',
                    'attributes' => array(
                        'id' => 'appproduct',
                        'onchange' => "change_product();",
                        ),
                    'options' => array(
                        'value_options' => $arr_products,
                        ),
                ));                
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_evaluate'));
                ?>
                <tr>
                    <td class="tdlabel">App产品：</td>
                    <td>
                        <?php echo $this->formRow($form->get('fk_product')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">产品卖点</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('highlight')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">评测要求</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('requirement')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">有效时间</td>
                    <td>
                        <?php echo $this->formRow($form->get('due_date')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">建议媒体采用的产品截图：</td>
                    <td>
                        <?php echo $this->formRow($form->get('screen_shot')); ?>
                    </td>
                </tr>
                <!--<tr>
                    <td class="tdlabel">选择评测媒体</td>
                    <td>
                        <?php //echo $this->formRow($form->get('evamedia')); ?>
                    </td>
                </tr>-->
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('web_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>                
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">媒体评测费用</td>
                    <td>评测撰稿及发布，2000元/篇</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
$(document).ready(function(){
    $( "#f_date_ETA" ).datepicker();
    $( "#f_date_ETA" ).datepicker("option","dateFormat","yy-mm-dd");    
});
</script>

<script>
function change_product()
{
    var product = document.getElementById("appproduct").value;
    var product_web = new Array();
    var product_appstore = new Array();
    var product_android = new Array();
    <?php foreach($js_products as $pro): ?>
    product_web[<?php echo $pro->id_product; ?>] = "<?php echo $pro->web_link; ?>";
    product_appstore[<?php echo $pro->id_product; ?>] = "<?php echo $pro->appstore_link; ?>";
    product_android[<?php echo $pro->id_product; ?>] = "<?php echo $pro->androidmkt_link; ?>";
    <?php endforeach; ?>
    document.getElementById("web_link").value = product_web[product];
    document.getElementById("appstore_link").value = product_appstore[product];
    document.getElementById("androidmkt_link").value = product_android[product];
}
</script>

            
            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>

