<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>产品评测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">            
        <?php 
        set_include_path("public/include");    
        if($user_type == 1)
        {    
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>
        </div>

        <div id="mid" class="span8 mid">  
            <div class="linkbtns">
                <form action="/evaluate/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="产品评测">
                </form>
            </div>
            <div>
                <form action="/evaluate/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要评测">
                </form>
            </div>
            <div id="evamgmt">
                <!--<h4>订单号：<?php echo $this->escapeHtml($evaluate->id_evaluate);?></h4>-->
                <table class="pubdetailtable">
                    <?php
                    $arr_id_user = array();
                    foreach($allusers as $u)
                    {
                        $arr_id_user[$u->id] = $u->username;
                    }
                    $arr_evamedia_status = array(
                        1 => '新订单',
                        2 => '媒体拒绝',
                        3 => '媒体接受',
                        4 => '企业拒绝',
                        5 => '企业接受',
                        6 => '订单完成',
                    );
                    ?>
                    <tr>
                        <td class="tdlabel">订单号：</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->order_no); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">App产品：</td>
                        <td>
                            <?php echo $this->escapeHtml($product->name); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品卖点：</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->highlight);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">评测要求：</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->requirement);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">有效时间：</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->due_date);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">订单状态：</td>
                        <td>
                            <?php 
                            $arr_evaluate_status = array(
                                '1' => '草稿',
                                '2' => '订单确认',
                                '3' => '订单工作完成',
                                '4' => '账款结清',
                            );
                            if(array_key_exists($evaluate->fk_evaluate_status, $arr_evaluate_status)){
                                echo $this->escapeHtml($arr_evaluate_status[$evaluate->fk_evaluate_status]); 
                            }else{
                                echo '订单状态错误！';
                            }                            
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">建议媒体采用的产品截图：</td>
                        <td>
                            <?php foreach($screenshots as $ss): ?>
                            <img src="<?php echo substr($ss->path.$ss->filename,6);?>" height="300" width="300">
                            <form action="<?php echo $this->url('evaluate', 
                            array('action' => 'deletescreenshot', 'id' => $ss->id_screenshot)) ;?>">
                                <input type="submit" class="btn btn-danger btn-mini" value="删除图片">
                            </form>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->web_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->appstore_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->androidmkt_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <img src="<?php echo $barcode_path;?>" height="200" width="200">
                            <?php //echo $this->escapeHtml($np->barcode);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">最大邀约数量</td>
                        <td>
                            <div class="linkbtns">
                                <?php echo $this->escapeHtml($evaluate->order_limit);?>
                            </div>
                            <div class="linkbtns" style="display:<?php echo ($evaluate->fk_evaluate_status==2)?"":"none";?>">
                                <!--<form action="<?php //echo $this->url('evaluate', array('action'=>'addonelimit', 'id' => $evaluate->id_evaluate)) ;?>">
                                    <input type="submit" class="btn btn-primary btn-mini" value="邀约+1">
                                </form>-->
                                <a href="javascript:if(confirm('确实要增加最大评测媒体数量吗?'))location='<?php echo $this->url('evaluate',array('action'=>'addonelimit', 'id' => $evaluate->id_evaluate)) ;?>'" class="btn btn-primary btn-mini">
                                    评测+1
                                </a>
                            </div>
                            <!--<div style="display:<?php //echo ($evaluate->fk_evaluate_status==2)?"":"none";?>">
                                <form action="<?php //echo $this->url('evaluate', array('action'=>'minusonelimit', 'id' => $evaluate->id_evaluate)) ;?>">
                                    <input type="submit" class="btn btn-danger btn-mini" value="邀约-1">
                                </form>
                                <a href="javascript:if(confirm('确实要减少最大评测媒体数量吗?'))location='<?php //echo $this->url('evaluate',array('action'=>'minusonelimit', 'id' => $evaluate->id_evaluate)) ;?>'" class="btn btn-danger btn-mini">
                                    评测-1
                                </a>
                            </div>-->
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">媒体评测费用</td>
                        <td>
                            <?php echo '评测撰稿及发布，2000 元/篇 × ',$evaluate->order_limit,' 篇 = ',2000*(int)$evaluate->order_limit,' 元'; ?>                             
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">接受评测的媒体：</td>
                        <td>
                            <div class="widget-box">
                                <div class="widget-content nopadding">
                                    <table class="table table-bordered table-striped">
                                        <tr>
                                            <th>子订单号</th>
                                            <th>媒体名称</th>
                                            <th>订单状态</th>
                                            <th>评测链接</th>
                                            <th>操作</th>
                                        </tr>
                                        <?php foreach ($evamedias as $em): ?>
                                        <tr>
                                            <td><?php echo $em->order_no; ?></td>
                                            <td><?php echo $arr_id_user[$em->fk_media_user]; ?></td>
                                            <td>
                                                <div class="linkbtns">
                                                    <?php echo $arr_evamedia_status[$em->fk_evamedia_status]; ?>
                                                </div>
                                            </td>   
                                            <td>
                                                <?php echo $em->news_link; ?>
                                            </td>     
                                            <td>
                                                <div id="btns" style="display:<?php echo ($em->fk_evamedia_status==3&&$vacant>0)?"inline":"none";?>">
                                                    <div class="linkbtns">
                                                        <form action="<?php echo $this->url('evaluate',
                                                        array('action' => 'entacc', 'id' => $em->id_evamedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="接受">
                                                        </form>
                                                    </div>
                                                    <div>
                                                        <form action="<?php echo $this->url('evaluate',
                                                        array('action' => 'entrej', 'id' => $em->id_evamedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="拒绝">
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>                                    
                                        </tr>
                                        <?php endforeach;?>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">创建日期</td>
                        <td><?php echo $this->escapeHtml($evaluate->created_at);?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">创建人</td>
                        <td><?php echo $this->escapeHtml($evaluate->created_by);?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">修改日期</td>
                        <td><?php echo $this->escapeHtml($evaluate->updated_at);?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">修改人</td>
                        <td><?php echo $this->escapeHtml($evaluate->updated_by);?></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <div class="linkbtns">
                                <form action="<?php echo $this->url('evaluate',
                                array('action' => 'edit', 'id' => $evaluate->id_evaluate)) ;?>">
                                    <input type="submit" class="btn btn-primary" value="修改订单">
                                </form>
                            </div>
                            <div style="display:<?php echo ($evaluate->fk_evaluate_status==1)?"":"none";?>">
                                <!--<form action="<?php //echo $this->url('evaluate', array('action'=>'confirm', 'id' => $evaluate->id_evaluate)) ;?>">
                                    <input type="submit" class="btn btn-primary" value="确认订单">
                                </form>-->
                                <a href="javascript:if(confirm('确实要确认订单吗?\n<?php echo 2000*(int)$evaluate->order_limit;?>元评测费用将被冻结。'))location='<?php echo $this->url('evaluate',array('action'=>'confirm', 'id' => $evaluate->id_evaluate)) ;?>'" class="btn btn-primary">
                                    确认订单
                                </a>
                            </div>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>