<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>产品评测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">            
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">  
            <div class="linkbtns">
                <form action="/evaluate/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="产品评测">
                </form>
            </div>
            <div>
                <form action="/evaluate/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要评测">
                </form>
            </div>
            <div id="evamgmt">
                <!--<h4>订单号：<?php echo $this->escapeHtml($evaluate->id_evaluate);?></h4>-->
                <table class="pubdetailtable">
                    <?php
                    $arr_id_user = array();
                    foreach($allusers as $u)
                    {
                        $arr_id_user[$u->id] = $u->username;
                    }
                    $arr_evaluate_status = array(
                        1 => '新订单',
                        2 => '媒体拒绝',
                        3 => '媒体接受',
                        4 => '企业拒绝',
                        5 => '企业接受',
                    );
                    ?>
                    <tr>
                        <td class="tdlabel">App产品：</td>
                        <td>
                            <?php echo $this->escapeHtml($product->name); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品卖点：</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->highlight);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">评测要求：</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->requirement);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">有效时间：</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->due_date);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">建议媒体采用的产品截图：</td>
                        <td>
                            
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->web_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->appstore_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($evaluate->androidmkt_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <img src="<?php echo $barcode_path;?>" height="200" width="200">
                            <?php //echo $this->escapeHtml($np->barcode);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">媒体评测费用</td>
                        <td>评测撰稿及发布，2000元/篇</td>
                    </tr>
                    <tr>
                        <td class="tdlabel">接受评测的媒体：</td>
                        <td>
                            <div class="widget-box">
                                <div class="widget-content nopadding">
                                    <table class="table table-bordered table-striped">
                                        <tr>
                                            <th>订单号</th>
                                            <th>媒体名称</th>
                                            <th>订单状态</th>
                                            <th>操作</th>
                                            <th>评测链接</th>
                                        </tr>
                                        <?php foreach ($evamedias as $em): ?>
                                        <tr>
                                            <td><?php echo $em->order_no; ?></td>
                                            <td><?php echo $arr_id_user[$em->fk_media_user]; ?></td>
                                            <td>
                                                <div class="linkbtns">
                                                    <?php echo $arr_evaluate_status[$em->fk_evaluate_status]; ?>
                                                </div>
                                            </td>
                                            <td>
                                                <div id="btns" style="display:<?php echo ($em->fk_evaluate_status==3)?"inline":"none";?>">
                                                    <div class="linkbtns">
                                                        <form action="<?php echo $this->url('evaluate',
                                                        array('action' => 'entacc', 'id' => $em->id_evamedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary" value="接受">
                                                        </form>
                                                    </div>
                                                    <div>
                                                        <form action="<?php echo $this->url('evaluate',
                                                        array('action' => 'entrej', 'id' => $em->id_evamedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary" value="拒绝">
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>    
                                            <td>
                                                <?php echo $em->news_link; ?>
                                            </td>                                        
                                        </tr>
                                        <?php endforeach;?>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <form action="<?php echo $this->url('evaluate',
                                array('action' => 'edit', 'id' => $evaluate->id_evaluate)) ;?>">
                                <input type="submit" class="btn btn-primary" value="修改订单">
                            </form>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>