<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>产品评测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">            
        <?php 
        set_include_path("public/include");    
        if($user_type == 1)
        {    
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>
        </div>

        <div id="mid" class="span8 mid">
            <div class="linkbtns">
                <form action="/evaluate/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="产品评测">
                </form>
            </div>
            <div>
                <form action="/evaluate/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要评测">
                </form>
            </div>
            <div id="evaedit">
                <div>
                    <h4>新建订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'evaluate', 
                    array(
                        'action' => 'edit',
                        'id'     => $this->id,
                    )
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_evaluate'));
                echo $this->formHidden($form->get('fk_product'));
                ?>
                <tr>
                    <td class="tdlabel">App产品：</td>
                    <td>
                        <?php echo $product->name; ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">产品卖点</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('highlight')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">评测要求</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('requirement')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">有效时间</td>
                    <td>
                        <?php echo $this->formRow($form->get('due_date')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">最大评测媒体数量</td>
                    <td class="td-order-limit">
                        <?php echo $this->formRow($form->get('order_limit')); ?>
                        <span id="plus_one" class="plus_one" onclick="plus_one();">+1</span>
                        <span id="minus_one" class="minus_one" onclick="minus_one();">-1</span>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">建议媒体采用的产品截图：</td>
                    <td>
                        <?php foreach($screenshots as $ss): ?>
                        <img src="<?php echo substr($ss->path.$ss->filename,6);?>" height="300" width="300">
                        <a href="/evaluate/deletescreenshotfromedit/<?php echo $ss->id_screenshot; ?>" 
                            class="btn btn-danger btn-mini">删除图片</a>
                        <?php endforeach; ?>       
                        <?php echo $this->formRow($form->get('screen_shot')); ?>                 
                        <?php //echo "截图数量：",$count_ss; ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('web_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>                
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <img src="<?php echo $barcode_path;?>" height="200" width="200">
                        </br>
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">媒体评测费用</td>
                    <td>评测撰稿及发布，2000元/篇</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
$(document).ready(function(){
    $( "#f_date_ETA" ).datepicker({
        minDate: 0,
        dateFormat: "yy-mm-dd",
    });
    /*$( "#f_date_ETA" ).val("<?php echo $evaluate->due_date; ?>");*/
});
</script>

<script>
document.getElementById('screen_shot').onchange = function(){
    var count_ss = <?php echo $count_ss; ?>;
    if(this.files.length + count_ss > 5)
    {
        alert('最多上传5个产品截图');
        document.getElementById('screen_shot').value = null;
    }
}
function plus_one()
{
    var order_limit = Number(document.getElementById("order_limit").value);
    document.getElementById("order_limit").value = order_limit + 1;
}
function minus_one()
{
    var order_limit = Number(document.getElementById("order_limit").value);
    if(order_limit>1){
        document.getElementById("order_limit").value = order_limit - 1;
    }
}
</script>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
span.plus_one
{
    background-color: black;
    color: white;
    cursor: pointer;
    padding: 2px;
}
span.minus_one
{
    background-color: grey;
    color: white;
    cursor: pointer;
    padding: 2px;
}
</style>