<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>产品评测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="user" class="user">
                <ul>
                    <li>
                        <span>用户: <?php echo $user;?></span>
                        <a href="/user/logout">退出</a>
                    </li>
                    <li><a href="">企业资料</a></li>
                    <li><a href="">我的账户</a></li>
                    <li><a href="">我的订单</a></li>
                    <li><a href="">APP新闻助手</a></li>
                </ul>
            </div>
            <div id="sidebar">
                <ul>
                    <!--
                    <li>
                        <a href="netmonitor"><span>网络监测</span></a>
                    </li>
                    -->
                    <li class="submenu">
                        <a href="#"><span>新闻发布</span></a>
                        <ul>
                            <li><a href="/newspub/add">我要发布</a></li>
                            <li><a href="/newspub/index">发布管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>产品测评</span></a>
                        <ul>
                            <li><a href="/evaluate/add">我要评测</a></li>
                            <li><a href="/evaluate/index">评测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>新闻撰写</span></a>
                        <ul>
                            <li><a href="/writer/add">我要撰稿</a></li>
                            <li><a href="/writer/index">撰稿管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>媒体选题</span></a>
                        <ul>
                            <li><a href="/topic/current">当期选题</a></li>
                            <li><a href="/topic/mgmt">选题管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="interview">媒体采访</a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="mid" class="span8 mid"> 
            <div class="linkbtns">
                <form action="/evaluate/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="产品评测">
                </form>
            </div>
            <div>
                <form action="/evaluate/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要评测">
                </form>
            </div>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>我的产品评测订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>App产品</th>
                        <th>产品卖点</th>
                        <th>创建日期</th>
                        <th>创建者</th>
                    </tr>
                    <?php foreach($paginator as $np): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($np->fk_product);?></td>
                        <td><a href="<?php echo $this->url('evaluate',array('action'=>'detail','id'=>$np->id_evaluate));?>"><?php echo $this->escapeHtml($np->highlight);?></a></td>
                        <td><?php echo $this->escapeHtml($np->created_at);?></td>
                        <td><?php echo $this->escapeHtml($np->created_by);?></td>
                    </tr>
                    <?php endforeach; ?>

                </table>

<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination/search.phtml');
?>
                </div>
            </div>
            

        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
