<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>产品评测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");
        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid"> 
            <div class="linkbtns">
                <form action="">
                    <input type="submit" class="btn btn-primary linkbtn" value="产品评测">
                </form>
            </div>
            <div>
                <form action="">
                    <input type="submit" class="btn btn-primary linkbtn" value="评测管理">
                </form>
            </div>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>我的产品评测订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <?php
                    $arr_products = array();
                    foreach ($products as $p)
                    {
                        $arr_products[$p->id_product] = $p->name;
                    }
                    ?>
                    <tr>
                        <th>订单号</th>
                        <th>App产品</th>
                        <th>创建日期</th>
                        <!--<th>产品卖点</th>-->
                        <th>订单状态</th>
                        <th>发布状态</th>
                        <th>查看详情</th>
                        <!--<th>创建者</th>-->
                    </tr>
                    <?php foreach($paginator as $np): ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('evaluate',array('action'=>'detail','id'=>$np->id_evaluate));?>">
                                <?php echo $this->escapeHtml($np->order_no); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($arr_products[$np->fk_product]);?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($np->created_at);?>
                        </td>
                        <!--<td>
                            <?php //echo $this->escapeHtml($np->highlight);?>
                        </td>-->
                        <td>
                            <?php 
                            $arr_evaluate_status = array(
                                '1' => '草稿',
                                '2' => '订单确认',
                                '3' => '订单完成',
                                '4' => '账款结清'
                            );
                            $arr_pub_status = array(
                                '1' => '',
                                '2' => '进行中',
                                '3' => '订单完成',
                                '4' => '订单完成',
                            );
                            if(array_key_exists($np->fk_evaluate_status, $arr_evaluate_status)){
                                echo $this->escapeHtml($arr_evaluate_status[$np->fk_evaluate_status]); 
                            }else{
                                echo '订单状态错误！';
                            }                            
                            ?>
                        </td>
                        <td>
                            <?php 
                            if(array_key_exists($np->fk_evaluate_status, $arr_pub_status)){
                                echo $this->escapeHtml($arr_pub_status[$np->fk_evaluate_status]); 
                            }else{
                                echo '订单状态错误！';
                            }  
                            ?>
                        </td>
                        <td>
                            <form action="<?php echo $this->url('evaluate', 
                            array('action' => 'detail', 'id' => $np->id_evaluate)) ;?>">
                                <input type="submit" class="btn btn-primary btn-mini" value="查看详情">
                            </form>
                        </td>
                        <!--<td><?php echo $this->escapeHtml($np->created_by);?></td>-->
                    </tr>
                    <?php endforeach; ?>

                </table>

<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination/search.phtml');
?>
                </div>
            </div>
            

        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
