<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>产品评测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="user" class="user">
                <ul>
                    <li>
                        <span>用户: <?php echo $user;?></span>
                        <a href="/user/logout">退出</a>
                    </li>
                    <li><a href="">企业资料</a></li>
                    <li><a href="">我的账户</a></li>
                    <li><a href="">我的订单</a></li>
                    <li><a href="">APP新闻助手</a></li>
                </ul>
            </div>
            <div id="sidebar">
                <ul>
                    <!--
                    <li>
                        <a href="netmonitor"><span>网络监测</span></a>
                    </li>
                    -->
                    <li class="submenu">
                        <a href="#"><span>新闻发布</span></a>
                        <ul>
                            <li><a href="/newspub/add">我要发布</a></li>
                            <li><a href="/newspub/index">发布管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>产品测评</span></a>
                        <ul>
                            <li><a href="/evaluate/add">我要评测</a></li>
                            <li><a href="/evaluate/index">评测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>新闻撰写</span></a>
                        <ul>
                            <li><a href="/writer/add">我要撰稿</a></li>
                            <li><a href="/writer/index">撰稿管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>媒体选题</span></a>
                        <ul>
                            <li><a href="/topic/current">当期选题</a></li>
                            <li><a href="/topic/mgmt">选题管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="interview">媒体采访</a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="mid" class="span8 mid">
            <div class="linkbtns">
                <form action="/evaluate/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="产品评测">
                </form>
            </div>
            <div>
                <form action="/evaluate/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要评测">
                </form>
            </div>
            <div id="evaedit">
                <div>
                    <h4>新建订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'evaluate', 
                    array(
                        'action' => 'neworder',
                    )
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_evaluate'));
                echo $this->formHidden($form->get('fk_product'));
                ?>
                <tr>
                    <td class="tdlabel">App产品：</td>
                    <td>
                        <?php echo $product->name; ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">产品卖点</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('highlight')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">建议媒体采用的产品截图：</td>
                    <td>
                        
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">选择评测媒体</td>
                    <td>
                        <?php echo $this->formRow($form->get('evamedia')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('web_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>                
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">媒体评测费用</td>
                    <td>评测撰稿及发布，2000元/篇</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
