<h1>Newspub Admin Page</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <div id="allproducts" class="widget-box">
                <div class="widget-title">
                    <h4>所有产品</h4>
                </div>                
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>id</th>
                            <th>产品名称</th>
                            <th>产品类型</th>
                            <th>创建人</th>
                        </tr>
                        <?php foreach($products as $product): ?>
                        <tr>
                            <td>
                                <?php 
                                    echo $this->escapeHtml($product->id_product);
                                ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('product',array('action'=>'detail','id'=>$product->id_product));?>">
                                    <?php echo $this->escapeHtml($product->name);?>
                                </a>
                            </td>
                            <td><?php echo $this->escapeHtml($product->type);?></td>
                            <td><?php echo $this->escapeHtml($product->created_by);?></td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div#userinfo
{
    border: 1px solid black;
}
</style>