<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="allproducts" class="widget-box">
                <div class="widget-title">
                    <h4>所有产品</h4>
                </div>                
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>id</th>
                            <th>产品名称</th>
                            <th>产品类型</th>
                            <th>创建人</th>
                        </tr>
                        <?php foreach($products as $product): ?>
                        <tr>
                            <td>
                                <?php 
                                    echo $this->escapeHtml($product->id_product);
                                ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('product',array('action'=>'detail','id'=>$product->id_product));?>">
                                    <?php echo $this->escapeHtml($product->name);?>
                                </a>
                            </td>
                            <td><?php echo $this->escapeHtml($product->type);?></td>
                            <td><?php echo $this->escapeHtml($product->created_by);?></td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>