<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");     
        if($user_type == 1)
        {   
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="productdetail">
                <h4>我的产品<?php //echo $this->escapeHtml($product->id_product);?></h4>
                <table class="pubdetailtable">
                    <tr>
                        <td>名称</td>
                        <td>
                            <?php echo $this->escapeHtml($product->name);?>
                        </td>
                    </tr>
                    <tr>
                        <td>描述</td>
                        <td>
                            <?php echo $this->escapeHtml($product->description);?>
                        </td>
                    </tr>
                    <tr>
                        <td>类型</td>
                        <td>
                            <?php echo $this->escapeHtml($product->type);?>
                        </td>
                    </tr>
                    <tr>
                        <td>Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($product->appstore_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td>安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($product->androidmkt_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td>web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($product->web_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <img src="<?php echo $barcode_path;?>" height="200" width="200">
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品图标</td>
                        <td>
                            <img src="<?php echo $appicon_path;?>" height="200" width="200">
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <form action="<?php echo $this->url('product',
                                array('action' => 'edit', 'id' => $product->id_product)) ;?>">
                                <input type="submit" class="btn btn-primary" value="修改产品信息">
                            </form>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>
    </div>
    </div>
</div>