
            <div class="linkbtns">
                <form action="/evaluate/mgmt">
                    <input type="submit" class="btn btn-primary linkbtn" value="评测管理">
                </form>
            </div>
            <div>
                <form action="/evaluate/invitation">
                    <input type="submit" class="btn btn-primary linkbtn" value="评测邀约">
                </form>
            </div>