<div id="user" class="user">
    <h4>用户：<?php echo $user;?></h4>
</div>
<div id="sidebar">
    <ul>
        <li>
            <a href='#'><span>用户管理</span></a>
            <ul>
                <li><a href="/user/admin">所有用户</a></li>
                <li><a href="/user/add">创建用户</a></li>
            </ul>
        </li>
        <li>
            <a href='#'><span>产品管理</span></a>
            <ul>
                <li><a href="/product/admin">所有产品</a></li>
                <li><a href="#">创建产品</a></li>
            </ul>
        </li>
        <li>
            <a href='#'><span>订单管理</span></a>
            <ul>
                <li><a href="/monitor/admin">网络监测</a></li>
                <li><a href="/newspub/admin">新闻发布</a></li>
                <li><a href="/evaluate/admin">产品评测</a></li>
                <li><a href="/writer/admin">撰稿外包</a></li>
                <li><a href="/topic/admin">媒体选题</a></li>
                <li><a href="/interview/admin">媒体采访</a></li>
            </ul>
        </li>
    </ul>
</div>