            <div id="user" class="user">
                <ul>
                    <li>
                        <span>用户: <?php echo $user;?></span>
                        <a href="/user/logout">退出</a>
                    </li>
                    <li><a href="/">企业资料</a></li>
                    <li><a href="/enterprise/myaccount">我的账户</a></li>
                    <li><a href="">我的订单</a></li>
                    <li><a href="">APP新闻助手</a></li>
                </ul>
            </div>
            <div id="sidebar">
                <ul>
                    <li class="submenu">
                        <a href="#"><span>网络监测</span></a>
                        <ul>
                            <li><a href="/monitor/configure">监测订制</a></li>
                            <li><a href="/monitor/data">监测数据</a></li>
                            <li><a href="/monitor/mgmt">监测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>新闻发布</span></a>
                        <ul>
                            <li><a href="/newspub/add">我要发布</a></li>
                            <li><a href="/newspub/index">发布管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>产品测评</span></a>
                        <ul>
                            <li><a href="/evaluate/add">我要评测</a></li>
                            <li><a href="/evaluate/index">评测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>新闻撰写</span></a>
                        <ul>
                            <li><a href="/writer/add">我要撰稿</a></li>
                            <li><a href="/writer/index">撰稿管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>媒体选题</span></a>
                        <ul>
                            <li><a href="/topic/current">当期选题</a></li>
                            <li><a href="/topic/mgmt">选题管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>媒体采访</span></a>
                        <ul>
                            <li><a href="/interview/entcurrent">当前邀约</a></li>
                            <li><a href="/interview/entpast">过往邀约</a></li>
                        </ul>
                    </li>
                </ul>
            </div>