            <div id="user" class="user">
                <ul>
                    <li>
                        <span>用户: <?php echo $user;?></span>
                        <a href="/user/logout">退出</a>
                    </li>
                    <li><a href="/">媒体资料</a></li>
                    <li><a href="/media/myaccount">我的账户</a></li>
                    <li><a href="/media/myorder">我的订单</a></li>
                    <li><a href="">APP新闻助手</a></li>
            </div>
            <div id="sidebar">
                <ul>
                    <li class="submenu">
                        <a href="#"><span>发布选题</span></a>
                        <ul>
                            <li><a href="/topic/add">我要发布</a></li>
                            <li><a href="/topic/index">选题管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>产品评测</span></a>
                        <ul>
                            <li><a href="/evaluate/invitation">评测邀约</a></li>
                            <li><a href="/evaluate/mgmt">评测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>采访APP</span></a>
                        <ul>
                            <li><a href="/interview/add">采访邀约</a></li>
                            <li><a href="/interview/index">采访管理</a></li>
                        </ul>
                    </li>
                    <div style="display:<?php echo ($is_writer)?'':'none' ;?>;">
                    <li class="submenu">
                        <a href="#"><span>自由撰稿人</span></a>
                        <ul>
                            <li><a href="/writer/reqlist">最新订单</a></li>
                            <li><a href="/writer/mgmt">撰稿管理</a></li>
                        </ul>
                    </li>
                    </div>
                </ul>
            </div>   
 