<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>企业用户首页</h1>  
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="user" class="user">
                用户: <?php echo $user;?>
                <a href="/user/logout">退出</a>
            </br>
                <a href="">企业资料</a>
            </br>
                <a href="">我的账户</a>
            </br>
                <a href="">我的订单</a>
            </br>
                <a href="">APP新闻助手</a>           
            </div>
            <div id="netmonitor" class="netmonitor">
                <a href="netmonitor">网络监测</a>
            </div>
            <div id="newspublish" class="newspublish">
                <a href="/newspub/index">新闻发布</a>
            </div>
            <div id="appevaluating" class="appevaluating">
                <a href="appevaluating">产品评测</a>
            </div>
            <div id="newsedit" class="newsedit">
                <a href="newsedit">新闻撰写</a>
            </div>
            <div id="topic" class="topic">
                <a href="topic">媒体选题</a>
            </div>
            <div id="interview" class="interview">
                <a href="interview">媒体采访</a>
            </div>
        </div>
        <div id="mid" class="span8 mid">
            <div>
                <div class="linkbtns">
                    <form action="/enterprise/enterpriseinfo">
                        <input type="submit" class="btn btn-primary linkbtn" value="企业资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/enterprise/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>
                <div>
                    <form action="/enterprise/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="userinfo">
                        <table id="tbuserinfo">
                            <tr>
                                <td>
                                    用户信息——
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    用户名：
                                    <?php echo $user;?>&nbsp;&nbsp;<a href="">修改密码</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    电子邮箱：
                                </td>
                                <td>
                                    <?php echo $email;?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                    <div id="addenterpriseinfo" style="display:<?php echo $addenterpriseinfo;?>;">
                        请在下表中编辑企业信息：
                        <table>
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action',$this->url(
                            'enterprise',
                            array(
                                'action' => 'index',
                            )
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('id_enterprise'));
                        ?>
                            <tr>
                                <td class="tdlabel">公司名称：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">所在地：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('location')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">办公地址：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('address')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">发票信息：</td>
                                <td class="tdlabel">发票抬头：</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('invoice_title')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">发票类型：</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('invoice_type')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">联系人：</td>
                                <td class="tdlabel">姓名</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">职位</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_post')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">电话</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_phone')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">邮箱</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_email')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td colspan=2>
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                    <?php echo $this->form()->closeTag(); ?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                    <div id="appinfo">
                        <table id="tbappinfo">
                            <tr>
                                <td>
                                    产品信息——
                                </td>
                                <td colspan=2></td>
                            </tr>
                            <tr>
                                <td>
                                    名称：
                                </td>
                                <td colspan=2></td>
                            </tr>
                            <tr>
                                <td>
                                    类型：
                                </td>
                                <td colspan=2></td>
                            </tr>
                            <tr>
                                <td>
                                    下载链接：
                                </td>
                                <td colspan=2></td>
                            </tr>


                        </table>
                    </div>
                    <div>

                    </div>
                </div>
            </div>
        </div>
        <div id="right" class="span4 right">
            SPAN4 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>