<div id="indexpage" class="indexpage">

    <div id="header" class="container">
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        <div id="mid" class="span9 mid">
            <!--
            <ul class="nav nav-pills" style="margin-top:20px;">
                <li class="active">
                <a href="#">我的APPBUZ</a>
                </li>
                <li><a href="#">APP新闻首页</a></li>
            </ul>

            <dl class="dashboard">
                <dt>网络监测</dt>
                <dd>
                    <ul class="clearfix">
                        <li><a style="padding-left:0;" href="#">监测项订制</a>|</li>
                        <li><a href="#">新闻收件箱<span class="num">new</span></a>|</li>
                        <li><a href="#">分析报表</a>|</li>
                        <li><a href="#">监测管理</a></li>
                    </ul>
                </dd>

                <dt>新闻发布</dt>
                <dd>
                    <ul class="clearfix">
                        <li><a style="padding-left:0;" href="#">我要发布</a>|</li>
                        <li><a href="#">发布管理</a>|</li>
                        <li><a href="#">新发布稿件<span class="num">5</span>篇</a>&nbsp;&nbsp;<a href="#">查看详情</a></li>
                    </ul>
                </dd>

                <dt>产品评测</dt>
                <dd>
                    <ul class="clearfix">
                        <li><a style="padding-left:0;" href="#">我要评测</a>|</li>
                        <li><a href="#">评测管理</a>|</li>
                        <li><a href="#">评测媒体反馈<span class="num">5</span>家</a>&nbsp;&nbsp;<a href="#">查看详情</a></li>
                    </ul>
                </dd>

                <dt>新闻撰写</dt>
                <dd>
                    <ul class="clearfix">
                        <li><a style="padding-left:0;" href="#">我要撰稿</a>|</li>
                        <li><a href="#">撰稿管理</a>|</li>
                        <li><a href="#">自由撰稿人反馈<span class="num">5</span>人</a>&nbsp;&nbsp;<a href="#">查看详情</a></li>
                    </ul>
                </dd>

                <dt>媒体选题</dt>
                <dd>
                    <ul class="clearfix">
                        <li><a style="padding-left:0;" href="#">当期选题</a>|</li>
                        <li><a href="#">媒体新发布选题<span class="num">5</span>篇</a>&nbsp;&nbsp;<a href="#">查看详情</a></li>
                    </ul>

                    <ul class="clearfix">
                        <li><a style="padding-left:0;" href="#">选题管理</a>|</li>
                        <li><a href="#">自由撰稿人反馈<span class="num">5</span>人</a>&nbsp;&nbsp;<a href="#">查看详情</a></li>
                    </ul>
                </dd>
            </dl>-->

            <div style="padding-top:20px;">
                <div class="linkbtns">
                    <form action="/">
                        <input type="submit" class="btn btn-primary linkbtn" value="企业资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/enterprise/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>
                <div>
                    <form action="/enterprise/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="userinfo">
                        <table id="tbuserinfo">
                            <tr>
                                <td>
                                    用户信息——
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    用户名：
                                    <?php echo $user;?>&nbsp;&nbsp;<a href="<?php echo $this->url('user',
                                        array('action' => 'changepassword', 'id' => $id_user)) ;?>">修改密码</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    电子邮箱：
                                    <?php echo $email;?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                    <?php 
                    //show the enterprise information if exist.
                    //if not, render the form to create it for the user.
                    $enterpriseinfo = 'none';
                    $addenterpriseinfo = '';
                    if($fk_enterprise)
                    {
                        $enterpriseinfo = '';
                        $addenterpriseinfo = 'none';
                    }
                    ?>
                    <div id="enterpriseinfo" style="display:<?php echo $enterpriseinfo;?>;">
                        <table id="tbenterpriseinfo">
                            <tr>
                                <td>公司信息——</td>
                                <td colspan=2>
                                    &nbsp;&nbsp;<a href="<?php echo $this->url('enterprise',
                                array('action' => 'edit', 'id' => $enterprise->id_enterprise)) ;?>">编辑</a>
                                </td>
                            </tr>
                            <tr>
                                <td>公司名称：</td>
                                <td colspan=2>
                                    <?php echo $enterprise->name;?>
                                </td>
                            </tr>
                            <tr>
                                <td>所在地：</td>
                                <td colspan=2>
                                    <?php echo $enterprise->location;?>
                                </td>
                            </tr>
                            <tr>
                                <td>发票信息：</td>
                                <td>发票抬头：</td>
                                <td>
                                    <?php echo $enterprise->invoice_title;?>
                                </td>
                            </tr>
                            <tr>
                                <?php $arr_invoice_type = array('1' => '普通发票', '2' => '增值税发票'); ?>
                                <td></td>
                                <td>发票类型：</td>
                                <td>
                                    <?php
                                    if(array_key_exists($enterprise->invoice_type, $arr_invoice_type)){
                                        echo $arr_invoice_type[$enterprise->invoice_type];
                                    }else{
                                        echo $enterprise->invoice_type;
                                    }
                                    ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>公司全称：</td>
                                <td>
                                    <?php echo $enterprise->ent_full_name; ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>通信地址：</td>
                                <td>
                                    <?php echo $enterprise->ent_address; ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>公司电话：</td>
                                <td>
                                    <?php echo $enterprise->ent_phone_number; ?>
                                </td>
                            </tr>
                            <tr>
                                <td>个人信息：</td>
                                <td>姓名：</td>
                                <td>
                                    <?php echo $enterprise->contacter_name;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>职位：</td>
                                <td>
                                    <?php echo $enterprise->contacter_post;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>电话：</td>
                                <td>
                                    <?php echo $enterprise->contacter_phone;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>手机：</td>
                                <td>
                                    <?php echo $enterprise->contacter_mobile;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>邮箱：</td>
                                <td>
                                    <?php echo $enterprise->contacter_email;?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                    <div id="addenterpriseinfo" style="display:<?php echo $addenterpriseinfo;?>;">
                        未创建企业信息，请在下表中填写：
                        <table>
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action',$this->url(
                            'enterprise',
                            array(
                                'action' => 'index',
                            )
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('id_enterprise'));
                        ?>
                            <tr>
                                <td class="tdlabel">公司名称：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">所在地：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('location')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">发票信息：</td>
                                <td class="tdlabel">发票抬头：</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('invoice_title')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">发票类型：</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('invoice_type')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">公司全称：</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('ent_full_name')); ?>
                                </td>
                            </tr>
                            
                            <tr>
                                <td></td>
                                <td class="tdlabel">通信地址：</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('ent_address')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">公司电话：</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('ent_phone_number')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">联系人：</td>
                                <td class="tdlabel">姓名</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">职位</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_post')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">电话</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_phone')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">手机</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_mobile')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">邮箱</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_email')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td colspan=2>
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                    <?php echo $this->form()->closeTag(); ?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>