<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>企业用户首页</h1>  
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <div>
                <div class="linkbtns">
                    <form action="/">
                        <input type="submit" class="btn btn-primary linkbtn" value="企业资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/enterprise/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>
                <div>
                    <form action="/enterprise/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="userinfo">
                        <h4>我的账户：</h4>
                        <table id="tbuserinfo">
                            <tr>
                                <td>用户名：</td>
                                <td><?php echo $user; ?></td>
                                <td>账户总金额：</td>
                                <td><?php echo '人民币 ',$credit->amount,' 元'; ?></td>
                                <td>账户可用金额：</td>
                                <td><?php echo '人民币 ',$credit->amount-$credit->deposit,' 元'; ?></td>
                                <td>订单锁定金额：</td>
                                <td><?php echo '人民币 ',$credit->deposit,' 元'; ?></td>
                            </tr>                            
                        </table>
                    </div>
                </div>
                <div id="creditlog" style="display:<?php echo ($creditlog)?'':'none';?>;" class="widget-box">
                <div class="widget-title">
                    <h4>最近交易记录：</h4>
                </div>
                <div class="widget-content nopadding">
                    <?php 
                    $arr_service_type = array(
                        '1' => '充值成功',
                        '2' => '已下单',//单篇发布
                        '3' => '已下单',//打包发布
                        '4' => '已结束',//单篇发布->将取消的订单的锁定资金退回
                        '5' => '已完成',//打包发布结账
                        '6' => '已完成',//单篇发布结账
                        '7' => '已下单',//评测
                        '8' => '增加数量',//评测
                        '9' => '减少数量',//评测
                        '10' => '订单结束',
                        '11' => '订单结束',
                    );
                    ?>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>订单号</th>
                            <th>订单类型</th>
                            <th>状态</th>
                            <th>锁定金额</th>
                            <th>交易金额</th>
                            <th>账户可用金额</th>
                            <!--<th>全部锁定金额</th>-->
                            <th>交易日期</th>
                            <th>经办人</th>
                        </tr>
                        <?php foreach($creditlog as $log): ?>
                        <tr>
                            <td><?php echo $log->order_no; ?></td>
                            <td>
                                <?php 
                                $type_code = substr($log->order_no, 0, 1);
                                switch($type_code)
                                {
                                    case 9:
                                        echo "充值";
                                        break;
                                    case 1:
                                        echo "新闻发布";
                                        break;
                                    case 2:
                                        echo "产品评测";
                                        break;
                                    case 3:
                                        echo "撰稿外包";
                                        break;
                                    case 4:
                                        echo "媒体选题";
                                        break;
                                    case 5:
                                        echo "网络监测";
                                        break;
                                }
                                ?>
                            </td>
                            <td><?php echo $arr_service_type[$log->fk_service_type]; ?></td>
                            <td>
                                <?php 
                                $sign_deposit = '';
                                if($log->is_pay_deposit==1){
                                    $sign_deposit = '-';
                                }
                                /*if($log->is_charge_deposit==1){
                                    echo $log->deposit;
                                }*/
                                echo $sign_deposit.$log->deposit; 
                                ?>
                            </td>
                            <td>
                                <?php 
                                $sign = '';
                                if($log->is_charge==1){
                                    $sign = '+';
                                }
                                if($log->amount != 0){
                                    echo $sign.$log->amount; 
                                }                                
                                ?>
                            </td>
                            <td>
                                <?php echo $log->remaining_balance - $log->remaining_deposit; ?>
                            </td>
                            <!--<td>
                                <?php //echo $log->remaining_deposit.'元'; ?>
                            </td>-->
                            <td><?php echo $log->date_time; ?></td>
                            <td><?php echo $log->created_by; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </table>                    
                </div>
                <div class="linkbtns">
                    <form action="/credit/exportlog/<?php echo $credit->id_credit ;?>">
                        <input type="submit" class="btn btn-primary" value="导出全部交易记录">
                    </form>
                </div>
                <div>
                    <form action="/credit/notify">
                        <input type="submit" class="btn btn-primary" value="充值">
                    </form>
                </div>
                </div>
            </div>
        </div>
        <div id="right" class="span4 right">
            SPAN4 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>