<div id="indexpage" class="indexpage">

    <div id="main" class="container"> 
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        <div id="mid" class="span9">
            <div style="padding-top:20px;">
                <div class="linkbtns">
                    <form action="/enterprise">
                        <input type="submit" class="btn btn-primary linkbtn" value="企业资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/enterprise/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>
                <div>
                    <form action="/enterprise/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="monitororder" class="widget-box">
                        <div class="widget-title">
                            <h4>最新订单——</h4>
                        </div>
                        <div class="widget-content nopadding">
                            <table id="monitortable" class="table table-bordered table-striped">
                                <tr>
                                    <th>订单号</th>
                                    <th>订单类型</th>
                                    <!--<th>服务周期</th>
                                    <th>开始日期</th>
                                    <th>结束日期</th>-->
                                    <th>订单状态</th>
                                    <th>创建日期</th>
                                    <th>操作</th>
                                </tr>
                                <?php foreach($monitor5 as $mnt): ?>
                                <tr>
                                    <td><?php echo $mnt->order_no; ?></td>
                                    <td>网络监测</td>
                                    <!--<td><?php echo $mnt->duration.'个月'; ?></td>
                                    <td><?php echo $mnt->start_date; ?></td>
                                    <td><?php echo $mnt->end_date; ?></td>-->
                                    <td>
                                        <?php 
                                        if($now > $mnt->end_date){
                                            echo "订单过期";
                                        }else{
                                            echo "生效中";
                                        }
                                        ?>
                                    </td>
                                    <td><?php echo $mnt->created_at;?></td>
                                    <td>
                                        <a href="/monitor/mgmt" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                        <?php
                        $arr_product_name = array();
                        $arr_product_description = array();
                        foreach ($products as $p)
                        {
                            $arr_product_name[$p->id_product] = $p->name;
                            $arr_product_description[$p->id_product] = $p->description;
                        }
                        ?>
                                <?php foreach($newspub5 as $np) :  ;?>
                                <tr>
                                    <td>
                                        <a href="/newspub/detail/<?php echo $np->id_newspub ;?>">
                                            <?php echo $np->order_no; ?>
                                        </a>
                                    </td>
                                    <td>新闻发布</td>
                                    <td>
                                        <?php 
                                        $arr_newspub_status = array(
                                            '1' => '草稿',
                                            '2' => '订单确认',
                                            '3' => '订单工作完成',
                                            '4' => '账款结清',
                                        );
                                        if(array_key_exists($np->fk_newspub_status, $arr_newspub_status)){
                                            echo $arr_newspub_status[$np->fk_newspub_status];
                                        }else{
                                            echo '订单状态错误！';
                                        }
                                        ?>
                                    </td>
                                    <td>
                                        <?php echo $np->created_at;?>
                                    </td>
                                    <td>
                                        <a href="/newspub/detail/<?php echo $np->id_newspub ;?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                    <!--<td>
                                        <?php 
                                        if(array_key_exists($np->fk_product, $arr_product_name))
                                        {
                                            echo $arr_product_name[$np->fk_product];
                                        }
                                        else
                                        {
                                            echo "未关联产品";
                                        }
                                        ?>
                                    </td>
                                    <td>
                                        <?php echo $np->title; ?>
                                    </td>-->
                                </tr>
                                <?php endforeach; ?>
                            <?php foreach($evaluate5 as $eva) :  ;?>
                            <tr>
                                <td>
                                    <a href="/evaluate/detail/<?php echo $eva->id_evaluate ;?>">
                                        <?php echo $eva->order_no; ?>
                                    </a>
                                </td>
                                <td>产品评测</td>
                                <!--<td>
                                    <?php //echo $arr_product_name[$eva->fk_product]; ?>
                                </td>
                                <td>
                                    <?php //echo $eva->highlight; ?>
                                </td>
                                <td>
                                    <?php //echo $eva->due_date; ?>
                                </td>-->
                                <td>
                                    <?php
                                    $arr_evaluate_status = array(
                                        '1' => '草稿',
                                        '2' => '订单确认',
                                        '3' => '订单工作完成',
                                        '4' => '账款结清',
                                    );
                                    if(array_key_exists($eva->fk_evaluate_status, $arr_evaluate_status)){
                                        echo $this->escapeHtml($arr_evaluate_status[$eva->fk_evaluate_status]); 
                                    }else{
                                        echo '订单状态错误！';
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?php echo $eva->created_at;?>
                                </td>
                                <td>
                                    <a href="/evaluate/detail/<?php echo $eva->id_evaluate ;?>" class="btn btn-primary btn-mini">
                                        查看详情
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                                <?php foreach($writer5 as $wrt): ?>
                                <tr>
                                    <td>
                                        <a href="/writer/detail/<?php echo $wrt->id_writer ;?>">
                                            <?php echo $wrt->order_no; ?>
                                        </a>
                                    </td>
                                    <td>撰稿外包</td>
                                    <!--<td><?php //echo $arr_product_name[$wrt->fk_product]; ?></td>
                                    <td><?php //echo $wrt->requirement; ?></td>-->
                                    <td>
                                        <?php
                                        $arr_writer_status = array(
                                            '1' => '草稿',
                                            '2' => '订单确认',
                                            '3' => '订单工作完成',
                                            '4' => '账款结清',
                                        );
                                        if(array_key_exists($wrt->fk_writer_status, $arr_writer_status)){
                                            echo $this->escapeHtml($arr_writer_status[$wrt->fk_writer_status]); 
                                        }else{
                                            echo '订单状态错误！';
                                        }
                                        ?>
                                    </td>
                                    <td><?php echo $wrt->created_at; ?></td>
                                    <td>
                                        <a href="/writer/detail/<?php echo $wrt->id_writer ;?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            <?php
                            $arr_id_user = array();
                            foreach($all_users as $au)
                            {
                                $arr_id_user[$au->id] = $au->username;
                            }
                            ?>
                                <?php foreach($tpcontact5 as $tpc): ?>
                                <tr>
                                    <td>
                                        <a href="/topic/viewcontact/<?php echo $tpc->fk_topic ;?>">
                                            <?php echo $tpc->order_no; ?>
                                        </a>
                                    </td>
                                    <td>
                                        媒体选题
                                    </td>
                                    <td>
                                        <?php
                                        $arr_tpcontact_status = array(
                                            '1' => '联系中',
                                            '2' => '已结束',
                                            '3' => '企业忽略',
                                        );
                                        if(array_key_exists($tpc->fk_tpcontact_status, $arr_tpcontact_status)){
                                            echo $arr_tpcontact_status[$tpc->fk_tpcontact_status];
                                        }
                                        ?>
                                    </td>
                                    <!--<td><?php echo $arr_id_user[$tpc->fk_media_user]; ?></td>
                                    <td><?php echo $arr_product_name[$tpc->fk_product]; ?></td>-->
                                    <td><?php echo $tpc->created_at; ?></td>
                                    <td>
                                        <a href="/topic/viewcontact/<?php echo $tpc->fk_topic ;?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                <?php foreach($interview5 as $itv): ?>
                                <tr>
                                    <td>
                                        <a href="/interview/entdetail/<?php echo $itv->id_interview ;?>">
                                            <?php echo $itv->order_no; ?>
                                        </a>
                                    </td>
                                    <td>媒体采访</td>
                                    <!--<td><?php echo $arr_id_user[$itv->fk_media_user]; ?></td>
                                    <td><?php echo $arr_product_name[$itv->fk_product]; ?></td>
                                    <td><?php echo $itv->date_time; ?></td>-->
                                    <td><?php echo $itv->fk_interview_status; ?></td>
                                    <td><?php echo $itv->created_at; ?></td>
                                    <td>
                                        <a href="/interview/entdetail/<?php echo $itv->id_interview ;?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}*/
</style>