<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>我的订单</h1>  
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <!--
        <div id="left" class="span2 left">
            <div id="user" class="user">
                用户: <?php echo $user;?>
                <a href="/user/logout">退出</a>
            </br>
                <a href="">企业资料</a>
            </br>
                <a href="">我的账户</a>
            </br>
                <a href="">我的订单</a>
            </br>
                <a href="">APP新闻助手</a>           
            </div>
            <div id="netmonitor" class="netmonitor">
                <a href="netmonitor">网络监测</a>
            </div>
            <div id="newspublish" class="newspublish">
                <a href="/newspub/index">新闻发布</a>
            </div>
            <div id="appevaluating" class="appevaluating">
                <a href="appevaluating">产品评测</a>
            </div>
            <div id="newsedit" class="newsedit">
                <a href="newsedit">新闻撰写</a>
            </div>
            <div id="topic" class="topic">
                <a href="topic">媒体选题</a>
            </div>
            <div id="interview" class="interview">
                <a href="interview">媒体采访</a>
            </div>
        </div>
        -->
        <div id="mid" class="span12">
            <div>
                <div class="linkbtns">
                    <form action="/enterprise/enterpriseinfo">
                        <input type="submit" class="btn btn-primary linkbtn" value="企业资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/enterprise/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>
                <div>
                    <form action="/enterprise/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="appinfo" class="widget-box">
                        <div class="widget-title">
                            <h4>新闻发布订单——</h4>
                        </div>
                        <div class="widget-content nopadding">
                        <?php
                        $arr_product_name = array();
                        $arr_product_description = array();
                        foreach ($products as $p)
                        {
                            $arr_product_name[$p->id_product] = $p->name;
                            $arr_product_description[$p->id_product] = $p->description;
                        }
                        ?>
                        <table id="tbappinfo" class="table table-bordered table-striped">
                            <th>
                                <td>产品</td>
                                <td>标题</td>
                                <td>正文</td>
                                <td>产品描述</td>
                                <td>web下载链接</td>
                            <!--<td>Appstore下载链接</td>
                                <td>安卓市场下载链接</td>-->
                                <td>发布方式及费用</td>
                            </th>
                            <?php foreach($newspub as $eva) :  ;?>
                            <tr>
                                <td></td>
                                <td>
                                    <?php 
                                    if(array_key_exists($eva->fk_product, $arr_product_name))
                                    {
                                        echo $arr_product_name[$eva->fk_product];
                                    }
                                    else
                                    {
                                        echo "未关联产品";
                                    }
                                    ?>
                                </td>
                                <td>
                                    <a href="/newspub/detail/<?php echo $eva->id_newspub ;?>"><?php echo $eva->title; ?></a>
                                </td>
                                <td>
                                    <?php echo $eva->body; ?>
                                </td>
                                <td>
                                    <?php 
                                    if(array_key_exists($eva->fk_product, $arr_product_description))
                                    {
                                        echo $arr_product_description[$eva->fk_product];
                                    }
                                    else
                                    {
                                        echo "未关联产品";
                                    }
                                    ?>

                                </td>
                                <td>
                                    <?php echo $eva->download_link; ?>
                                </td>
                            <!--<td>
                                    <?php echo $eva->appstore_links; ?>
                                </td>
                                <td>
                                    <?php echo $eva->androidmkt_link; ?>
                                </td>-->
                                <td>
                                    <?php echo $eva->fk_pub_mode; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        </div>
                    </div>
                    <div id="appinfo" class="widget-box">
                        <div class="widget-title">
                            <h4>产品评测订单——</h4>
                        </div>
                        <div class="widget-content nopadding">
                        <table id="tbappinfo" class="table table-bordered table-striped">
                            <th>
                                <td>App产品</td>
                                <td>产品卖点</td>
                                <td>web下载链接</td>
                            </th>
                            <?php foreach($evaluate as $eva) :  ;?>
                            <tr>
                                <td></td>
                                <td>
                                    
                                </td>
                                <td>
                                    <a href="/evaluate/detail/<?php echo $eva->id_evaluate ;?>"><?php echo $eva->highlight; ?></a>
                                </td>
                                <td>
                                    <?php echo $eva->web_link; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!--
        <div id="right" class="span4 right">
            SPAN4 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
        -->
    </div>
    </div>
</div>

<style>
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
</style>