<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="charge">
                <table>
                    <?php 
                    $form = $this->form;
                    $form->setAttribute('action', $this->url(
                        'credit',
                        array(
                            'action' => 'charge',
                            'id'     => $credit->id_credit,
                        )
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_credit'));
                    echo $this->formHidden($form->get('fk_user'));
                    echo $this->formHidden($form->get('fk_user_type'));
                    echo $this->formHidden($form->get('created_at'));
                    echo $this->formHidden($form->get('created_by'));
                    ?>
                    <tr>
                        <td class="tdlabel">充值账户：</td>
                        <td><?php echo $target_user->username; ?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">账户余额：</td>
                        <td class="tdinput">
                            <?php echo $credit->amount; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">锁定金额：</td>
                        <td class="tdinput">
                            <?php echo $credit->deposit; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">可用余额：</td>
                        <td class="tdinput">
                            <?php echo $credit->amount - $credit->deposit;?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">充值金额：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('chargeamount')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>