<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?>

        <div id="mid" class="span9 mid"  style="padding-top:20px">   
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要采访">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="采访邀约">
                </form>
            </div>
            <div id="wrtmgmt">
                <table>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url(
                        'interview',
                        array(
                            'action' => 'add',
                        )
                    ));
                    $arr_products = array();
                    foreach($all_products as $product)
                    {
                        $arr_products[$product->id_product] = $product->name;
                    }
                    $form->add(array(
                        'name' => 'fk_product',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            'id' => 'appproduct',
                        ),
                        'options' => array(
                            'value_options' => $arr_products,
                        ),
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_interview'));
                    ?>
                    <tr>
                        <td class="tdlabel">采访目标APP：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('fk_product')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访目的：</td>
                        <td class="tdtextarea">
                            <?php echo $this->formRow($form->get('purpose')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访纲要：</td>
                        <td class="tdtextarea">
                            <?php echo $this->formRow($form->get('outline')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访日期：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('date_time')); ?>
                        </td>
                    </tr>
                    <?php for($i=1;$i<11;$i++): ?>
                    <tr id="<?php echo 'q'.$i;?>">
                        <td class="tdlabel">问题<?php echo $i; ?>：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('q'.$i)); ?>
                        </td>
                    </td>
                    <?php endfor; ?>
                    <tr>
                        <td>
                            <a id="add_a_question" class="btn btn-primary btn-mini">增加一个问题</a>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
$(function() {
    $( "#f_date_ETA" ).datepicker({minDate:0});
    $( "#f_date_ETA" ).datepicker("option","dateFormat","yy-mm-dd");
});
</script>

<script>
var q_index = 2;
$(document).ready(function(){
    for(var i=2; i<11; i++){
        $("#q"+i).css("display", "none");   
    }    
    $("#add_a_question").click(function(){
        $("#q"+q_index).css("display", "");
        q_index++;
    });
});

</script>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>
