<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <?php

            ?>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>媒体采访订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <?php
                    $arr_id_user = array();
                    foreach($all_users as $au)
                    {
                        $arr_id_user[$au->id] = $au;
                    }
                    $arr_id_product = array();
                    foreach ($products as $pd) 
                    {
                        $arr_id_product[$pd->id_product] = $pd;
                    }
                    $arr_fk_interview_status = array(
                        '1' => '发出邀请',
                        '2' => '企业接受邀请',
                        '3' => '企业拒绝邀请',
                        '4' => '媒体取消采访邀约',
                    );
                    ?>
                    <tr>
                        <th>订单号</th>
                        <th>发布媒体</th>
                        <th>产品名称</th>
                        <th>受邀企业</th>
                        <th>订单状态</th>
                        <th>创建日期</th>
                        <!--<th>操作</th>-->
                    </tr>
                    <?php foreach($interview as $iv): ?>
                    <tr>
                        <td>                       
                            <a href="/interview/detail/<?php echo $iv->id_interview; ?>">
                                <?php echo $iv->order_no; ?>
                            </a>
                        </td>
                        <td><?php echo $iv->created_by; ?></td>
                        <td>
                            <?php
                            if(array_key_exists($iv->fk_product, $arr_id_product))
                            {
                                echo $arr_id_product[$iv->fk_product]->name; 
                            }
                            ?>
                        </td>
                        <td>
                            <?php                             
                            if(array_key_exists($iv->fk_enterprise_user, $arr_id_user))
                            {
                                echo $arr_id_user[$iv->fk_enterprise_user]->username; 
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if(array_key_exists($iv->fk_interview_status, $arr_fk_interview_status))
                            {
                                echo $arr_fk_interview_status[$iv->fk_interview_status];
                            }
                            ?>
                        </td>
                        <td><?php echo $iv->created_at; ?></td>
                        <!--<td></td>-->
                    </tr>
                    <?php endforeach; ?>
                </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div#userinfo
{
    border: 1px solid black;
}*/
</style>