
<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;"> 
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="媒体采访">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="邀约详情">
                </form>
            </div>
            <div id="wrtmgmt">
                <table>
                    <tr>
                        <td class="tdlabel">订单号：</td>
                        <td class="tdinput">
                            <?php echo $interview->order_no; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访目标APP：</td>
                        <td class="tdinput">
                            <?php echo $product->name; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访目的：</td>
                        <td class="tdtextarea">
                            <?php echo $interview->purpose; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访纲要：</td>
                        <td class="tdtextarea">
                            <?php echo $interview->outline; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访日期：</td>
                        <td class="tdinput">
                            <?php echo substr($interview->date_time,0,10); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">订单状态：</td>
                        <td>
                            <?php
                            $arr_interview_status = array(
                                '1' => '已发邀请',
                                '2' => '企业接受邀请',
                                '3' => '企业拒绝邀请',
                                '4' => '媒体取消',
                            );
                             echo $arr_interview_status[$interview->fk_interview_status]; ?>
                        </td>
                    </tr>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url(
                        'interview',
                        array(
                            'action' => 'answer',
                            'id'     => $interview->id_interview,
                        )
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_interview'));

                    $end_of_question = 0;             
                    for($i=10;$i>0;$i--){
                        $qname = 'q'.$i;
                        if($interview->$qname){
                            $end_of_question = $i;
                            break;
                        }else{
                            continue;
                        }
                    }                   
                    ?>
                    <?php if($end_of_question > 0): ?>
                        <?php for($j=1;$j<$end_of_question+1;$j++): ?>
                        <tr>
                            <td class="tdlabel">问题<?php echo $j; ?>：</td>
                            <td>
                                <?php 
                                $qname = 'q'.$j;
                                echo $interview->$qname; 
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">回答<?php echo $j; ?>：</td>
                            <td>
                                <?php echo $this->formRow($form->get('a'.$j)); ?>
                            </td>
                        </tr>
                        <?php endfor; ?>
                    <?php endif; ?>
                    <?php 
                    for($k=1;$k<11;$k++)
                    {
                        echo $this->formHidden($form->get('q'.$k));
                    }
                    echo $this->formHidden($form->get('date_time'));
                    ?>
                    <tr>
                        <td class="tdlabel">回答配图：</td>
                        <td>
                            <?php foreach($screenshots as $ss): ?>
                            <img src="<?php echo substr($ss->path.$ss->filename, 6);?>" height="300" width="300"> 
                            <?php endforeach; ?>
                            <?php echo $this->formRow($form->get('screen_shot')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>
