<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>我要采访</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");    
        if($user_type == 2)
        {    
            include 'sidebar_media.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>
        </div>

        <div id="mid" class="span8 mid">  
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要采访">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="修改邀约">
                </form>
            </div>
            <div id="wrtmgmt">
                <table>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url(
                        'interview',
                        array(
                            'action' => 'edit',
                            'id'     => $interview->id_interview,
                        )
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_interview'));
                    ?>
                    <tr>
                        <td class="tdlabel">采访目标APP：</td>
                        <td class="tdinput">
                            <?php echo $product->name; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访目的：</td>
                        <td class="tdtextarea">
                            <?php echo $this->formRow($form->get('purpose')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访纲要：</td>
                        <td class="tdtextarea">
                            <?php echo $this->formRow($form->get('outline')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">采访日期：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('date_time')); ?>
                        </td>
                    </tr>
                    <?php        
                    $end_of_question = 0;             
                    for($i=10;$i>0;$i--){
                        $qname = 'q'.$i;
                        if($interview->$qname){
                            $end_of_question = $i;
                            break;
                        }else{
                            continue;
                        }
                    }                   
                    ?>
                    <?php if($end_of_question>0): ?>
                        <?php for($i=1;$i<11;$i++): ?>
                        <tr id="<?php echo 'q'.$i;?>">
                            <td class="tdlabel">问题<?php echo $i; ?>：</td>
                            <td class="tdinput">
                                <?php echo $this->formRow($form->get('q'.$i)); ?>
                            </td>
                        </tr>
                        <tr id="<?php echo 'a'.$i;?>">
                            <td class="tdlabel">回答<?php echo $i; ?>：</td>
                            <td>
                                <?php 
                                $aname = 'a'.$i;
                                echo $interview->$aname;
                                ?>
                            </td>
                        </tr>
                        <?php endfor; ?>
                    <?php endif; ?>
                    <tr>
                        <td>
                            <a id="add_a_question" class="btn btn-primary btn-mini">增加一个问题</a>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<script>
var q_index = <?php echo $end_of_question; ?>;
$(document).ready(function(){
    for(var i=q_index+1; i<11; i++){
        $("#q"+i).css("display", "none");   
        $("#a"+i).css("display", "none");
    } 
    $("#add_a_question").click(function(){
        $("#q"+q_index).css("display", "");
        //$("#a"+q_index).css("display", "");
        q_index++;
    });
});

</script>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
$(document).ready(function(){
    $( "#f_date_ETA" ).datepicker({minDate:0});
    $( "#f_date_ETA" ).datepicker("option","dateFormat","yy-mm-dd"); 
    $( "#f_date_ETA" ).val("<?php echo $interview->date_time; ?>");
});
</script>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>
