<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;"> 
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="媒体采访">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="过往邀约">
                </form>
            </div>
                    <?php
                    $arr_products = array();
                    foreach($products as $p)
                    {
                        $arr_products[$p->id_product] = $p->name;
                    }
                    $arr_interview_status = array(
                        '1' => '已发邀请',
                        '2' => '企业接受邀请',
                        '3' => '企业拒绝邀请',
                        '4' => '媒体取消',
                        '5' => '采访结束',
                    );
                    ?>
            <div id="past_interview" class="widget-box">
                <div class="widget-title">
                    <h4>已结束的采访</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>订单号</th>
                            <th>APP</th>
                            <th>采访时间</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                        <?php foreach($past_interview as $p_i): ?>
                        <tr>
                            <td>
                                <?php echo $p_i->order_no; ?>
                            </td>
                            <td>
                                <?php echo $arr_products[$p_i->fk_product]; ?>
                            </td>
                            <td>
                                <?php echo substr($p_i->date_time,0,10); ?>
                            </td>
                            <td>
                                <?php echo $arr_interview_status[$p_i->fk_interview_status]; ?>
                            </td>
                            <td>
                                <div class="linkbtns">
                                    <form action="<?php echo $this->url('interview', 
                                        array('action' => 'entdetail', 'id' => $p_i->id_interview)); ?>">
                                        <input type="submit" class="btn btn-primary btn-mini" value="查看">
                                    </form>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>
