<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>我要采访</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">  
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要采访">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="采访管理">
                </form>
            </div>
            <div id="current_interview" class="widget-box">
                <div class="widget-title">
                    <h4>当前采访邀约</h4>
                </div>
                <div class="widget-content nopadding">
                    <?php
                    $arr_products = array();
                    foreach($products as $p)
                    {
                        $arr_products[$p->id_product] = $p->name;
                    }
                    $arr_interview_status = array(
                        '1' => '已发邀请',
                        '2' => '企业接受邀请',
                        '3' => '企业拒绝邀请',
                        '4' => '媒体取消',
                        '5' => '采访结束',
                    );
                    ?>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>订单号</th>
                            <th>APP</th>
                            <th>采访日期</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                        <?php foreach($current_interview as $c_i): ?>
                        <tr>
                            <td>
                                <?php echo $c_i->order_no; ?>
                            </td>
                            <td>
                                <?php echo $arr_products[$c_i->fk_product]; ?>
                            </td>
                            <td>
                                <?php echo substr($c_i->date_time,0,10); ?>
                            </td>
                            <td>
                                <?php echo $arr_interview_status[$c_i->fk_interview_status]; ?>
                            </td>
                            <td>
                                <div class="linkbtns">
                                    <form action="<?php echo $this->url('interview', 
                                        array('action' => 'detail', 'id' => $c_i->id_interview)); ?>">
                                        <input type="submit" class="btn btn-primary btn-mini" value="查看">
                                    </form>
                                </div>
                                <div style="display:<?php echo ($c_i->fk_interview_status==4)?'none':'';?>">
                                    <form action="<?php echo $this->url('interview',
                                        array('action' => 'cancel', 'id' => $c_i->id_interview)); ?>">
                                        <input type="submit" class="btn btn-danger btn-mini" value="撤销">
                                    </form>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
            <div id="past_interview" class="widget-box">
                <div class="widget-title">
                    <h4>已结束的采访</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>订单号</th>
                            <th>APP</th>
                            <th>采访时间</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                        <?php foreach($past_interview as $p_i): ?>
                        <tr>
                            <td>
                                <?php echo $p_i->order_no; ?>
                            </td>
                            <td>
                                <?php echo $arr_products[$p_i->fk_product]; ?>
                            </td>
                            <td>
                                <?php echo substr($p_i->date_time,0,10); ?>
                            </td>
                            <td>
                                <?php echo $arr_interview_status[$p_i->fk_interview_status]; ?>
                            </td>
                            <td>
                                <div class="linkbtns">
                                    <form action="<?php echo $this->url('interview', 
                                        array('action' => 'detail', 'id' => $p_i->id_interview)); ?>">
                                        <input type="submit" class="btn btn-primary btn-mini" value="查看">
                                    </form>
                                </div>
                                <div style="display:<?php echo ($p_i->fk_interview_status==4)?'none':'';?>">
                                    <form action="<?php echo $this->url('interview',
                                        array('action' => 'cancel', 'id' => $p_i->id_interview)); ?>">
                                        <input type="submit" class="btn btn-danger btn-mini" value="撤销">
                                    </form>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>
