<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻发布</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="user" class="user">
                用户: <?php echo $user;?>
                <a href="/user/logout">退出</a>
            </br>
                <a href="">企业资料</a>
            </br>
                <a href="">我的账户</a>
            </br>
                <a href="">我的订单</a>
            </br>
                <a href="">APP新闻助手</a>           
            </div>
            <div id="netmonitor" class="netmonitor">
                <a href="netmonitor">网络监测</a>
            </div>
            <div id="newspublish" class="newspublish">
                <a href="/newspub">新闻发布</a>
            </div>
            <div id="appevaluating" class="appevaluating">
                <a href="appevaluating">产品评测</a>
            </div>
            <div id="newsedit" class="newsedit">
                <a href="newsedit">新闻撰写</a>
            </div>
            <div id="topic" class="topic">
                <a href="topic">媒体选题</a>
            </div>
            <div id="interview" class="interview">
                <a href="interview">媒体采访</a>
            </div>
        </div>

        <div id="mid" class="span6 mid">            
            <div>
                <form action="/newspub/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="订单管理">
                </form>
            </div>
            <div id="pubedit">
                <div>
                    <h4>新建订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'newspub', 
                    array(
                        'action' => 'add',
                    )
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_newspub'));
                ?>
                <tr>
                    <td class="tdlabel">标题</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('title')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">正文</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('body')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('download_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">软件市场链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_links')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">发布方式及费用</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('fk_pub_mode')); ?>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>
