<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻发布</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">            
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="新闻发布">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="新建订单">
                </form>
            </div>
            <div id="pubedit">
                <div>
                    <h4>新建订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'newspub', 
                    array(
                        'action' => 'add',
                    )
                ));
                $arr_products = array( '' => '');
                foreach ($products as $p)
                {
                    $arr_products[$p->id_product] = $p->name;
                    /*$arr_product_appstorelink[$p->id_product] = $p->appstore_link;
                    $arr_product_androidmktlink[$p->id_product] = $p->androidmkt_link;
                    $arr_product_weblink[$p->id_product] = $p->web_link;*/
                }
                $form->add(array(
                    'name' => 'fk_product',
                    'type'  => 'Zend\Form\Element\Select',
                    'attributes' => array(
                        'id' => 'appproduct',
                        'onchange' => "change_product();",
                        ),
                    'options' => array(
                        'value_options' => $arr_products,
                        ),
                    ));
              /*$form->add(array(
                    'name' => 'fk_pub_mode',
                    'type'  => 'Zend\Form\Element\Radio',
                    'options' => array(
                        'value_options' => array(
                            '1' => '按媒体单篇发布，350元/篇：点击选择媒体 发布__篇，共__元',
                            '2' => '打包发布，实发篇数不少于6篇，1500元/发布包',
                            ),
                        ),
                    ));*/
                $arr_id_media = array();
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_newspub'));
                ?>
                <tr>
                    <td class="tdlabel">标题</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('title')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">正文</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('body')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">App产品</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('fk_product')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('download_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_links')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>          
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">发布方式</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('fk_pub_mode')); ?>
                    </td>
                </tr>
                <tr id="tr_pick_media">
                    <td class="tdlabel">选择媒体</td>
                    <td>
                        <?php 

                        ?>
                        <table>
                            <tr>
                                <td class="tdlabel">
                                    <h5>候选媒体</h5>
                                    <select multiple class="sel" id="sel_left">
                                        <?php foreach($medias as $media): ?>
                                        <option value="<?php echo $media->id;?>">
                                            <?php 
                                                echo $media->username;
                                                $arr_id_media[$media->id] = $media->username;
                                            ?>
                                        </option>
                                        <?php endforeach; ?>
                                    </select>
                                </td>
                                <td>    
                                    <p><a class="btn btn-primary btn-mini" id="btn_1">&gt;&gt; </a></p>
                                    <p><a class="btn btn-primary btn-mini" id="btn_2">&gt;</a></p>
                                    <p><a class="btn btn-primary btn-mini" id="btn_3">&lt;</a></p>
                                    <p><a class="btn btn-primary btn-mini" id="btn_4">&lt;&lt;</a></p>
                                    
                                </td>
                                <td class="tdlabel">
                                    <h5>已选媒体</h5>
                                    <?php                                    
                                        $form->add(array(
                                            'name' => 'sel_right',
                                            'type' => 'Zend\Form\Element\Select',
                                            'attributes' => array(
                                                'id' => 'sel_right',
                                                'class' => 'sel',
                                                'multiple' => 'multiple',
                                                'inarrayvalidator' => false,
                                                ),
                                            ));
                                        echo $this->formRow($form->get('sel_right')); 
                                    ?>
                                    <!--<select multiple class="sel" id="sel_right">
                                    <option value="f">fffffffffff</option>
                                    </select>-->
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr id="charge_method_single">
                    <td class="tdlabel">费用</td>
                    <td>
                        按媒体单篇发布，350 元/篇：  <!--<a id="pick_media">点击选择媒体</a>-->  发布&nbsp;<span id="total_selected">0</span>&nbsp;篇，共&nbsp;<span id="total_amount">0</span>&nbsp;元。
                    </td>
                </tr>
                <tr id="charge_method_multiple" style="display:none;">
                    <td class="tdlabel">费用：</td>
                    <td>
                        打包发布，实发篇数不少于 6 篇，1500 元/发布包
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<script>
function change_product()
{
    var product = document.getElementById("appproduct").value;
    var product_web = new Array();
    var product_appstore = new Array();
    var product_android = new Array();
    <?php foreach($js_products as $pro): ?>
    product_web[<?php echo $pro->id_product; ?>] = "<?php echo $pro->web_link; ?>";
    product_appstore[<?php echo $pro->id_product; ?>] = "<?php echo $pro->appstore_link; ?>";
    product_android[<?php echo $pro->id_product; ?>] = "<?php echo $pro->androidmkt_link; ?>";
    <?php endforeach; ?>
    document.getElementById("download_link").value = product_web[product];
    document.getElementById("appstore_links").value = product_appstore[product];
    document.getElementById("androidmkt_link").value = product_android[product];
}


//show and hide the charge method according to the value of the publish mode
var media = document.getElementById("tr_pick_media");
var single = document.getElementById("charge_method_single");
var multiple = document.getElementById("charge_method_multiple");
document.getElementById("select_pub_mode").onchange = function(){
  single.style.display = (this.selectedIndex == 1) ? "none" : "";
  media.style.display = (this.selectedIndex == 1) ? "none" : "";
  multiple.style.display = (this.selectedIndex == 1) ? "" : "none";
}
/*
//pick up the medias:
document.getElementById("pick_media").onclick = function(){
    //alert("aaaaaa");
    window.open('/newspub/index','newwindow','width=200,height=200')
}*/
//media picker
$(function(){
    $("#sel_left,#sel_right").bind("change",checkBtn);
    $("#btn_1,#btn_2,#btn_3,#btn_4").bind("click",clickBtn);
    checkBtn();
    });
    
    function checkBtn(){
        jQuery("#sel_left>option").length > 0 ? jQuery("#btn_1").removeAttr("disabled") : jQuery("#btn_1").attr("disabled","disabled");
        jQuery("#sel_left option:selected").length > 0 ? jQuery("#btn_2").removeAttr("disabled") : jQuery("#btn_2").attr("disabled","disabled");
        jQuery("#sel_right option:selected").length > 0 ? jQuery("#btn_3").removeAttr("disabled") : jQuery("#btn_3").attr("disabled","disabled");
        jQuery("#sel_right>option").length > 0 ? jQuery("#btn_4").removeAttr("disabled") : jQuery("#btn_4").attr("disabled","disabled");
    }
    
    function clickBtn(e){
        if("btn_1" == e.target.id){
            jQuery("#sel_left>option").appendTo("#sel_right");
        }else if("btn_2" == e.target.id){
            jQuery("#sel_left option:selected").appendTo("#sel_right");
        }else if("btn_3" == e.target.id){
            jQuery("#sel_right option:selected").appendTo("#sel_left");
        }else if("btn_4" == e.target.id){
            jQuery("#sel_right>option").appendTo("#sel_left");
        }
        var var_total_selected = document.getElementById("sel_right").options.length;
        total_selected.innerHTML = var_total_selected;
        total_amount.innerHTML = var_total_selected * 350;
        checkBtn();
    }
</script>

<style>
.sel
{
    width:150px;height:200px;
}
#pick_media:hover
{
    text-decoration: underline;
}
select, #appproduct
{
    width: 100%;
}
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 75%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>


