<h1>订单管理</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <?php
                $arr_pub_mode = array(
                    '1' => '单篇发布',
                    '2' => '打包发布',
                );
                $arr_newspub_status = array(                    
                    '1' => '草稿',
                    '2' => '订单确认',
                    '3' => '订单完成',
                    '4' => '账款结清'
                );
                $arr_pub_status = array(
                    '1' => '',
                    '2' => '进行中',
                    '3' => '订单完成',
                    '4' => '订单完成',
                );
            ?>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>企业新闻发布订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>订单号</th>
                        <th>发布方式</th>
                        <th>创建日期</th>
                        <!--<th>业务内容</th>-->
                        <th>订单状态</th>
                        <th>发布状态</th>
                        <!--<th>创建人</th>-->
                        <th>操作</th>
                    </tr>
                    <?php foreach($newspubs as $np): ?>
                    <tr>
                        <td><a href="<?php echo $this->url('newspub',array('action'=>'detail','id'=>$np->id_newspub));?>"><?php echo $this->escapeHtml($np->order_no);?></a></td>
                        <td>
                            <?php 
                            if(array_key_exists($np->fk_pub_mode, $arr_pub_mode))
                            {
                                echo $this->escapeHtml($arr_pub_mode[$np->fk_pub_mode]);
                            }                            
                            ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($np->created_at); ?>
                        </td>
                        <!--<td>
                            <?php echo $this->escapeHtml($np->title);?>
                        </td>-->
                        <td>
                            <?php 
                            if(array_key_exists($np->fk_newspub_status, $arr_newspub_status))
                            {
                                echo $this->escapeHtml($arr_newspub_status[$np->fk_newspub_status]);
                            }                            
                            ?>  
                        </td>
                        <td>
                            <?php 
                            if(array_key_exists($np->fk_newspub_status, $arr_pub_status))
                            {
                                echo $this->escapeHtml($arr_pub_status[$np->fk_newspub_status]);
                            }                            
                            ?>
                        </td>
                        <!--<td>
                            <?php echo $this->escapeHtml($np->created_by);?>
                        </td>-->
                        <td>
                            <!--<div id="btns" style="display:<?php echo ($np->fk_newspub_status==2)?"inline":"none";?>">
                                <form action="<?php echo $this->url('newspub', 
                                array('action' => 'done', 'id' => $np->id_newspub)) ;?>">
                                    <input type="submit" class="btn btn-primary btn-mini" value="订单完成">
                                </form>
                            </div>
                            <div id="btns" style="display:<?php echo ($np->fk_newspub_status==3)?"inline":"none";?>">
                                <form action="<?php echo $this->url('newspub', 
                                array('action' => 'remittance', 'id' => $np->id_newspub)) ;?>">
                                    <input type="submit" class="btn btn-primary btn-mini" value="确认付款">
                                </form>                                   
                            </div>-->
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div#userinfo
{
    border: 1px solid black;
}
</style>