<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻发布</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">            
            <div>
                <div class="linkbtns">
                    <form action="/newspub/add">
                        <input type="submit" class="btn btn-primary linkbtn" value="我要发布">
                    </form>
                </div>
                <div>
                    <form action="/newspub/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="订单管理">
                    </form>
                </div>
                <!--<button id="pubedit" class="btn btn-primary">我要发布</button>  
                <button id="pubmgmt" class="btn btn-primary">订单管理</button>-->
            </div>
            <div id="pubmgmt">
                <h4>订单号：<?php echo $this->escapeHtml($np->id_newspub);?></h4>
                <table class="pubdetailtable">
                    <tr>
                        <td class="tdlabel">标题</td>
                        <td>
                            <?php echo $this->escapeHtml($np->title);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">正文</td>
                        <td>
                            <?php echo $this->escapeHtml($np->body);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品名称：</td>
                        <td>
                            <?php echo $product->name; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品描述：</td>
                        <td>
                            <?php echo $product->description; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($np->download_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($np->appstore_links);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($np->androidmkt_link);?>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <img src="<?php echo $barcode_path;?>" height="200" width="200">
                            <?php //echo $this->escapeHtml($np->barcode);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">发布方式及费用</td>
                        <td>
                            <?php echo $this->escapeHtml($np->fk_pub_mode);?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <form action="<?php echo $this->url('newspub',
                                array('action' => 'edit', 'id' => $np->id_newspub)) ;?>">
                                <input type="submit" class="btn btn-primary" value="修改订单">
                            </form>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>