<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻发布</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");    
        if($user_type == 1)
        {    
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>
        </div>

        <div id="mid" class="span8 mid">            
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="新闻发布">
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="订单信息">
                    </form>
                </div>
                <!--<button id="pubedit" class="btn btn-primary">我要发布</button>  
                <button id="pubmgmt" class="btn btn-primary">订单管理</button>-->
            </div>
            <div id="pubmgmt">
                <h4>订单号：<?php echo $this->escapeHtml($np->order_no);?></h4>
                <table class="pubdetailtable">
                    <tr>
                        <td class="tdlabel">标题</td>
                        <td>
                            <?php echo $this->escapeHtml($np->title);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">正文</td>
                        <td>
                            <?php echo $this->escapeHtml($np->body);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">订单状态</td>
                        <td>
                            <?php
                            $arr_newspub_status = array(
                                '1' => '草稿',
                                '2' => '订单确认',
                                '3' => '账款结清',
                            );
                            if(array_key_exists($np->fk_newspub_status, $arr_newspub_status)){
                                echo $arr_newspub_status[$np->fk_newspub_status];
                            }else{
                                echo '订单状态错误！';
                            }
                            ?>
                        </td>   
                    </tr>
                    <tr>
                        <td class="tdlabel">产品名称：</td>
                        <td>
                            <?php echo $product->name; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品描述：</td>
                        <td>
                            <?php echo $product->description; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($np->download_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($np->appstore_links);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($np->androidmkt_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <img src="<?php echo $barcode_path;?>" height="200" width="200">
                            <?php //echo $this->escapeHtml($np->barcode);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">发布方式</td>
                        <td>
                            <?php
                                $arr_pub_mode = array(
                                    '1' => '单篇发布',
                                    '2' => '打包发布',
                                    );
                                echo $this->escapeHtml($arr_pub_mode[$np->fk_pub_mode]);
                            ?>
                        </td>
                    </tr>
                    <tr style="display:<?php echo ($np->fk_pub_mode==1)?'':'none';?>;">
                        <td class="tdlabel">已选媒体</td>
                        <td>
                            <?php
                                $arr_id_user = array();
                                foreach ($all_users as $au)
                                {
                                    $arr_id_user[$au->id] = $au->username;
                                }
                                $arr_npmedia_status = array(
                                    '1' => '新订单',
                                    '2' => '媒体接受',
                                    '3' => '媒体拒绝',
                                    '4' => '已发布',
                                    '5' => '已取消',
                                    );                            
                            ?>
                            <div class="widget-box">
                                <div class="widget-content nopadding">
                                    <table class="table table-bordered table-striped">
                                        <tr>
                                            <th>媒体</th>
                                            <th>状态</th>
                                            <th>新闻链接</th>
                                            <th>操作</th>
                                        </tr>
                                        <?php foreach($npmedia as $nm): ?>
                                        <tr>
                                            <td>
                                                <?php echo $arr_id_user[$nm->fk_media_user];?>
                                            </td>
                                            <td>
                                                <?php echo $arr_npmedia_status[$nm->fk_npmedia_status] ;?>
                                            </td>
                                            <td>
                                                <?php echo $nm->news_link ;?>
                                            </td>
                                            <td style="display:<?php echo ($user_type==1)?'':'none';?>">
                                                <div style="display:<?php echo ($nm->fk_npmedia_status==4)?'':'none';?>">
                                                    <div class="linkbtns">
                                                        <form action="<?php echo $this->url('newspub',
                                                        array('action' => 'score', 'id' => $nm->id_npmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="评分">
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                            <td style="display:<?php echo ($user_type==3)?'':'none';?>">
                                                <div style="display:<?php echo ($nm->fk_npmedia_status==1)?'':'none';?>">
                                                    <div class="linkbtns">
                                                        <form action="<?php echo $this->url('newspub',
                                                        array('action' => 'mediaacc', 'id' => $nm->id_npmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="媒体接受">
                                                        </form>
                                                    </div>
                                                    <div class="linkbtns">
                                                        <form action="<?php echo $this->url('newspub',
                                                        array('action' => 'mediarej', 'id' => $nm->id_npmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="媒体拒绝">
                                                        </form>
                                                    </div>
                                                    <div>
                                                        <form action="<?php echo $this->url('newspub',
                                                        array('action' => 'cancel', 'id' => $nm->id_npmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="企业取消">
                                                        </form>
                                                    </div>
                                                </div>
                                                <div style="display:<?php echo ($nm->fk_npmedia_status==2)?'':'none';?>">
                                                    <div class="linkbtns">
                                                        <form action="<?php echo $this->url('newspub',
                                                        array('action' => 'publish', 'id' => $nm->id_npmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="发布">
                                                        </form>
                                                    </div>
                                                    <div>
                                                        <form action="<?php echo $this->url('newspub',
                                                        array('action' => 'nmcancel', 'id' => $nm->id_npmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="企业取消">
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <?php endforeach;?>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">创建日期</td>
                        <td><?php echo $this->escapeHtml($np->created_at);?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">创建人</td>
                        <td><?php echo $this->escapeHtml($np->created_by);?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">修改日期</td>
                        <td><?php echo $this->escapeHtml($np->updated_at);?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">修改人</td>
                        <td><?php echo $this->escapeHtml($np->updated_by);?></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <div class="linkbtns">
                                <form action="<?php echo $this->url('newspub',
                                array('action' => 'edit', 'id' => $np->id_newspub)) ;?>">
                                    <input type="submit" class="btn btn-primary" value="修改订单">
                                </form>
                            </div>
                            <div style="display:<?php echo ($np->fk_newspub_status==1)?'':'none';?>">
                                <form action="<?php echo $this->url('newspub',
                                array('action' => 'confirm', 'id' => $np->id_newspub)); ?>">
                                    <input type="submit" class="btn btn-primary" value="确认订单">
                                </form>
                            </div>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
.sel
{
    width:150px;height:200px;
}
#pick_media:hover
{
    text-decoration: underline;
}
select, #appproduct
{
    width: 100%;
}
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>