<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");    
        if($user_type == 1)
        {    
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">           
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="新闻发布">
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="修改订单">
                    </form>
                </div>
            </div>
            </br>
            <div id="pubedit">
                <h4>编辑订单：</h4>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'newspub', 
                    array(
                        'action' => 'edit',
                        'id'     => $this->id,
                    )
                ));
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_newspub'));
                echo $this->formHidden($form->get('fk_product'));
                ?>
                <tr>
                    <td class="tdlabel">标题</td>
                    <td>
                        <?php echo $this->formRow($form->get('title')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">正文</td>
                    <td>
                        <?php echo $this->formRow($form->get('body')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">产品名称</td>
                    <td>
                        <?php echo $product->name;?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">产品描述</td>
                    <td>
                        <?php echo $product->description;?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td>
                        <?php echo $this->formRow($form->get('download_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td>
                        <?php echo $this->formRow($form->get('appstore_links')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td>
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td>
                        <img src="<?php echo $barcode_path;?>" height="200" width="200">
                        </br>
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">发布方式</td>
                    <td>
                        <?php
                            $arr_pub_mode = array(
                                '1' => '单篇发布',
                                '2' => '打包发布',
                                );
                            echo $this->escapeHtml($arr_pub_mode[$np->fk_pub_mode]);
                            echo $this->formHidden($form->get('fk_pub_mode'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <div class="linkbtns">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                        <div>
                            <form action="/newspub/detail/<?php echo $id;?>">
                                <input type="submit" class="btn btn-primary" value="取消">
                            </form>
                        </div>
                    </td>
                </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>


<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>