<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">

<div id="indexpage" class="indexpage">
    <h1>新闻发布</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="user" class="user">
                <ul>
                    <li>
                        <span>用户: <?php echo $user;?></span>
                        <a href="/user/logout">退出</a>
                    </li>
                    <li><a href="">企业资料</a></li>
                    <li><a href="">我的账户</a></li>
                    <li><a href="">我的订单</a></li>
                    <li><a href="">APP新闻助手</a></li>
                </ul>
            </div>
            <div id="sidebar">
                <ul>
                    <!--
                    <li>
                        <a href="netmonitor"><span>网络监测</span></a>
                    </li>
                    -->
                    <li class="submenu">
                        <a href="#"><span>新闻发布</span></a>
                        <ul>
                            <li><a href="/newspub/add">我要发布</a></li>
                            <li><a href="/newspub/index">发布管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>产品测评</span></a>
                        <ul>
                            <li><a href="/evaluate/add">我要评测</a></li>
                            <li><a href="/evaluate/index">评测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>新闻撰写</span></a>
                        <ul>
                            <li><a href="/writer/add">我要撰稿</a></li>
                            <li><a href="/writer/index">撰稿管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>媒体选题</span></a>
                        <ul>
                            <li><a href="/topic/current">当期选题</a></li>
                            <li><a href="/topic/mgmt">选题管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="interview">媒体采访</a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="mid" class="span8 mid">            
            <div>
                <form action="/newspub/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要发布">
                </form>
                <!--<button id="pubedit" class="btn btn-primary">我要发布</button>  
                <button id="pubmgmt" class="btn btn-primary">订单管理</button>-->
            </div>
            </br>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>我的新闻发布订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>订单号</th>
                        <th>业务内容</th>
                        <th>发布方式</th>
                        <th>订单状态</th>
                    </tr>
                    <?php foreach($paginator as $np): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($np->id_newspub);?></td>
                        <td><a href="<?php echo $this->url('newspub',array('action'=>'detail','id'=>$np->id_newspub));?>"><?php echo $this->escapeHtml($np->title);?></a></td>
                        <td><?php echo $this->escapeHtml($np->fk_pub_mode);?></td>
                        <td><?php echo $this->escapeHtml($np->fk_newspub_status);?></td>
                    </tr>
                    <?php endforeach; ?>

                </table>

<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination/search.phtml');
?>
                </div>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<!--
<script>
$("div#pubedit").hide();
$("button#pubmgmt").hide();

$(document).ready(function(){

  $("button#pubedit").click(function(){
    $(this).hide();
    $("div#pubmgmt").hide();
    $("div#pubedit").show();
    $("button#pubmgmt").show();
  });

  $("button#pubmgmt").click(function(){
    $(this).hide();
    $("div#pubedit").hide();
    $("div#pubmgmt").show();
    $("button#pubedit").show();
  });
});
</script>
-->

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>