<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻发布</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">            
            <div>
                <!--
                <form action="/newspub">
                    <input type="submit" class="btn btn-primary" value="订单管理">
                </form>
            -->
            </div>
            </br>
            <div id="pubedit">
                <h4>填写新闻链接：</h4>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'newspub', 
                    array(
                        'action' => 'publish',
                        'id'     => $this->id,
                    )
                ));
                /*$form->add(array(
                    'name' => 'score',
                    'attributes' => array(
                        'type' => 'hidden',
                    ),
                ));*/
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_npmedia'));
                ?>
                <tr>
                    <td class="tdlabel">新闻链接</td>
                    <td>
                        <?php echo $this->formRow($form->get('news_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>


<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>