<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">         
            <div>
                <!--
                <form action="/newspub">
                    <input type="submit" class="btn btn-primary" value="订单管理">
                </form>
            -->
            </div>
            </br>
            <div id="pubedit">
                <h4>填写新闻链接：</h4>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'newspub', 
                    array(
                        'action' => 'publish',
                        'id'     => $this->id,
                    )
                ));
                /*$form->add(array(
                    'name' => 'score',
                    'attributes' => array(
                        'type' => 'hidden',
                    ),
                ));*/
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_npmedia'));
                ?>
                <tr>
                    <td class="tdlabel">新闻链接</td>
                    <td>
                        <?php echo $this->formRow($form->get('news_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>


<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>