<h1>用户管理：</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="userinfo">
                <h4>用户：<?php echo $user;?></h4>
            </div>
            <div>
                <a href="/user/admin">用户管理</a>
            </div>
            <div>
                <a href="/product/admin">所有产品</a>
            </div>
            <div>
                <a href="/newspub/admin">新闻发布</a>
            </div>
            <div id="medialogos" class="medialogos">
                合作媒体
            </div>
        </div>
        <div id="mid" class="span8 mid">
            <div id="appinfo" class="widget-box">
                <div class="widget-title">
                    <h4>用户信息——</h4>
                </div>
                <div class="widget-content nopadding">
                    <table id="tbappinfo" class="table table-bordered table-striped">
                        <tr>
                            <th>id</th>
                            <th>用户名</th>
                            <th>用户类型</th>
                            <th>真实姓名</th>
                            <th>电子邮箱</th>
                        </tr>
                        <?php foreach ($allusers as $u):?>
                        <tr>
                            <td><?php echo $u->id; ?></td>
                            <td><a href="/user/detail/<?php echo $u->id ;?>"><?php echo $u->username; ?></a></td>
                            <td><?php echo $u->fk_user_type; ?> </td>
                            <td><?php echo $u->real_name; ?> </td>
                            <td><?php echo $u->email; ?> </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div#userinfo
{
    border: 1px solid black;
}
</style>