<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">   
        <?php 
        set_include_path("public/include");
        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="appinfo" class="widget-box">
                <div class="widget-title">
                    <h4>用户信息——</h4>
                </div>
                <div class="widget-content nopadding">
                    <?php
                    $arr_user_type = array(
                        '1' => '企业用户',
                        '2' => '媒体用户',
                        '3' => '普通管理员用户',
                        '4' => '超级管理员用户',
                        );
                    ?>
                    <table id="tbappinfo" class="table table-bordered table-striped">
                        <tr>
                            <th>id</th>
                            <th>用户名</th>
                            <th>用户类型</th>
                            <!--<th>真实姓名</th>-->
                            <th>电子邮箱</th>
                        </tr>
                        <?php foreach ($allusers as $u):?>
                        <tr>
                            <td><?php echo $u->id; ?></td>
                            <td><a href="/user/detail/<?php echo $u->id ;?>"><?php echo $u->username; ?></a></td>
                            <td>
                                <?php 
                                if(array_key_exists($u->fk_user_type, $arr_user_type))
                                {
                                    echo $arr_user_type[$u->fk_user_type]; 
                                }
                                else
                                {
                                    echo "用户类型错误！";
                                }
                                ?> 
                            </td>
                            <!--<td><?php //echo $u->real_name; ?> </td>-->
                            <td><?php echo $u->email; ?> </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
