
<div id="indexpage" class="indexpage">
    <div id="main" class="container"> 
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");
        switch ($target_user->fk_user_type) {
            case 1:
                include 'sidebar_enterprise.phtml';
                break;
            case 2:
                include 'sidebar_media.phtml';
                break;
            case 3:
                include 'sidebar_admin.phtml';
                break;            
            default:
                
                break;
        }         
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div>
                <?php
                $arr_user_type = array(
                    '1' => '企业用户',
                    '2' => '媒体用户',
                    '3' => '管理员用户',
                    );
                ?>
                <table>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action',$this->url(
                        'user',
                        array(
                            'action' => 'changepassword',
                            'id'     => $target_user->id,
                        )
                    ));
                    $form->add(array(
                        'name' => 'originalpassword',
                        'attributes' => array(
                            'type' => 'password',
                            'placeholder' => '*原密码',
                            ),
                        ));
                    $form->add(array(
                        'name' => 'password',
                        'attributes' => array(
                            'type' => 'password',
                            'placeholder' => '*新密码',
                            ),
                        ));
                    $form->add(array(
                        'name' => 'confirmpassword',
                        'attributes' => array(
                            'type' => 'password',
                            'placeholder' => '*确认新密码',
                            ),
                        ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('username'));
                    echo $this->formHidden($form->get('real_name'));
                    echo $this->formHidden($form->get('fk_user_type'));
                    echo $this->formHidden($form->get('email'));
                    echo $this->formHidden($form->get('is_writer'));
                    ?>
                    <tr>
                        <td class="tdlabel">用户名：</td>
                        <td><?php echo $target_user->username;?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">原密码：</td>
                        <td><?php echo $this->formRow($form->get('originalpassword'));?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">新密码：</td>
                        <td><?php echo $this->formRow($form->get('password'));?></td>
                    </tr>
                    <tr>
                        <td class="tdlabel">确认新密码：</td>
                        <td><?php echo $this->formRow($form->get('confirmpassword'));?></td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit'));?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>


<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>