<h1>用户详细信息：</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <div id="userinfo">
                <h3>用户信息：</h3>
                <?php
                $arr_user_type = array(
                    '1' => '企业用户',
                    '2' => '媒体用户',
                    '3' => '普通管理员用户',
                    '4' => '超级管理员用户',
                    );
                ?>
                <table>
                    <tr>
                        <td>id：</td>
                        <td><?php echo $target_user->id;?></td>
                        <td>用户名：</td>
                        <td><?php echo $target_user->username;?></td>
                    </tr>
                    <tr>
                        <td>电子邮箱：</td>
                        <td><?php echo $target_user->email;?></td>
                        <td>密码：</td>
                        <td><?php echo $target_user->password;?></td>                        
                    </tr>
                    <tr>
                        <td>用户类型：</td>
                        <td>
                            <?php 
                            if(array_key_exists($target_user->fk_user_type, $arr_user_type))
                            {
                                echo $arr_user_type[$target_user->fk_user_type];
                            }
                            else
                            {
                                echo "用户类型“ ".$target_user->fk_user_type." ”不存在！";
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if($target_user->fk_user_type == 2)
                            {
                                echo "是否自由撰稿人：";
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            $arr_is_writer = array(
                                '1' => 'Yes',
                                '0' => 'No',
                            );
                            if($target_user->fk_user_type == 2)
                            {
                                echo $arr_is_writer[$target_user->is_writer];
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>创建人：</td>
                        <td><?php echo $target_user->created_by; ?></td>
                        <td>创建日期：</td>
                        <td><?php echo $target_user->created_at; ?></td>
                    </tr>
                    <tr>
                        <td>修改人：</td>
                        <td><?php echo $target_user->updated_by; ?></td>
                        <td>修改日期：</td>
                        <td><?php echo $target_user->updated_at; ?></td>
                    </tr>
                </table>
                <div>
                    <div class="linkbtns">
                        <form action="/user/edit/<?php echo $target_user->id;?>">
                            <input type="submit" class="btn btn-primary" value="修改用户信息">
                        </form>
                    </div>
                    <div class="linkbtns">
                        <form action="/user/delete/<?php echo $target_user->id;?>">
                            <input type="submit" class="btn btn-danger" value="删除此用户">
                        </form>
                    </div>
                    <div>
                        <form action="/user/admin">
                            <input type="submit" class="btn btn-primary" value="返回列表">
                        </form>
                    </div>
                </div>
            </div>
            <div id="enterpriseinfo" style="display:<?php echo ($enterprise)?'':'none';?>;">
                <h3>企业信息：</h3>
                <table>
                    <tr>
                        <td>公司信息：</td>
                    </tr>
                    <tr>
                        <td>id：</td>
                        <td><?php echo $enterprise->id_enterprise; ?></td>
                        <td>企业名称：</td>
                        <td><?php echo $enterprise->name; ?></td>
                    </tr>
                    <tr>
                        <td>所在地：</td>
                        <td><?php echo $enterprise->location; ?></td>
                        <td>地址：</td>
                        <td><?php echo $enterprise->address; ?></td>
                    </tr>
                    <tr>
                        <td>发票抬头：</td>
                        <td><?php echo $enterprise->invoice_title; ?></td>
                        <td>发票类型：</td>
                        <td><?php echo $enterprise->invoice_type; ?></td>
                    </tr>
                    <tr>
                        <td>联系人信息：</td>
                    </tr>
                    <tr>
                        <td>姓名：</td>
                        <td><?php echo $enterprise->contacter_name; ?></td>
                        <td>职位：</td>
                        <td><?php echo $enterprise->contacter_post; ?></td>
                    </tr>
                    <tr>
                        <td>电话：</td>
                        <td><?php echo $enterprise->contacter_phone; ?></td>
                        <td>邮箱：</td>
                        <td><?php echo $enterprise->contacter_email; ?></td>
                    </tr>
                    <tr>
                        <td>创建人：</td>
                        <td><?php echo $enterprise->created_by; ?></td>
                        <td>创建日期：</td>
                        <td><?php echo $enterprise->created_at; ?></td>
                    </tr>
                    <tr>
                        <td>修改人：</td>
                        <td><?php echo $enterprise->updated_by; ?></td>
                        <td>修改日期：</td>
                        <td><?php echo $enterprise->updated_at; ?></td>
                    </tr>
                </table>
                <div>
                    <div>
                        <form action="/enterprise/admin/<?php echo $enterprise->id_enterprise;?>">
                            <input type="submit" class="btn btn-primary" value="修改企业信息">
                        </form>
                    </div>
                </div>
            </div>
            <div id="mediainfo" style="display:<?php echo ($media)?'':'none';?>;">
                <h3>媒体信息：</h3>
                <table>
                    <tr>
                        <td>公司信息：</td>
                    </tr>
                    <tr>
                        <td>id：</td>
                        <td><?php echo $media->id_media; ?></td>
                        <td>企业名称：</td>
                        <td><?php echo $media->name; ?></td>
                    </tr>
                    <tr>
                        <td>所在地：</td>
                        <td><?php echo $media->location; ?></td>
                        <td>地址：</td>
                        <td><?php echo $media->address; ?></td>
                    </tr>
                    <tr>
                        <td>发票抬头：</td>
                        <td><?php echo $media->invoice_title; ?></td>
                        <td>发票类型：</td>
                        <td><?php echo $media->invoice_type; ?></td>
                    </tr>
                    <tr>
                        <td>联系人信息：</td>
                    </tr>
                    <tr>
                        <td>姓名：</td>
                        <td><?php echo $media->contacter_name; ?></td>
                        <td>职位：</td>
                        <td><?php echo $media->contacter_post; ?></td>
                    </tr>
                    <tr>
                        <td>电话：</td>
                        <td><?php echo $media->contacter_phone; ?></td>
                        <td>邮箱：</td>
                        <td><?php echo $media->contacter_email; ?></td>
                    </tr>
                    <tr>
                        <td>创建人：</td>
                        <td><?php echo $media->created_by; ?></td>
                        <td>创建日期：</td>
                        <td><?php echo $media->created_at; ?></td>
                    </tr>
                    <tr>
                        <td>修改人：</td>
                        <td><?php echo $media->updated_by; ?></td>
                        <td>修改日期：</td>
                        <td><?php echo $media->updated_at; ?></td>
                    </tr>
                </table>
                <div>
                    <div>
                        <form action="/media/admin/<?php echo $media->id_media;?>">
                            <input type="submit" class="btn btn-primary" value="修改公司信息">
                        </form>
                    </div>
                </div>
            </div>
            <div id="creditinfo" style="display:<?php echo ($credit)?'':'none';?>;">
                <h3>现金账户：</h3>
                <table>
                    <tr>
                        <td>id：</td>
                        <td><?php echo $credit->id_credit; ?></td>
                        <td>账户余额：</td>
                        <td><?php echo '人民币 '.$credit->amount.' 元'; ?></td>
                    </tr>
                    <tr>
                        <td>创建人：</td>
                        <td><?php echo $credit->created_by; ?></td>
                        <td>创建日期：</td>
                        <td><?php echo $credit->created_at; ?></td>
                    </tr>
                    <tr>
                        <td>修改人：</td>
                        <td><?php echo $credit->updated_by; ?></td>
                        <td>修改日期：</td>
                        <td><?php echo $credit->updated_at; ?></td>
                    </tr>                    
                </table>
                <div>
                    <div class="linkbtns">
                        <form action="/credit/charge/<?php echo $credit->id_credit;?>">
                            <input type="submit" class="btn btn-primary" value="充值">
                        </form>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <div id="creditlog" style="display:<?php echo ($creditlog)?'':'none';?>;" class="widget-box">
                <div class="widget-title">
                    <h3>最近交易记录：</h3>
                </div>
                <div class="widget-content nopadding">
                    <?php 
                    $arr_service_type = array(
                        '1' => '充值',
                        '2' => '新闻发布(单篇)',
                        '3' => '新闻发布(打包)',
                        '4' => '产品评测',
                        '5' => '媒体评测',
                        '6' => '新闻撰写',
                        '7' => '媒体撰稿',
                        '8' => '网络监测(6个月)',
                        '9' => '网络监测(12个月)',
                    );
                    ?>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>订单号</th>
                            <th>交易类型</th>
                            <th>交易金额</th>
                            <th>交易日期</th>
                            <th>经办人</th>
                        </tr>
                        <?php foreach($creditlog as $log): ?>
                        <tr>
                            <td><?php echo $log->order_no; ?></td>
                            <td><?php echo $arr_service_type[$log->fk_service_type]; ?></td>
                            <td>
                                <?php 
                                $sign = '';
                                if($log->fk_service_type==1){
                                    $sign = '+';
                                }
                                echo $sign.$log->amount.'元'; 
                                ?>
                            </td>
                            <td><?php echo $log->date_time; ?></td>
                            <td><?php echo $log->created_by; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>