<h1>用户详细信息：</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <div>
                <?php
                $arr_user_type = array(
                    '1' => '企业用户',
                    '2' => '媒体用户',
                    '3' => '管理员用户',
                    );
                ?>
                <table>
                    <tr>
                        <td>id：</td>
                        <td><?php echo $target_user->id;?></td>
                    </tr>
                    <tr>
                        <td>用户名：</td>
                        <td><?php echo $target_user->username;?></td>
                    </tr>
                    <tr>
                        <td>密码：</td>
                        <td><?php echo $target_user->password;?></td>
                    </tr>
                    <tr>
                        <td>真实姓名：</td>
                        <td><?php echo $target_user->real_name;?></td>
                    </tr>
                    <tr>
                        <td>用户类型：</td>
                        <td>
                            <?php 
                            if(array_key_exists($target_user->fk_user_type, $arr_user_type))
                            {
                                echo $arr_user_type[$target_user->fk_user_type];
                            }
                            else
                            {
                                echo "用户类型“ ".$target_user->fk_user_type." ”不存在！";
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>电子邮箱：</td>
                        <td><?php echo $target_user->email;?></td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <div class="linkbtns">
                                <form action="/user/edit/<?php echo $target_user->id;?>">
                                    <input type="submit" class="btn btn-primary" value="修改用户信息">
                                </form>
                            </div>
                            <div class="linkbtns">
                                <form action="/user/delete/<?php echo $target_user->id;?>">
                                    <input type="submit" class="btn btn-danger" value="删除此用户">
                                </form>
                            </div>
                            <div>
                                <form action="/user/admin">
                                    <input type="submit" class="btn btn-primary" value="返回列表">
                                </form>
                            </div>
                        </td>
                    </tr>


                </table>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>