<h1>用户详细信息：</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <div>
                <?php
                $arr_user_type = array(
                    '1' => '企业用户',
                    '2' => '媒体用户',
                    '3' => '管理员用户',
                    );
                ?>
                <table>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action',$this->url(
                        'user',
                        array(
                            'action' => 'edit',
                            'id'     => $target_user->id,
                        )
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('username'));
                    ?>
                    <tr>
                        <td>id：</td>
                        <td><?php echo $target_user->id;?></td>
                    </tr>
                    <tr>
                        <td>用户名：</td>
                        <td><?php echo $target_user->username;?></td>
                    </tr>
                    <tr>
                        <td>密码：</td>
                        <td><?php echo $this->formRow($form->get('password'));?></td>
                    </tr>
                    <tr>
                        <td>真实姓名：</td>
                        <td><?php echo $this->formRow($form->get('real_name'));?></td>
                    </tr>
                    <tr>
                        <td>用户类型：</td>
                        <td><?php echo $this->formRow($form->get('fk_user_type'));?></td>
                    </tr>
                    <tr>
                        <td>电子邮箱：</td>
                        <td><?php echo $this->formRow($form->get('email'));?></td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit'));?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div#userinfo
{
    border: 1px solid black;
}
</style>