<?php

$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'mediasignup')));
$form->add(array(
			'name' => 'is_writer',
			'type' => 'Zend\Form\Element\Select',
			'attributes' => array(
				'id' => 'is_writer'
				),
			'options' => array(
				'value_options' => array(
					'1' => '我是自由撰稿人',
					'0' => '我不是自由撰稿人',
					),
				),
			));
$form->prepare();
?>
<h1>媒体用户注册：</h1>
<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('fk_user_type'));
echo "</br>";
echo $this->formRow($form->get('username'));
echo "</br>";
//echo $this->formRow($form->get('real_name'));
//echo "</br>";
echo $this->formRow($form->get('email'));
echo "</br>";
echo $this->formRow($form->get('is_writer'));
echo "</br>";
echo $this->formRow($form->get('password'));
echo "</br>";
echo $this->formRow($form->get('confirmpassword'));
echo "</br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>

