<?php

$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'mediasignup')));
$form->add(array(
			'name' => 'is_writer',
			'type' => 'Zend\Form\Element\Select',
			'attributes' => array(
				'id' => 'is_writer'
				),
			'options' => array(
				'value_options' => array(
					'1' => '我是自由撰稿人',
					'0' => '我不是自由撰稿人',
					),
				),
			));
$form->prepare();
?>
<h1>媒体用户注册：</h1>
<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('fk_user_type'));
echo "</br>";
echo $this->formRow($form->get('username'));
echo "</br>";
?>
<span id="dupe_hint"></span>
<?php
//echo $this->formRow($form->get('real_name'));
//echo "</br>";
echo $this->formRow($form->get('email'));
echo "</br>";
echo $this->formRow($form->get('is_writer'));
echo "</br>";
echo $this->formRow($form->get('password'));
echo "</br>";
echo $this->formRow($form->get('confirmpassword'));
echo "</br>";
?>
<input id="terms" type="checkbox">我同意<a href="/user/terms" target="view_frame">用户协议</a></input>
</br>
<input type="button" class="btn" value="立即注册" onClick="signup_med();"/>
<?php
//echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>


<script>
function checkDupe(str)
{
    if(str.length == 0)
    {
        document.getElementById("dupe_hint").innerHTML = "";
        return;
    }
    //alert("aoaokaka");
    if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp = new XMLHttpRequest();
    }
    else
    {// code for IE6, IE5
        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
    }
    xmlhttp.onreadystatechange = function()
    {
        if (xmlhttp.readyState == 4 && xmlhttp.status == 200)
        {
            document.getElementById("dupe_hint").innerHTML = xmlhttp.responseText;
        }
    }
    xmlhttp.open("GET","/user/check?q=" + str, true);
    xmlhttp.send();
}
function signup_med()
{
    var is_agree_terms = document.getElementById("terms").checked;  
    var form_user = document.getElementById("user");
    if(is_agree_terms){
        form_user.submit();
    }else{
        alert("必须同意用户协议才能注册。");
    }
}
</script>