<?php

$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'signup')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('fk_user_type'));
echo "</br>";
echo $this->formRow($form->get('username'));
echo "</br>";
echo $this->formRow($form->get('email'));
echo "</br>";
echo $this->formRow($form->get('password'));
echo "</br>";
echo $this->formRow($form->get('confirmpassword'));
echo "</br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>

