<div style="padding:20px;">
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'signup')));
/*$form->add(array(
    'name' => 'fk_user_type',
    'type'  => 'Zend\Form\Element\Select',
    'attributes' => array(
        'id' => 'usertype',
    ),
    'options' => array(
        'value_options' => array(
			''  => '*用户类型',
			'1' => '企业用户',
			'2' => '媒体用户',
        ),
    ),
));*/
$form->prepare();
?>
<h1>企业用户注册：</h1>
<?php

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('fk_user_type'));
echo "</br>";
echo $this->formRow($form->get('username'));
echo "</br>";
?>
<span id="dupe_hint"></span>
<?php
//echo $this->formRow($form->get('real_name'));
//echo "</br>";
echo $this->formRow($form->get('email'));
echo "</br>";
echo $this->formRow($form->get('password'));
echo "</br>";
echo $this->formRow($form->get('confirmpassword'));
echo "</br>";
?>
<input id="terms" type="checkbox">我同意<a href="/user/terms" target="view_frame">用户协议</a></input>
</br>
<input type="button" class="btn" value="立即注册" onClick="signup_ent();"/>
<?php
//echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<script>
function checkDupe(str)
{
    if(str.length == 0)
    {
        document.getElementById("dupe_hint").innerHTML = "";
        return;
    }
    //alert("aoaokaka");
    if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp = new XMLHttpRequest();
    }
    else
    {// code for IE6, IE5
        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
    }
    xmlhttp.onreadystatechange = function()
    {
        if (xmlhttp.readyState == 4 && xmlhttp.status == 200)
        {
            document.getElementById("dupe_hint").innerHTML = xmlhttp.responseText;
        }
    }
    xmlhttp.open("GET","/user/check?q=" + str, true);
    xmlhttp.send();
}
function signup_ent()
{
    var is_agree_terms = document.getElementById("terms").checked;  
    var form_user = document.getElementById("user");
    if(is_agree_terms){
        form_user.submit();
    }else{
        alert("必须同意用户协议才能注册。");
    }
}
</script>
