<?php

$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'signup')));
/*$form->add(array(
    'name' => 'fk_user_type',
    'type'  => 'Zend\Form\Element\Select',
    'attributes' => array(
        'id' => 'usertype',
    ),
    'options' => array(
        'value_options' => array(
			''  => '*用户类型',
			'1' => '企业用户',
			'2' => '媒体用户',
        ),
    ),
));*/
$form->prepare();
?>
<h1>企业用户注册：</h1>
<?php

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('fk_user_type'));
echo $this->formRow($form->get('is_writer'));
echo "</br>";
echo $this->formRow($form->get('username'));
echo "</br>";
//echo $this->formRow($form->get('real_name'));
//echo "</br>";
echo $this->formRow($form->get('email'));
echo "</br>";
echo $this->formRow($form->get('password'));
echo "</br>";
echo $this->formRow($form->get('confirmpassword'));
echo "</br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>

