<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">

<div id="message" class="container">
	<div id="head" class="row">
		<div class="span2 left">
			<h4>站内信</h4>
		</div>
		<div class="span8 right">
			<button class="btn btn-primary"><a class="btn-a" href="/message">返回</a></button>
			<button class="btn btn-primary">刷新</button>
			<button class="btn btn-primary">删除</button>
		</div>
	</div>
	<div id="body" class="row">
		<div id="left" class="span2 left">
			<form action="/message/compose">
				<input type="submit" class="btn btn-primary" value="写邮件">
			</form>
			<a href="/message">收件箱</a>
		</br>
			<a href="/message/sent">已发邮件</a>
		</br>
			<a href="/message/draft">草稿</a>
		</div>
		<div id="right" class="span8 right">
			<table>		
				<tr>					
					<td>发件人</td>
					<td><?php echo $this->escapeHtml($message->from);?></td>
				</tr>
				<tr>					
					<td>收件人</td>
					<td><?php echo $this->escapeHtml($message->to);?></td>
				</tr>
				<tr>					
					<td>抄送</td>
					<td><?php echo $this->escapeHtml($message->cc);?></td>
				</tr>
				<tr>
					<td>主题</td>
					<td><?php echo $this->escapeHtml($message->subject);?></td>
				</tr>
			</table>
			<textarea>
				<?php echo $this->escapeHtml($message->body);?>
			</textarea>				
		</div>
	</div>
</div>

<style>
input, textarea
{
	width:100%;
}
.minput
{
	/*display: table-row;*/
}
.hiddeninput
{
	/*visibility: collapse;*/
	display: none;
}
table
{
	width: 100%;
}
.btn-a
{
	color:white;
}
.subject
{
	width: 80%;
}
input[type="text"]
{
	margin-bottom: 0px;
	border: 1px #ffffff;
	box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
	width: 100%;
}
.container
{
	background-image: "/";
}
div#head
{
	border-bottom:1px solid #000000;
	margin-bottom: 4px;
}
div#body
{
	margin-top: 8px;
}
</style>




