<h1>Admin Index</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
        CONTAINER
    <div id="row" class="row">
        ROW
        <div id="left" class="span4 left">
            SPAN4 LEFT
            <div id="userinfo">
                <h4>用户：</h4>
            </div>
            <div id="medialogos" class="medialogos">
                合作媒体
            </div>
        </div>
        <div id="mid" class="span4 mid">
            SPAN4 MID
            <div id="slides" class="slides">
                焦点推荐图
            </div>
            <div id="abstract" class="abstract">
                摘要
            </div>
            <div id="news" class="news">
                新闻与评测
            </div>
        </div>
        <div id="right" class="span4 right">
            SPAN4 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div#userinfo
{
    border: 1px solid black;
}
</style>