<h1>Admin Index</h1>


<div id="indexpage" class="indexpage">
    <div id="main" class="container"> 
    <div class="row" class="row">
        <?php 
        set_include_path("public/include");
        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span6 mid">
            <div id="slides" class="slides">
                焦点推荐图
            </div>
            <div id="abstract" class="abstract">
                摘要
            </div>
            <div id="news" class="news">
                新闻与评测
            </div>
        </div>
        <?php
        set_include_path("public/include");
        include 'sidebar_right.phtml';
        ?>
    </div>
    </div>
</div>

<style>
div#userinfo
{
    border: 1px solid black;
}
</style>