<div id="main" class="container" style="padding:20px;">
	<form id='login' action="/user/checkadminuser" method='post' accept-charset='UTF-8'>
		<h4>管理员用户登录</h4>
    	<input name="username" type="text" placeholder="用户名"/>
    	<input name="password" type="password" placeholder="密码"/>
    	<div class="remember">
        	<!--<div class="left">
        		<input id="remember_me" type="checkbox">
        		<label for="remember_me">记住我</label>
        	</div>-->
    		<div class="right">
            	<a href="/user/forgotpassword">忘记密码</a>
            </div>
        </div>
    	<input type="submit" class="btn" value="登录"/>
	</form>
</div>
