<div id="main" class="container" style="width:1170px;">
	<div id="row" class="row">
		<div class="span">
			<div id="user" class="user">
				<div id="enterpriseuser" class="enterpriseuser">
					<!--<a href="/enterprise/index">企业用户</a>-->
					<form id='login' action="/user/checkadminuser" method='post' accept-charset='UTF-8'>
						<h1>管理员用户登录</h1>
    					<input name="username" type="text" placeholder="用户名"/>
    					<input name="password" type="password" placeholder="密码"/>
    					<div class="remember">
        					<div class="right">
            					<a href="/user/forgotpassword">忘记密码</a>
        					</div>
    					</div>
    					<input type="submit" class="btn" value="登录"/>
					</form>
				</div>				
			</div>			
		</div>		
	</div>
</div>

<style>
div.navbar
{
    display: none;
}
</style>