<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        //->prependStylesheet($this->basePath() . '/jsDatePick/jsDatePick_ltr.min.css')
                        //->prependStylesheet($this->basePath() . '/css/unicorn.grey.css') 
                        //->prependStylesheet($this->basePath() . '/css/unicorn.main.css') 

                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
                                      //->prependFile($this->basePath() . '/jsDatePick/jsDatePick.min.1.3.js') 
                                      ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('APPBUZZ') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>                        
                    </div><!--/.nav-collapse -->
                    <div id="user-nav" class="navbar navbar-inverse">
                        <ul class="nav btn-group">
                            <li class="btn btn-inverse" >
                                <a title="" href="#">
                                    <i class="icon icon-user"></i> 
                                    <span class="text">用户资料</span>
                                </a>
                            </li>
                            <li class="btn btn-inverse" >
                                <a title="站内信" href="/message">
                                    <i class="icon icon-envelope"></i> 
                                    <span class="text">站内信</span>
                                </a>
                            </li>
                            <!--<li class="btn btn-inverse">
                                <a title="" href="#">
                                    <i class="icon icon-cog"></i> 
                                    <span class="text">设置</span>
                                </a>
                            </li>-->
                            <li class="btn btn-inverse">
                                <a title="" href="/user/logout">
                                    <i class="icon icon-share-alt"></i> 
                                    <span class="text">退出登录</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
               <p>&copy; 2013 by Appbuzz.cn <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
