<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('APP媒体推广平台 '. $this->translate('APPbuzz.cn'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/icon-1.png'))
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        //->prependStylesheet($this->basePath() . '/jsDatePick/jsDatePick_ltr.min.css')
                        //->prependStylesheet($this->basePath() . '/css/unicorn.grey.css') 
                        //->prependStylesheet($this->basePath() . '/css/unicorn.main.css') 

                        ?>

         <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/app.js') 
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      
                                      //->prependFile($this->basePath() . '/jsDatePick/jsDatePick.min.1.3.js') 
                                      ?>
        
    </head>
    <body>
        <?php 
        set_include_path("public/include");
        include_once("analyticstracking.php") 
        ?>
        <div class="banner">
            <div class="container">
                <ul class="links clearfix">
                    <li><a href="/reports">APP新闻报告</a></li>
                    <li><a href="/services">客户服务</a></li>
                    <li><a href="/rss.xml">RSS订阅</a></li>
                    <li><a href="/aboutus">关于我们</a></li>
                </ul>
                <div class="clearfix">
                    <a class="logo" href="/"></a>
                    <div class="adv"><img src="<?php echo $this->basePath() . '/images/adv.jpg'?>"/></div>
                </div>
                
            </div>
        </div>
        
        <div class="container main">
            <div class="line">
                <div class="left-line"></div>
            </div>

           

            <?php echo $this->content; ?>
            
        </div> <!-- /container -->

        <footer>

           <p class="container">&copy; 2013 by Appbuzz.cn <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        

        <?php echo $this->inlineScript() ?>
    </body>
</html>
