<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>撰稿外包</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="撰稿外包">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="订单发布">
                </form>
            </div>
            <div id="writeredit">
                <div>
                    <h4>新建订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'writer', 
                    array(
                        'action' => 'add',
                    )
                ));
                $arr_products = array( '' => '' );
                foreach ($products as $p)
                {
                    $arr_products[$p->id_product] = $p->name;
                }
                $form->add(array(
                    'name' => 'fk_product',
                    'type'  => 'Zend\Form\Element\Select',
                    'attributes' => array(
                        'id' => 'appproduct',
                        'onchange' => "change_product();",
                        ),
                    'options' => array(
                        'value_options' => $arr_products,
                        ),
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_writer'));
                ?>
                <tr>
                    <td class="tdlabel">App产品：</td>
                    <td>
                        <?php echo $this->formRow($form->get('fk_product')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿要求：</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('requirement')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">信息提示：</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('hint')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">最大邀约数量：</td>
                    <td>
                        <?php echo $this->formRow($form->get('order_limit')); ?>
                        <span id="plus_one" class="plus_one" onclick="plus_one();">+1</span>
                        <span id="minus_one" class="minus_one" onclick="minus_one();">-1</span>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿配图：</td>
                    <td>
                        <?php echo $this->formRow($form->get('screen_shot')); ?>
                    </td>
                </tr>
                <!--
                <tr>
                    <td class="tdlabel">选择新闻撰写媒体</td>
                    <td>
                        <?php //echo $this->formRow($form->get('wrtmedia')); ?>
                    </td>
                </tr>
                -->
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('web_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>                
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿费用：</td>
                    <td>1500元/篇（800字左右）</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<script>
function plus_one()
{
    var order_limit = Number(document.getElementById("order_limit").value);
    document.getElementById("order_limit").value = order_limit + 1;
}
function minus_one()
{
    var order_limit = Number(document.getElementById("order_limit").value);
    if(order_limit>1){
        document.getElementById("order_limit").value = order_limit - 1;
    }
}
function change_product()
{
    var product = document.getElementById("appproduct").value;
    var product_web = new Array();
    var product_appstore = new Array();
    var product_android = new Array();
    <?php foreach($js_products as $pro): ?>
    product_web[<?php echo $pro->id_product; ?>] = "<?php echo $pro->web_link; ?>";
    product_appstore[<?php echo $pro->id_product; ?>] = "<?php echo $pro->appstore_link; ?>";
    product_android[<?php echo $pro->id_product; ?>] = "<?php echo $pro->androidmkt_link; ?>";
    <?php endforeach; ?>
    document.getElementById("web_link").value = product_web[product];
    document.getElementById("appstore_link").value = product_appstore[product];
    document.getElementById("androidmkt_link").value = product_android[product];
}
</script>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
span.plus_one
{
    background-color: black;
    color: white;
    cursor: pointer;
    padding: 2px;
}
span.minus_one
{
    background-color: grey;
    color: white;
    cursor: pointer;
    padding: 2px;
}
</style>
