<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <?php

            ?>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>撰稿外包订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <?php
                    /*$arr_id_wrt = array();
                    foreach($writer as $wrt)
                    {
                        $arr_id_wrt[$wrt->id_writer] = $wrt;
                    }*/
                    $arr_id_user = array();
                    foreach($all_users as $au)
                    {
                        $arr_id_user[$au->id] = $au;
                    }
                    $arr_id_product = array();
                    foreach ($products as $pd) 
                    {
                        $arr_id_product[$pd->id_product] = $pd;
                    }
                    $arr_fk_wrtmedia_status = array(
                        '1' => '新订单',
                        '2' => '媒体拒绝',
                        '3' => '媒体接受',
                        '4' => '企业拒绝',
                        '5' => '企业接受',
                        '6' => '初稿提交',
                        '7' => '初稿修改',
                        '8' => '终稿提交',
                        '9' => '稿件通过',
                        '10' => '订单终止',
                    );
                    ?>
                    <tr>
                        <th>母订单号</th>
                        <th>发布企业</th>
                        <th>产品名称</th>
                        <th>子订单号</th>
                        <th>撰稿媒体</th>
                        <th>订单状态</th>
                        <th>创建日期</th>
                        <!--<th>操作</th>-->
                    </tr>
                    <?php foreach($wrtjoinwm as $tjm): ?>
                    <tr>
                        <td>
                            <a href="/writer/detail/<?php echo $tjm->id_writer; ?>">
                                <?php echo $tjm->order_no; ?>
                            </a>
                        </td>
                        <td><?php echo $tjm->created_by; ?></td>
                        <td>
                            <?php
                            if(array_key_exists($tjm->fk_product, $arr_id_product))
                            {
                                echo $arr_id_product[$tjm->fk_product]->name; 
                            }
                            ?>
                        </td>
                        <td><?php echo $tjm->wm_order_no; ?></td>
                        <td>
                            <?php                             
                            if(array_key_exists($tjm->wm_fk_media_user, $arr_id_user))
                            {
                                echo $arr_id_user[$tjm->wm_fk_media_user]->username; 
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if(array_key_exists($tjm->wm_fk_wrtmedia_status, $arr_fk_wrtmedia_status))
                            {
                                echo $arr_fk_wrtmedia_status[$tjm->wm_fk_wrtmedia_status];
                            }
                            ?>
                        </td>
                        <td>
                            <?php echo $tjm->wm_created_at; ?>
                        </td>
                    </tr>
                    <?php endforeach;?>
                </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
