<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻撰写</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="user" class="user">
                用户: <?php echo $user;?>
                <a href="/user/logout">退出</a>
            </br>
                <a href="">企业资料</a>
            </br>
                <a href="">我的账户</a>
            </br>
                <a href="">我的订单</a>
            </br>
                <a href="">APP新闻助手</a>           
            </div>
            <div id="netmonitor" class="netmonitor">
                <a href="netmonitor">网络监测</a>
            </div>
            <div id="newspublish" class="newspublish">
                <a href="/newspub">新闻发布</a>
            </div>
            <div id="appevaluating" class="appevaluating">
                <a href="appevaluating">产品评测</a>
            </div>
            <div id="newsedit" class="newsedit">
                <a href="newsedit">新闻撰写</a>
            </div>
            <div id="topic" class="topic">
                <a href="topic">媒体选题</a>
            </div>
            <div id="interview" class="interview">
                <a href="interview">媒体采访</a>
            </div>
        </div>

        <div id="mid" class="span6 mid">  
            <div class="linkbtns">
                <form action="/product/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="新闻撰写">
                </form>
            </div>
            <div>
                <form action="/product/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要撰稿">
                </form>
            </div>
            <div id="evamgmt">
                <h4>订单号：<?php echo $this->escapeHtml($writer->id_writer);?></h4>
                <table class="pubdetailtable">
                    <tr>
                        <td class="tdlabel">App产品：</td>
                        <td>
                            <?php echo $this->escapeHtml($product->name); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">撰稿要求：</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->requirement);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">信息提示：</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->hint);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->web_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->appstore_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->androidmkt_link);?>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->barcode);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">撰稿费用：</td>
                        <td>1500元/篇（800字左右）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <form action="<?php echo $this->url('writer',
                                array('action' => 'edit', 'id' => $writer->id_writer)) ;?>">
                                <input type="submit" class="btn btn-primary" value="修改订单">
                            </form>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
</style>