<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻撰写</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
            <div id="user" class="user">
                <ul>
                    <li>
                        <span>用户: <?php echo $user;?></span>
                        <a href="/user/logout">退出</a>
                    </li>
                    <li><a href="">企业资料</a></li>
                    <li><a href="">我的账户</a></li>
                    <li><a href="">我的订单</a></li>
                    <li><a href="">APP新闻助手</a></li>
                </ul>
            </div>
            <div id="sidebar">
                <ul>
                    <!--
                    <li>
                        <a href="netmonitor"><span>网络监测</span></a>
                    </li>
                    -->
                    <li class="submenu">
                        <a href="#"><span>新闻发布</span></a>
                        <ul>
                            <li><a href="/newspub/add">我要发布</a></li>
                            <li><a href="/newspub/index">发布管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>产品测评</span></a>
                        <ul>
                            <li><a href="/evaluate/add">我要评测</a></li>
                            <li><a href="/evaluate/index">评测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>新闻撰写</span></a>
                        <ul>
                            <li><a href="/writer/add">我要撰稿</a></li>
                            <li><a href="/writer/index">撰稿管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>媒体选题</span></a>
                        <ul>
                            <li><a href="/topic/current">当期选题</a></li>
                            <li><a href="/topic/mgmt">选题管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="interview">媒体采访</a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="mid" class="span8 mid">  
            <div class="linkbtns">
                <form action="/writer/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="新闻撰写">
                </form>
            </div>
            <div>
                <form action="/writer/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要撰稿">
                </form>
            </div>
            <div id="evamgmt">
                <h4>订单号：<?php echo $this->escapeHtml($writer->id_writer);?></h4>
                <table class="pubdetailtable">
                    <tr>
                        <td class="tdlabel">App产品：</td>
                        <td>
                            <?php echo $this->escapeHtml($product->name); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">撰稿要求：</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->requirement);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">信息提示：</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->hint);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->web_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->appstore_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->androidmkt_link);?>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->barcode);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">撰稿费用：</td>
                        <td>1500元/篇（800字左右）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <form action="<?php echo $this->url('writer',
                                array('action' => 'edit', 'id' => $writer->id_writer)) ;?>">
                                <input type="submit" class="btn btn-primary" value="修改订单">
                            </form>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
</style>