<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻撰写</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">  
            <div class="linkbtns">
                <form action="/writer/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="新闻撰写">
                </form>
            </div>
            <div>
                <form action="/writer/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要撰稿">
                </form>
            </div>
            <div id="evamgmt">
                <h4>订单号：<?php echo $this->escapeHtml($writer->id_writer);?></h4>
                <table class="pubdetailtable">
                    <?php
                    $arr_id_user = array();
                    foreach($allusers as $u)
                    {
                        $arr_id_user[$u->id] = $u->username;
                    }
                    $arr_wrtmedia_status = array(
                        1 => '新订单',
                        2 => '媒体拒绝',
                        3 => '媒体接受',
                        4 => '企业拒绝',
                        5 => '企业接受',
                    );
                    ?>
                    <tr>
                        <td class="tdlabel">App产品：</td>
                        <td>
                            <?php echo $this->escapeHtml($product->name); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">撰稿要求：</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->requirement);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">信息提示：</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->hint);?>
                        </td>
                    </tr>
                    <!--<tr>
                        <td class="tdlabel">评测媒体：</td>
                        <td>
                            <?php /*
                            foreach ($this->media_assignees as $media)
                            {
                                echo $media."; ";
                            }*/
                            ?>
                        </td>
                    </tr>-->
                    <tr>
                        <td class="tdlabel">web下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->web_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">Appstore下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->appstore_link);?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">安卓市场下载链接</td>
                        <td>
                            <?php echo $this->escapeHtml($writer->androidmkt_link);?>
                    <tr>
                        <td class="tdlabel">下载二维码</td>
                        <td>
                            <img src="<?php echo $barcode_path;?>" height="200" width="200">
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">撰稿费用：</td>
                        <td>1500元/篇（800字左右）</td>
                    </tr>
                    <tr>
                        <td class="tdlabel">接受评测的媒体：</td>
                        <td>
                            <div class="widget-box">
                                <div class="widget-content nopadding">
                                    <table class="table table-bordered table-striped">
                                        <tr>
                                            <th>媒体名称</th>
                                            <th>订单状态</th>
                                            <th>操作</th>
                                        </tr>
                                        <?php foreach ($wrtmedias as $wm): ?>
                                        <tr>
                                            <td><?php echo $arr_id_user[$wm->fk_media_user]; ?></td>
                                            <td>
                                                <div class="linkbtns">
                                                    <?php echo $arr_wrtmedia_status[$wm->fk_wrtmedia_status]; ?>
                                                </div>
                                            </td>
                                            <td>
                                                <div id="btns" style="display:<?php echo ($wm->fk_wrtmedia_status==3)?"inline":"none";?>">
                                                    <div class="linkbtns">
                                                        <form action="<?php echo $this->url('writer',
                                                        array('action' => 'entacc', 'id' => $wm->id_wrtmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary" value="接受">
                                                        </form>
                                                    </div>
                                                    <div>
                                                        <form action="<?php echo $this->url('writer',
                                                        array('action' => 'entrej', 'id' => $wm->id_wrtmedia)) ;?>">
                                                            <input type="submit" class="btn btn-primary" value="拒绝">
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>                                            
                                        </tr>
                                        <?php endforeach;?>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <form action="<?php echo $this->url('writer',
                                array('action' => 'edit', 'id' => $writer->id_writer)) ;?>">
                                <input type="submit" class="btn btn-primary" value="修改订单">
                            </form>
                        </td>
                    </tr>                    
                </table>
            </div>
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>
