
<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");    
        if($user_type == 1)
        {    
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">  
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="撰稿外包">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="修改订单">
                </form>
            </div>
            <div id="evaedit">
                <div>
                    <h4>修改订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'writer', 
                    array(
                        'action' => 'edit',
                        'id'     => $this->id,
                    )
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_writer'));
                echo $this->formHidden($form->get('fk_product'));
                ?>
                <tr>
                    <td class="tdlabel">订单号：</td>
                    <td>
                        <?php echo $order_no; ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿类型：</td>
                    <td>
                        <?php 
                        $arr_writer_type = array(
                            '1' => '企业新闻',
                            '2' => '产品新闻',
                            '3' => '其他',
                        );
                        if(array_key_exists($writer->fk_writer_type, $arr_writer_type)){
                            echo $arr_writer_type[$writer->fk_writer_type]; 
                        }else{
                            echo "撰稿类型不正确！";
                        }
                        
                        ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">App产品：</td>
                    <td>
                        <?php echo $product->name; ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿要求：</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('requirement')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">信息提示：</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('hint')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">有效日期：</td>
                    <td>
                        <?php echo $this->formRow($form->get('due_date')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿配图：</td>
                    <td>
                        <?php foreach($screenshots as $ss): ?>
                        <img src="<?php echo substr($ss->path.$ss->filename,6);?>" height="300" width="300">
                        <a href="/writer/deletescreenshotfromedit/<?php echo $ss->id_screenshot; ?>" 
                            class="btn btn-danger btn-mini">删除图片</a>
                        <?php endforeach; ?>       
                        <?php echo $this->formRow($form->get('screen_shot')); ?>                 
                    </td>
                </tr>
                <!--<tr>
                    <td class="tdlabel">评测媒体：</td>
                    <td>
                        <?php /*
                        foreach ($this->media_assignees as $media)
                        {
                            echo $media."; ";
                        }*/
                        ?>
                    </td>
                </tr>-->
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('web_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>                
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <img src="<?php echo $barcode_path;?>" height="200" width="200">
                        </br>
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿费用：</td>
                    <td>1200元/篇（800字左右）</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
$(document).ready(function(){   
    /*$( "#due_date" ).val("<?php echo $writer->due_date; ?>");*/
    $( "#due_date" ).datepicker({
        minDate: 0,
        dateFormat: "yy-mm-dd",
    });
});
</script>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>
