<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>新闻撰写</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>

        <div id="mid" class="span8 mid">
            <div class="linkbtns">
                <form action="/writer/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="新闻撰写">
                </form>
            </div>
            <div>
                <form action="/writer/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要撰稿">
                </form>
            </div>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>我的新闻撰写订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <?php
                    $arr_products = array();
                    foreach ($products as $p)
                    {
                        $arr_products[$p->id_product] = $p->name;
                    }
                    ?>
                    <tr>
                        <th>App产品</th>
                        <th>撰稿要求</th>
                        <th>信息提示</th>
                        <th>创建日期</th>
                    </tr>
                    <?php foreach($paginator as $np): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($arr_products[$np->fk_product]);?></td>
                        <td><a href="<?php echo $this->url('writer',array('action'=>'detail','id'=>$np->id_writer));?>"><?php echo $this->escapeHtml($np->requirement);?></a></td>
                        <td><?php echo $this->escapeHtml($np->hint);?></td>
                        <td><?php echo $this->escapeHtml($np->created_at);?></td>
                    </tr>
                    <?php endforeach; ?>

                </table>

<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination/search.phtml');
?>
                </div>
            </div>
            
        </div>

        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>
