
<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div class="linkbtns">
                <form action="/writer/index">
                    <input type="submit" class="btn btn-primary linkbtn" value="新闻撰写">
                </form>
            </div>
            <div>
                <form action="/writer/add">
                    <input type="submit" class="btn btn-primary linkbtn" value="我要撰稿">
                </form>
            </div>
            <div id="writeredit">
                <div>
                    <h4>新建订单：</h4>
                </div>
                <table>
                <?php 
                $form = $this->form;
                $form->setAttribute('action',$this->url(
                    'writer', 
                    array(
                        'action' => 'neworder',
                    )
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_writer'));
                echo $this->formHidden($form->get('fk_product'));
                ?>
                <tr>
                    <td class="tdlabel">App产品：</td>
                    <td>
                        <?php echo $product->name; ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿要求：</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('requirement')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">信息提示：</td>
                    <td class="tdtextarea">
                        <?php echo $this->formRow($form->get('hint')); ?>
                    </td>
                </tr>
                <!--<tr>
                    <td class="tdlabel">建议媒体采用的产品截图：</td>
                    <td>
                        
                    </td>
                </tr>-->
                <!--<tr>
                    <td class="tdlabel">选择新闻撰写媒体</td>
                    <td>
                        <?php //echo $this->formRow($form->get('wrtmedia')); ?>
                    </td>
                </tr>-->
                <tr>
                    <td class="tdlabel">web下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('web_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">Appstore下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('appstore_link')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">安卓市场下载链接</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('androidmkt_link')); ?>
                    </td>
                </tr>                
                <tr>
                    <td class="tdlabel">下载二维码</td>
                    <td class="tdinput">
                        <?php echo $this->formRow($form->get('barcode')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="tdlabel">撰稿费用：</td>
                    <td>1500元/篇（800字左右）</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>
