
<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?>
        <div id="mid" class="span9 mid"  style="padding-top:20px"> 
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="自由撰稿人">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="需求列表">
                </form>
            </div>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>新闻撰写需求列表</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <?php
                    $arr_product_name = array();
                    foreach ($products as $p)
                    {
                        $arr_product_name[$p->id_product] = $p->name;
                    }
                    $arr_wrt_wm = array(); 
                    $arr_wm_stat = array(); 
                    $arr_wrt_order = array();
                    foreach ($wrtmedia as $wm)
                    {
                        $arr_wrt_wm[$wm->fk_writer]    = $wm->id_wrtmedia;
                        $arr_wm_stat[$wm->fk_writer]   = $wm->fk_wrtmedia_status;
                        $arr_wrt_order[$wm->fk_writer] = $wm->order_no;
                    }
                    $arr_wrtmedia_status = array(
                        1 => '新订单',
                        2 => '媒体拒绝',
                        3 => '媒体接受，等待企业回复',
                        4 => '企业拒绝',
                        5 => '企业接受',
                        6 => '一稿提交',
                        7 => '一稿修改',
                        8 => '二稿提交',
                        9 => '稿件通过',
                        10 => '订单终止',
                    );
                    ?>

                    <tr>
                        <th>订单号</th>
                        <th>App产品</th>
                        <th>撰稿要求</th>
                        <th>创建者</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    <?php foreach($writer as $wrt): ?>
                    <?php 
                    if(array_key_exists($wrt->id_writer, $arr_wrt_order)||$wrt->fk_writer_status==1)
                    {
                        continue;
                    }
                    ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('writer',
                            array('action' => 'wrtinfo', 'id' => $wrt->id_writer)); ?>">
                            <?php echo $this->escapeHtml($wrt->order_no); ?>
                            </a>
                        </td>
                        <td>
                            <?php 
                            if($wrt->fk_product){
                                echo $this->escapeHtml($arr_product_name[$wrt->fk_product]);
                            }else{

                            }                            
                            ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($wrt->requirement);?>
                        </td>
                        <td><?php echo $this->escapeHtml($wrt->created_by);?></td>
                        <td>     
                            <div id="btns" style="display:<?php echo array_key_exists($wrt->id_writer, $arr_wrt_wm)?"none":"inline";?>">
                                新订单
                            </div>
                            <div id="status" style="display:<?php echo array_key_exists($wrt->id_writer, $arr_wrt_wm)?"inline":"none";?>"> 
                                <?php echo $this->escapeHtml($arr_wrtmedia_status[$arr_wm_stat[$wrt->id_writer]]);?>
                            </div>
                        </td>
                        <td>
                            <div id="btns" style="display:<?php echo array_key_exists($wrt->id_writer, $arr_wrt_wm)?"none":"inline";?>">
                                <div class="linkbtns">
                                    <form action="<?php echo $this->url('writer',
                                    array('action' => 'mediaacc', 'id' => $wrt->id_writer)) ;?>">
                                        <input type="submit" class="btn btn-primary btn-mini" value="接受">
                                    </form>
                                </div>
                                <div>
                                    <form action="<?php echo $this->url('writer',
                                    array('action' => 'mediarej', 'id' => $wrt->id_writer)) ;?>">
                                        <input type="submit" class="btn btn-primary btn-mini" value="拒绝">
                                    </form>
                                </div>
                            </div>
                            <div id="details" style="display:<?php echo (array_key_exists($wrt->id_writer, $arr_wrt_wm)&&($arr_wm_stat[$wrt->id_writer]==5))?"inline":"none";?>">
                                <div>
                                    <form action="<?php echo $this->url('writer',
                                    array('action' => 'firstdraft', 'id' => $arr_wrt_wm[$wrt->id_writer])) ;?>">
                                        <input type="submit" class="btn btn-primary btn-mini" value="开始撰稿">
                                    </form>
                                </div>
                            </div>
                            <div id="details" style="display:<?php echo (array_key_exists($wrt->id_writer, $arr_wrt_wm)&&($arr_wm_stat[$wrt->id_writer]==7))?"inline":"none";?>">
                                <div>
                                    <form action="<?php echo $this->url('writer',
                                    array('action' => 'seconddraft', 'id' => $arr_wrt_wm[$wrt->id_writer])) ;?>">
                                        <input type="submit" class="btn btn-primary btn-mini" value="撰写二稿">
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                </div>
            </div>
            

        </div>

        
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
