<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>我要发布</h1>  
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
        CONTAINER
    <div id="row" class="row">
        ROW
        <div id="left" class="span2 left">
            <div id="user" class="user">
                <ul>
                    <li>
                        <span>用户: <?php echo $user;?></span>
                        <a href="/user/logout">退出</a>
                    </li>
                    <li><a href="">媒体资料</a></li>
                    <li><a href="">我的账户</a></li>
                    <li><a href="">我的订单</a></li>
                    <li><a href="">APP新闻助手</a></li>
            </div>
            <div id="sidebar">
                <ul>
                    <li class="submenu">
                        <a href="#"><span>发布选题</span></a>
                        <ul>
                            <li><a href="/topic/add">我要发布</a></li>
                            <li><a href="/topic/index">选题管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>评测APP</span></a>
                        <ul>
                            <li><a href="#">评测邀约</a></li>
                            <li><a href="#">评测管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>采访APP</span></a>
                        <ul>
                            <li><a href="#">采访邀约</a></li>
                            <li><a href="#">采访管理</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#"><span>自由撰稿人</span></a>
                        <ul>
                            <li><a href="#">需求列表</a></li>
                            <li><a href="#">撰稿管理</a></li>
                        </ul>
                    </li>
                </ul>
            </div>   
        </div>
        <div id="mid" class="span8 mid">
            <div>
                <div class="linkbtns">
                    <form action="/topic/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="发布选题">
                    </form>
                </div>
                <div>
                    <form action="/topic/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我要发布">
                    </form>
                </div>
            </div>
            <div id="addtopic">
                <div>
                    <h4>新建选题：</h4>
                </div>
                <table>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action',$this->url(
                        'topic',
                        array(
                            'action' => 'add',
                        )
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_topic'));
                    ?>
                    <tr>
                        <td class="tdlabel">选题类型：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('topic_type')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">选题概要：</td>
                        <td class="tdtextarea">
                            <?php echo $this->formRow($form->get('abstract')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">征集APP产品类型：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('app_type')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>        
        <div id="right" class="span4 right">
            SPAN4 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>