<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <?php

            ?>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>媒体选题订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <?php
                    $arr_id_user = array();
                    foreach($all_users as $au)
                    {
                        $arr_id_user[$au->id] = $au;
                    }
                    $arr_id_product = array();
                    foreach ($products as $pd) 
                    {
                        $arr_id_product[$pd->id_product] = $pd;
                    }
                    $arr_fk_tpcontact_status = array(
                        '1' => '联系中',
                        '2' => '已结束',
                    );
                    $arr_fk_topic_status = array(
                        '1' => '待发布',
                        '2' => '征集中',
                        '3' => '已结束',
                    );
                    ?>
                    <tr>
                        <th>母订单号</th>
                        <th>发布媒体</th>
                        <th>产品名称</th>
                        <th>订单状态</th>
                        <th>子订单号</th>
                        <th>联系企业</th>
                        <th>订单状态</th>
                        <th>创建日期</th>
                        <!--<th>操作</th>-->
                    </tr>
                    <?php foreach($tpjointc as $tjc): ?>
                    <tr>
                        <td>                       
                            <a href="/topic/detail/<?php echo $tjc->id_topic; ?>">
                                <?php echo $tjc->order_no; ?>
                            </a>
                        </td>
                        <td><?php echo $tjc->created_by; ?></td>
                        <td>
                            <?php
                            if(array_key_exists($tjc->tc_fk_product, $arr_id_product))
                            {
                                echo $arr_id_product[$tjc->tc_fk_product]->name; 
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if(array_key_exists($tjc->fk_topic_status, $arr_fk_topic_status))
                            {
                                echo $arr_fk_topic_status[$tjc->fk_topic_status];
                            }
                            ?>
                        </td>
                        <td><?php echo $tjc->tc_order_no; ?></td>
                        <td>
                            <?php                             
                            if(array_key_exists($tjc->tc_fk_enterprise_user, $arr_id_user))
                            {
                                echo $arr_id_user[$tjc->tc_fk_enterprise_user]->username; 
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if(array_key_exists($tjc->tc_fk_tpcontact_status, $arr_fk_tpcontact_status))
                            {
                                echo $arr_fk_tpcontact_status[$tjc->tc_fk_tpcontact_status];
                            }
                            ?>
                        </td>
                        <td><?php echo $tjc->tc_created_at; ?></td>
                        <!--<td></td>-->
                    </tr>
                    <?php endforeach; ?>
                </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>