<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
        
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");  
        include 'sidebar_media.phtml'; 
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="媒体选题"/>
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="选题信息"/>
                    </form>
                </div>
            </div>
            <div id="addtopic">
                <div>
                    <h4>订单号：<?php echo $tpcontact->order_no;?></h4>
                </div>
                <table>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url(
                        'topic',
                        array(
                            'action' => 'contactlink',
                            'id'     => $tpcontact->id_tpcontact,
                        )
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_tpcontact'));
                    ?>
                    <tr>
                        <td class="tdlabel">选题链接：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('topic_link')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>      
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>