<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");    
        if($user_type == 1)
        {    
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="媒体选题"/>
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="选题信息"/>
                    </form>
                </div>
            </div>
            <div id="addtopic">
                <div>
                    <h4>订单号：<?php echo $tpcontact->order_no;?></h4>
                </div>
                <table>
                    <tr>
                        <td class="tdlabel">选题类型：</td>
                        <td class="tdinput">
                            <?php echo $topic->topic_type; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">选题概要：</td>
                        <td class="tdtextarea">
                            <?php echo $topic->abstract; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">征集APP产品类型：</td>
                        <td class="tdinput">
                            <?php echo $topic->app_type; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">有效日期：</td>
                        <td class="tdinput">
                            <?php echo $topic->due_date; ?>
                        </td>
                    </tr>
                    </br>
                    <tr>
                        <td class="tdlabel">产品名称：</td>
                        <td class="tdinput">
                            <?php echo isset($product)?$product->name:"未选择产品"; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品类型：</td>
                        <td>
                            <?php echo isset($product)?$product->type:"未选择产品"; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">产品描述：</td>
                        <td>
                            <?php echo isset($product)?$product->description:"未选择产品"; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">企业：</td>
                        <td class="tdinput">
                            <?php echo $tpcontact->created_by; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">附件：</td>
                        <td class="tdinput">
                            <?php if(isset($attachment)){ ?>
                            <a href="<?php echo substr($attachment->path,6).$attachment->filename; ?>" title="点击下载">
                                <?php echo $attachment->filename; ?>
                            </a>
                            <?php 
                            }else{
                                echo "未上传附件";
                            } 
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">说明：</td>
                        <td class="tdinput">
                            <?php echo $tpcontact->introduction; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">选题链接：</td>
                        <td>
                            <a href="//<?php echo $tpcontact->topic_link; ?>">
                                <?php 
                                if($tpcontact->fk_tpcontact_status==2){
                                    echo $tpcontact->topic_link; 
                                }                                
                                ?>
                            </a>
                            <p style="color:grey">
                            <?php
                            if($tpcontact->fk_tpcontact_status==1){
                                echo "选题完成后请填入链接地址，以表示对选题参与者的尊重";
                            }
                            ?>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">订单状态：</td>
                        <td>
                            <?php
                            $arr_tpcontact_status = array(
                                '1' => '已投递资料',
                                '2' => '已完成',
                            );
                            echo $arr_tpcontact_status[$tpcontact->fk_tpcontact_status]; ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <div class="linkbtns">
                                <?php 
                                $btn_label = ($tpcontact->fk_tpcontact_status==1)?"完成选题":"修改选题链接";
                                ?>
                                <form action="/topic/contactlink/<?php echo $tpcontact->id_tpcontact; ?>">
                                    <input type="submit" class="btn btn-primary" value="<?php echo $btn_label;?>"/>
                                </form>
                            </div>
                            <div>
                                <form action="/topic/detail/<?php echo $topic->id_topic; ?>">
                                    <input type="submit" class="btn btn-primary" value="返回"/>
                                </form>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>     
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>