
<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
        
    <div id="row" class="row">
        
        <?php 
        set_include_path("public/include");  
        if($usertype == 1)
        {
            include 'sidebar_enterprise.phtml';
        }      
        elseif($usertype == 2)
        {
            include 'sidebar_media.phtml'; 
        }
        else
        {
            include 'sidebar_admin.phtml';
        }
        ?>

        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="发布选题"/>
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="订单详情"/>
                    </form>
                </div>
            </div>
            <div id="addtopic">
                <div>
                    <h4>选题<?php echo $topic->order_no.":";?></h4>
                </div>
                <table>
                    <tr>
                        <td class="tdlabel">选题类型：</td>
                        <td class="tdinput">
                            <?php echo $topic->topic_type; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">选题概要：</td>
                        <td class="tdtextarea">
                            <?php echo $topic->abstract; ?>
                        </td>
                    </tr>
                    <!--<tr>
                        <td class="tdlabel">选题链接：</td>
                        <td class="tdtextarea">
                            <?php echo $topic->topic_link; ?>
                        </td>
                    </tr>-->
                    <tr>
                        <td class="tdlabel">征集APP产品类型：</td>
                        <td class="tdinput">
                            <?php echo $topic->app_type; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">有效日期：</td>
                        <td class="tdinput">
                            <?php echo $topic->due_date; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">创建人：</td>
                        <td class="tdinput">
                            <?php echo $topic->created_by; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">创建日期：</td>
                        <td class="tdinput">
                            <?php echo $topic->created_at; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">修改人：</td>
                        <td class="tdinput">
                            <?php echo $topic->updated_by; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">修改日期：</td>
                        <td class="tdinput">
                            <?php echo $topic->updated_at; ?>
                        </td>
                    </tr>
                    <tr>
                        <?php
                        $arr_tpcontact_status = array(
                            '1' => '联系中',
                            '2' => '已结束',
                        );                        
                        $arr_id_user = array();
                        foreach($all_users as $a_u)
                        {
                            $arr_id_user[$a_u->id] = $a_u->username;
                        }
                        $arr_id_product = array();
                        foreach($products as $p)
                        {
                            $arr_id_product[$p->id_product] = $p->name;
                        }
                        ?>
                        <td class="tdlabel">有意联系的企业：</td>
                        <td>
                            <div class="widget-box">
                                <div class="widget-content nopadding">
                                    <table class="table table-bordered table-striped">
                                        <tr>
                                            <th>订单号</th>
                                            <th>产品名称</th>
                                            <th>企业名称</th>
                                            <th>订单状态</th>
                                            <th>操作</th>
                                        </tr>
                                        <?php foreach ($tpcontact as $tc): ?>
                                        <tr>
                                            <td><?php echo $tc->order_no; ?></td>
                                            <td>
                                            <?php
                                                if(array_key_exists($tc->fk_product, $arr_id_product))
                                                {
                                                    echo $arr_id_product[$tc->fk_product];
                                                }
                                            ?>
                                            </td>
                                            <td><?php echo $arr_id_user[$tc->fk_enterprise_user]; ?></td>
                                            <td>
                                                <div class="linkbtns">
                                                    <?php echo $arr_tpcontact_status[$tc->fk_tpcontact_status]; ?>
                                                </div>
                                            </td>
                                            <td>
                                                <div id="btns" style="display:<?php echo ($tc->fk_tpcontact_status<3)?"inline":"none";?>">
                                                    <div>
                                                        <form action="<?php echo $this->url('topic',
                                                        array('action' => 'contactinfo', 'id' => $tc->id_tpcontact)) ;?>">
                                                            <input type="submit" class="btn btn-primary btn-mini" value="查看">
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>                                      
                                        </tr>
                                        <?php endforeach;?>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td style="display:<?php echo ($topic->fk_topic_status<2)?'':'none';?>">
                            <form action="/topic/edit/<?php echo $id; ?>" 
                                style="display:<?php echo ($usertype==1)?'none':'inline';?>;">
                                <input type="submit" class="btn btn-primary" value="修改订单"/>
                            </form>
                            <!--
                            <form action="/topic/contact/<?php echo $id; ?>"
                                style="display:<?php echo ($usertype==1)?'inline':'none';?>;">
                                <input type="submit" class="btn btn-primary" value="我要联系"/>
                            </form>
                            -->
                        </td>
                    </tr>
                </table>
            </div>
        </div>  
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>