<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
        
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");    
        if($user_type == 1)
        {    
            include 'sidebar_enterprise.phtml'; 
        }
        elseif($user_type == 3)
        {
            include 'sidebar_admin.phtml';
        }
        ?>       
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="发布选题">
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="订单详情">
                    </form>
                </div>
            </div>
            <div id="addtopic">
                <div>
                    <h4>选题<?php echo $topic->order_no; ?>：</h4>
                </div>
                <table>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action',$this->url(
                        'topic',
                        array(
                            'action' => 'edit',
                            'id'     => $id,
                        )
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_topic'));
                    ?>
                    <tr>
                        <td class="tdlabel">选题类型：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('topic_type')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">选题概要：</td>
                        <td class="tdtextarea">
                            <?php echo $this->formRow($form->get('abstract')); ?>
                        </td>
                    </tr>
                    <!--<tr>
                        <td class="tdlabel">选题链接：</td>
                        <td class="tdtextarea">
                            <?php echo $this->formRow($form->get('topic_link')); ?>
                        </td>
                    </tr>-->
                    <tr>
                        <td class="tdlabel">征集APP产品类型：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('app_type')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdlabel">有效日期：</td>
                        <td class="tdinput">
                            <?php echo $this->formRow($form->get('due_date')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div> 
    </div>
    </div>
</div>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
$(document).ready(function(){
    $( "#f_date_ETA" ).datepicker();
    $( "#f_date_ETA" ).datepicker("option","dateFormat","yy-mm-dd"); 
    $( "#f_date_ETA" ).val("<?php echo $topic->due_date; ?>");
});
</script>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>