<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>选题管理</h1>  
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
        CONTAINER
    <div id="row" class="row">
        ROW
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?> 
        </div>
        <div id="mid" class="span8 mid">
            <div>
                <div class="linkbtns">
                    <form action="/topic/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="发布选题">
                    </form>
                </div>
                <div>
                    <form action="/topic/add">
                        <input type="submit" class="btn btn-primary linkbtn" value="我要发布">
                    </form>
                </div>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>我发布的当期选题:</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>id</th>
                            <th>选题类型</th>
                            <th>选题概要</th>
                            <th>APP类型</th>
                            <th>有效日期</th>
                            <th>创建日期</th>
                        </tr>
                        <?php foreach($current_topics as $tp): ?>
                        <tr onclick="document.location = '/topic/detail/<?php echo $this->escapeHtml($tp->id_topic);?>';">
                            <td>
                                <?php echo $this->escapeHtml($tp->id_topic);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->topic_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->abstract);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->app_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->due_date);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml(substr($tp->created_at,0,10));?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>往期选题:</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>id</th>
                            <th>选题类型</th>
                            <th>选题概要</th>
                            <th>APP类型</th>
                            <th>有效日期</th>
                            <th>创建日期</th>
                        </tr>
                        <?php foreach($past_topics as $pt): ?>
                        <tr onclick="document.location = '/topic/detail/<?php echo $this->escapeHtml($pt->id_topic);?>';">
                            <td>
                                <?php echo $this->escapeHtml($pt->id_topic);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->topic_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->abstract);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->app_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->due_date);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml(substr($pt->created_at,0,10));?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>        
        <div id="right" class="span4 right">
            SPAN4 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>