<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?> 
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="发布选题">
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="选题管理">
                    </form>
                </div>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>我发布的当期选题:</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>订单号</th>
                            <th>选题类型</th>
                            <th>选题概要</th>
                            <th>APP类型</th>
                            <th>有效日期</th>
                            <th>创建日期</th>
                        </tr>
                        <?php foreach($current_topics as $tp): ?>
                        <!--<tr onclick="document.location = '/topic/detail/<?php echo $this->escapeHtml($tp->id_topic);?>';">-->
                        <tr>
                            <td>
                                <a href="/topic/detail/<?php echo $this->escapeHtml($tp->id_topic);?>">
                                    <?php echo $this->escapeHtml($tp->order_no);?>
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->topic_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->abstract);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->app_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($tp->due_date);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml(substr($tp->created_at,0,10));?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>往期选题:</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>订单号</th>
                            <th>选题类型</th>
                            <th>选题概要</th>
                            <th>APP类型</th>
                            <th>有效日期</th>
                            <th>创建日期</th>
                        </tr>
                        <?php foreach($past_topics as $pt): ?>
                        <!--<tr onclick="document.location = '/topic/detail/<?php echo $this->escapeHtml($pt->id_topic);?>';">-->
                        <tr>
                            <td>
                                <a href="/topic/detail/<?php echo $this->escapeHtml($pt->id_topic);?>">
                                    <?php echo $this->escapeHtml($pt->order_no);?>
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->topic_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->abstract);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->app_type);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($pt->due_date);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml(substr($pt->created_at,0,10));?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>     
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>