<div id="indexpage" class="indexpage">
    <div id="main" class="container" >

    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?> 
        <div id="mid" class="span9 mid" style="padding-top:20px">
            <div>
                <div class="linkbtns">
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="媒体选题">
                    </form>
                </div>
                <div>
                    <form action="#">
                        <input type="submit" class="btn btn-primary linkbtn" value="选题管理">
                    </form>
                </div>
            </div>
            <?php
            $arr_contacting = array();
            $arr_finished = array();
            foreach($tpcontacts as $tc)
            {
                if($tc->fk_tpcontact_status == 1)
                {
                    $arr_contacting[$tc->id_tpcontact] = $tc;
                }
                elseif($tc->fk_tpcontact_status == 2)
                {
                    $arr_finished[$tc->id_tpcontact] = $tc;
                }
            }
            $arr_id_user = array();
            foreach($users as $u)
            {
                $arr_id_user[$u->id] = $u->username;
            }
            $arr_id_abstract = array();
            $arr_id_due = array();
            foreach($topics as $tp)
            {
                $arr_id_abstract[$tp->id_topic] = $tp->abstract;
                $arr_id_due[$tp->id_topic] = $tp->due_date;
            }
            $arr_tpcontact_status = array(
                '1' => '联系中',
                '2' => '已结束',
                '3' => '忽略',
            );
            ?>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>联系中的选题:</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>媒体</th>
                            <th>选题概要</th>
                            <th>有效日期</th>
                            <th>状态</th>
                            <th>媒体互动</th>
                        </tr>
                        <?php foreach($arr_contacting as $tc_contacting): ?>                        
                        <tr>
                            <td>
                                <?php echo $this->escapeHtml($arr_id_user[$tc_contacting->fk_media_user]);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($arr_id_abstract[$tc_contacting->fk_topic]);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($arr_id_due[$tc_contacting->fk_topic]);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($arr_tpcontact_status[$tc_contacting->fk_tpcontact_status]);?>
                            </td>
                            <td>
                                <form action="<?php echo $this->url('topic', array('action' => 'viewcontact', 'id' => $tc_contacting->fk_topic)) ;?>">
                                    <input type="submit" class="btn btn-primary btn-mini" value="查看">
                                </form>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>已经发布的选题:</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>媒体</th>
                            <th>选题概要</th>
                            <th>有效日期</th>
                            <th>状态</th>
                            <th>原文地址</th>
                        </tr>
                        <?php foreach($arr_finished as $tc_finished): ?>                        
                        <tr>
                            <td>
                                <?php echo $this->escapeHtml($arr_id_user[$tc_finished->fk_media_user]);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($arr_id_abstract[$tc_finished->fk_topic]);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($arr_id_due[$tc_finished->fk_topic]);?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($arr_tpcontact_status[$tc_finished->fk_tpcontact_status]);?>
                            </td>
                            <td>
                                <a href="<?php echo $tc_finished->topic_link;?>">
                                    <?php echo $tc_finished->topic_link;?>
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>        
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>