<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="addarticle" class="widget-box">
                <div class="widget-title">
                    <h4>创建横幅——</h4>
                </div>
                <div class="widget-content nopadding">
                    <?php
                    $form = $this->form;
                    $form->setAttribute(
                        'action', 
                        $this->url(
                            'article', 
                            array(
                                'action' => 'addbanner',
                            )
                        )
                    );
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_banner'));
                    ?>
                    <table>
                        <tr>
                            <td class="tdlabel">选取文件：</td>
                            <td>
                                <?php echo $this->formRow($form->get('filename')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">横幅链接地址：</td>
                            <td>
                                <?php echo $this->formRow($form->get('url')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <?php 
                                echo $this->formSubmit($form->get('submit'));
                                echo $this->form()->closeTag();
                                ?>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
$(document).ready(function(){
    $( "#f_date_ETA" ).datepicker();
    $( "#f_date_ETA" ).datepicker("option","dateFormat","yy-mm-dd");    
});
</script>

<style>
/*
div.user,.mid,#userinfo
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput
{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea, select, .password
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>