<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="addarticle" class="widget-box">
                <div class="widget-title">
                    <h4>横幅列表——</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>id</th>
                            <th>名称</th>
                            <th>创建人</th>
                            <th>创建日期</th>
                        </tr>
                        <?php foreach($banners as $ban): ?>
                        <tr>
                            <td>
                                <a href="/article/bannerdetail/<?php echo $ban->id_banner; ?>">
                                    <?php echo $ban->id_banner; ?>
                                </a>
                            </td>
                            <td><?php echo $ban->filename; ?></td>
                            <td><?php echo $ban->created_by; ?></td>
                            <td><?php echo $ban->created_at; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid,#userinfo
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput
{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea, select, .password
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>