<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="addarticle" class="widget-box">
                <div class="widget-title">
                    <h4>横幅排序——</h4>
                </div>
                <div class="widget-content nopadding">
                    <?php
                    $arr_id_banner = array();
                    foreach($banners as $ban)
                    {
                        $arr_id_banner[$ban->id_banner] = $ban;
                    }
                    ?>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>序号</th>
                            <th>id</th>
                            <th>名称</th>
                            <th>创建人</th>
                            <th>创建日期</th>
                        </tr>
                        <tr>
                            <td>#1：</td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_1, $arr_id_banner))?$arr_id_banner[$rank->fk_no_1]->id_banner:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_1, $arr_id_banner))?$arr_id_banner[$rank->fk_no_1]->filename:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_1, $arr_id_banner))?$arr_id_banner[$rank->fk_no_1]->created_by:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_1, $arr_id_banner))?$arr_id_banner[$rank->fk_no_1]->created_at:null; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#2：</td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_2, $arr_id_banner))?$arr_id_banner[$rank->fk_no_2]->id_banner:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_2, $arr_id_banner))?$arr_id_banner[$rank->fk_no_2]->filename:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_2, $arr_id_banner))?$arr_id_banner[$rank->fk_no_2]->created_by:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_2, $arr_id_banner))?$arr_id_banner[$rank->fk_no_2]->created_at:null; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#3：</td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_3, $arr_id_banner))?$arr_id_banner[$rank->fk_no_3]->id_banner:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_3, $arr_id_banner))?$arr_id_banner[$rank->fk_no_3]->filename:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_3, $arr_id_banner))?$arr_id_banner[$rank->fk_no_3]->created_by:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_3, $arr_id_banner))?$arr_id_banner[$rank->fk_no_3]->created_at:null; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#4：</td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_4, $arr_id_banner))?$arr_id_banner[$rank->fk_no_4]->id_banner:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_4, $arr_id_banner))?$arr_id_banner[$rank->fk_no_4]->filename:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_4, $arr_id_banner))?$arr_id_banner[$rank->fk_no_4]->created_by:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_4, $arr_id_banner))?$arr_id_banner[$rank->fk_no_4]->created_at:null; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#5：</td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_5, $arr_id_banner))?$arr_id_banner[$rank->fk_no_5]->id_banner:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_5, $arr_id_banner))?$arr_id_banner[$rank->fk_no_5]->filename:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_5, $arr_id_banner))?$arr_id_banner[$rank->fk_no_5]->created_by:null; ?>
                            </td>
                            <td>
                                <?php echo (array_key_exists($rank->fk_no_5, $arr_id_banner))?$arr_id_banner[$rank->fk_no_5]->created_at:null; ?>
                            </td>
                        </tr>
                    </table>
                                <div>
                                    <form action="/article/editbannerrank">
                                        <input type="submit" class="btn btn-primary" value="调整排序">
                                    </form>
                                </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid,#userinfo
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput
{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea, select, .password
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>