<h1>首页管理</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <div id="addarticle" class="widget-box">
                <div class="widget-title">
                    <h4>横幅信息——</h4>
                </div>
                <div class="widget-content nopadding">
                    <table>
                        <tr>
                            <td class="tdlabel">横幅：</td>
                            <td>
                                <img src="<?php echo substr($banner->path,6).$banner->filename;?>" height="300" width="300">
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">id：</td>
                            <td>
                                <?php echo $banner->id_banner; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">名称：</td>
                            <td>
                                <?php echo $banner->filename; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">链接地址：</td>
                            <td>
                                <?php echo $banner->url; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">创建日期：</td>
                            <td>
                                <?php echo $banner->created_at; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">创建人：</td>
                            <td>
                                <?php echo $banner->created_by; ?>
                            </td>
                        </tr>
                        <!--<tr>
                            <td></td>
                            <td>
                                <div>
                                    <form action="/article/edit/<?php echo $article->id_article; ?>">
                                        <input type="submit" class="btn btn-primary" value="修改文章">
                                    </form>
                                </div>
                            </td>
                        </tr>-->
                    </table>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid,#userinfo
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput
{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea, select, .password
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>