<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="addarticle" class="widget-box">
                <div class="widget-title">
                    <h4>首页文章——</h4>
                </div>
                <div class="widget-content nopadding">
                    <table>
                        <tr>
                            <td class="tdlabel">文章标题：</td>
                            <td>
                                <?php echo $article->title; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">作者：</td>
                            <td>
                                <?php echo $article->author; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">发表日期：</td>
                            <td>
                                <?php echo $article->pub_date; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">摘要：</td>
                            <td>
                                <?php echo $article->abstract; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">标签：</td>
                            <td>
                                <?php echo $article->label; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">正文：</td>
                            <td>
                                <?php echo $article->body; ?>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <div>
                                    <form action="/article/edit/<?php echo $article->id_article; ?>">
                                        <input type="submit" class="btn btn-primary" value="修改文章">
                                    </form>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid,#userinfo
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput
{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea, select, .password
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>