<h1>首页管理</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <div id="addarticle" class="widget-box">
                <div class="widget-title">
                    <h4>调整横幅排序——</h4>
                </div>
                <div class="widget-content nopadding">
                    <?php
                    $form = $this->form;
                    $form->setAttribute(
                        'action', 
                        $this->url(
                            'article', 
                            array(
                                'action' => 'editbannerrank',
                            )
                        )
                    );
                    $arr_banners = array('' => '');
                    foreach($banners as $ban)
                    {
                        $arr_banners[$ban->id_banner] = $ban->id_banner.' '.$ban->filename;
                    }
                    $form->add(array(
                        'name' => 'fk_no_1',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_banners,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_2',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_banners,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_3',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_banners,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_4',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_banners,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_5',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_banners,
                            ),
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_rank'));
                    echo $this->formHidden($form->get('name'));
                    echo $this->formHidden($form->get('description'));
                    echo $this->formHidden($form->get('obj_type'));
                    ?>
                    <table>
                        <tr>
                            <td>#1：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_1')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#2：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_2')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#3：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_3')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#4：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_4')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#5：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_5')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <?php 
                                echo $this->formSubmit($form->get('submit'));
                                echo $this->form()->closeTag();
                                ?>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid,#userinfo
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput
{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea, select, .password
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>