<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px;">
            <div id="addarticle" class="widget-box">
                <div class="widget-title">
                    <h4>调整右侧最新注册APP排序——</h4>
                </div>
                <div class="widget-content nopadding">
                    <?php
                    $form = $this->form;
                    $form->setAttribute(
                        'action', 
                        $this->url(
                            'article', 
                            array(
                                'action' => 'editlatestapprank',
                            )
                        )
                    );
                    $arr_products = array('' => '');
                    foreach($products as $p)
                    {
                        $arr_products[$p->id_product] = $p->name.' '.$p->created_by;
                    }
                    $form->add(array(
                        'name' => 'fk_no_1',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_2',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_3',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_4',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_5',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_6',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_7',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_8',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_9',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->add(array(
                        'name' => 'fk_no_10',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            ),
                        'options' => array(
                            'value_options' => $arr_products,
                            ),
                    ));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id_rank'));
                    echo $this->formHidden($form->get('name'));
                    echo $this->formHidden($form->get('description'));
                    echo $this->formHidden($form->get('obj_type'));
                    ?>
                    <table>
                        <tr>
                            <td>#1：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_1')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#2：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_2')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#3：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_3')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#4：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_4')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#5：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_5')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#6：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_6')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#7：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_7')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#8：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_8')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#9：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_9')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>#10：</td>
                            <td>
                                <?php echo $this->formRow($form->get('fk_no_10')); ?>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <?php 
                                echo $this->formSubmit($form->get('submit'));
                                echo $this->form()->closeTag();
                                ?>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid,#userinfo
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput
{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea, select, .password
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>