
<div>
    <div id="main" class="container" >
        
        <div id="row" class="row">
            <?php 
            set_include_path("public/include");        
            include 'sidebar.phtml'; 
            ?>
            <div id="mid" class="span9 mid">
    
                <div class="article">
                    <h2><?php echo $article->title; ?></h2>
                    <div class="meta">作者: <?php echo $article->author; ?>&nbsp;&nbsp;&nbsp;&nbsp;发表日期: <?php echo $article->pub_date; ?></div>
                    <div class="summary"><?php echo $article->abstract; ?></div>
                    <div class="content"><?php echo $article->body; ?></div>
                    <div class="tags"><?php echo $article->label; ?></div>
                </div>
            </div>
        
        </div>
    </div>
</div>
