<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        <div id="mid" class="span9 mid"  style="padding-top:20px;">
            <?php
                $arr_id_user = array();
                foreach($all_users as $u)
                {
                    $arr_id_user[$u->id] = $u->username;
                }
                $arr_fk_keyword_type = array(
                    '1' => '自产品',
                    '2' => '竞争产品',
                );
            ?>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>企业网络监测订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>订单号</th>
                        <th>服务周期</th>
                        <th>开始日期</th>
                        <th>结束日期</th>
                        <th>关键词</th>
                        <th>关键词类型</th>
                        <th>购买人</th>
                        <th>操作</th>
                    </tr>
                    <?php foreach($mntjoinkw as $mt): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($mt->order_no);?></td>
                        <td><?php echo $this->escapeHtml($mt->duration)." 个月";?></td>
                        <td><?php echo $this->escapeHtml(substr($mt->start_date,0,10));?></td>
                        <td><?php echo $this->escapeHtml(substr($mt->end_date,0,10));?></td>
                        <td><?php echo $this->escapeHtml($mt->kw_keyword); ?></td>
                        <td><?php echo $this->escapeHtml($arr_fk_keyword_type[$mt->kw_fk_keyword_type]); ?></td>
                        <td><?php echo $this->escapeHtml($arr_id_user[$mt->fk_enterprise_user]);?></td>
                        <td></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>