<h1>订单管理</h1>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_admin.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid">
            <?php
                $arr_id_user = array();
                foreach($all_users as $u)
                {
                    $arr_id_user[$u->id] = $u->username;
                }
                $arr_fk_keyword_type = array(
                    '1' => '自产品',
                    '2' => '竞争产品',
                );
            ?>
            <div id="pubmgmt" class="widget-box">
                <div class="widget-title">
                    <h4>企业网络监测订单</h4>
                </div>
                <div class="widget-content nopadding">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>订单号</th>
                        <th>服务周期</th>
                        <th>开始日期</th>
                        <th>结束日期</th>
                        <th>关键词</th>
                        <th>关键词类型</th>
                        <th>购买人</th>
                        <th>操作</th>
                    </tr>
                    <?php foreach($mntjoinkw as $mt): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($mt->order_no);?></td>
                        <td><?php echo $this->escapeHtml($mt->duration)." 个月";?></td>
                        <td><?php echo $this->escapeHtml(substr($mt->start_date,0,10));?></td>
                        <td><?php echo $this->escapeHtml(substr($mt->end_date,0,10));?></td>
                        <td><?php echo $this->escapeHtml($mt->kw_keyword); ?></td>
                        <td><?php echo $this->escapeHtml($arr_fk_keyword_type[$mt->kw_fk_keyword_type]); ?></td>
                        <td><?php echo $this->escapeHtml($arr_id_user[$mt->fk_enterprise_user]);?></td>
                        <td></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div#userinfo
{
    border: 1px solid black;
}
</style>