<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        <div id="mid" class="span9 mid"  style="padding-top:20px;"> 
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="网络监测">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="购买服务">
                </form>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>购买网络监测服务</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>服务周期</th>
                            <th>费用</th>
                            <th>操作</th>
                        </tr>
                        <tr>
                            <td>6个月</td>
                            <td><?php echo $price_monitor_six, '元';?></td>
                            <td>
                                <!--<form action="<?php echo $this->url('monitor', array('action' => 'buysixm')) ;?>">
                                    <input type="submit" class="btn btn-primary btn-mini" value="购买">
                                </form>-->
                                <button class="btn btn-primary btn-mini" onClick="check_n_confirm_six()">
                                    购买
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>12个月</td>
                            <td><?php echo $price_monitor_twelve, '元';?></td>
                            <td>
                                <!--<form action="<?php echo $this->url('monitor', array('action' => 'buytwelvem')) ;?>">
                                    <input type="submit" class="btn btn-primary btn-mini" value="购买">
                                </form>-->
                                <button class="btn btn-primary btn-mini" onClick="check_n_confirm_twelve()">
                                    购买
                                </button>
                            </td>
                        </tr>
                    </table>
                </div>
                <div>
                    <span>购买网络监测服务即可获赠媒体选题免费服务。</span>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>
<script>
function check_n_confirm_six()
{
    var price = <?php echo $price_monitor_six;?>;
    var credit = <?php echo $credit->amount - $credit->deposit;?>;
    if(credit < price)
    {
        alert("您的账户余额不足，请先充值");
        window.location.href="/credit/notify";
    }
    else
    {
        if(confirm('确实要确认订单吗?\n\n系统将收取'+price+'元监测费用。'))
        {
            window.location.href = '<?php echo $this->url('monitor',array('action'=>'buysixm')) ;?>'
        }
    }
}
function check_n_confirm_twelve()
{
    var price = <?php echo $price_monitor_twelve;?>;
    var credit = <?php echo $credit->amount - $credit->deposit;?>;
    if(credit < price)
    {
        alert("您的账户余额不足，请先充值");
        window.location.href="/credit/notify";
    }
    else
    {
        if(confirm('确实要确认订单吗?\n\n系统将收取'+price+'元监测费用。'))
        {
            window.location.href = '<?php echo $this->url('monitor',array('action'=>'buytwelvem')) ;?>'
        }
    }
}
</script>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
