<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        <div id="mid" class="span9 mid"  style="padding-top:20px;">
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="网络监测">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="监测订制">
                </form>
            </div>
            <div>
                <table>
                    <?php 
                    $form = $this->form;
                    $form->setAttribute('action',$this->url(
                        'monitor',
                        array(
                            'action' => 'configure',
                        )
                    ));
                    $arr_products = array();
                    foreach ($products as $p)
                    {
                        $arr_products[$p->name] = $p->name;
                    }
                    $form->add(array(
                        'name' => 'myapp',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            'id' => 'appproduct1',
                            //'onchange' => "alert();",
                        ),
                        'options' => array(
                            'value_options' => $arr_products,
                        ),
                    ));
                    $form->add(array(
                        'name' => 'myapp2',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            'id' => 'appproduct2',
                            //'onchange' => "alert();",
                        ),
                        'options' => array(
                            'value_options' => $arr_products,
                        ),
                    ));
                    $form->add(array(
                        'name' => 'myapp3',
                        'type'  => 'Zend\Form\Element\Select',
                        'attributes' => array(
                            'id' => 'appproduct3',
                            //'onchange' => "alert();",
                        ),
                        'options' => array(
                            'value_options' => $arr_products,
                        ),
                    ));
                    $form->prepare();   
                    echo $this->form()->openTag($form);
                    ?>
                    <tr>
                        <td><span>请输入您要监测的APP产品1：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('myapp')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>请输入您要监测的APP产品2：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('myapp2')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>请输入您要监测的APP产品3：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('myapp3')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>请输入您要监测的竞争APP产品1：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('competitorapp')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>请输入您要监测的竞争APP产品2：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('competitorapp2')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>请输入您要监测的竞争APP产品3：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('competitorapp3')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>请输入您要监测的竞争APP产品4：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('competitorapp4')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>请输入您要监测的竞争APP产品5：</span></td>
                        <td>
                            <?php echo $this->formRow($form->get('competitorapp5')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                            <?php echo $this->form()->closeTag(); ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>

<script>
$(document).ready(function(){
    $("#appproduct1").get(0).value = "<?php echo $self1;?>";
    $("#appproduct2").get(0).value = "<?php echo $self2;?>";
    $("#appproduct3").get(0).value = "<?php echo $self3;?>";
    $("#compapp1").get(0).value = "<?php echo $competitor1;?>";
    $("#compapp2").get(0).value = "<?php echo $competitor2;?>";
    $("#compapp3").get(0).value = "<?php echo $competitor3;?>";
    $("#compapp4").get(0).value = "<?php echo $competitor4;?>";
    $("#compapp5").get(0).value = "<?php echo $competitor5;?>";
});
</script>
""

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
