<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>网络监测</h1>  
    <div id="header" class="container" style="width:1170px;"> 
        CONTAINER
        <div class="row">
            ROW
            <div id="logo" class="span2 logo">
                APPBUZZ LOGO
            </div>
            <div id="banner" class="span8 banner">
                BANNER
            </div>
        </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
    <div id="row" class="row">
        <div id="left" class="span2 left">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        </div>
        <div id="mid" class="span8 mid"> 
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="网络监测">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="监测数据">
                </form>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>近期监测数据</h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>新闻</th>
                            <th>时间</th>
                            <th>网站</th>
                            <th>标签</th>
                        </tr>
                        <?php while($row = mysql_fetch_array($result_keyword1_news)){  ?>
                        <tr>
                            <td><?php echo $row['content'];?></td>
                            <td><?php echo $row['tm_post'];?></td>
                            <td><?php echo $row['source_site'];?></td>
                            <td><?php echo $keyword1->keyword; ?></td>
                        </tr>
                        <?php } ?>
                        <?php while($row = mysql_fetch_array($result_keyword2_news)){  ?>
                        <tr>
                            <td><?php echo $row['content'];?></td>
                            <td><?php echo $row['tm_post'];?></td>
                            <td><?php echo $row['source_site'];?></td>
                            <td><?php echo $keyword2->keyword; ?></td>
                        </tr>
                        <?php } ?>
                    </table>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>论坛</th>
                            <th>时间</th>
                            <th>网站</th>
                            <th>标签</th>
                        </tr>
                        <?php while($row = mysql_fetch_array($result_keyword1_forum)){  ?>
                        <tr>
                            <td><?php echo $row['content'];?></td>
                            <td><?php echo $row['tm_post'];?></td>
                            <td><?php echo $row['source_site'];?></td>
                            <td><?php echo $keyword1->keyword; ?></td>
                        </tr>
                        <?php } ?>
                        <?php while($row = mysql_fetch_array($result_keyword2_forum)){  ?>
                        <tr>
                            <td><?php echo $row['content'];?></td>
                            <td><?php echo $row['tm_post'];?></td>
                            <td><?php echo $row['source_site'];?></td>
                            <td><?php echo $keyword2->keyword; ?></td>
                        </tr>
                        <?php } ?>
                    </table>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>微博</th>
                            <th>时间</th>
                            <th>网站</th>
                            <th>标签</th>
                        </tr>
                        <?php while($row = mysql_fetch_array($result_keyword1_weibo)){  ?>
                        <tr>
                            <td><?php echo $row['content'];?></td>
                            <td><?php echo $row['tm_post'];?></td>
                            <td><?php echo $row['source_site'];?></td>
                            <td><?php echo $keyword1->keyword; ?></td>
                        </tr>
                        <?php } ?>
                        <?php while($row = mysql_fetch_array($result_keyword2_weibo)){  ?>
                        <tr>
                            <td><?php echo $row['content'];?></td>
                            <td><?php echo $row['tm_post'];?></td>
                            <td><?php echo $row['source_site'];?></td>
                            <td><?php echo $keyword2->keyword; ?></td>
                        </tr>
                        <?php } ?>
                    </table>
                </div>
                <div>
                    <a href="/monitor/timerangepicker">历史数据查询</a>
                </div>
            </div>
        </div>
        <div id="right" class="span3 right">
            SPAN3 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>

<style>
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
