<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        <div id="mid" class="span9 mid"  style="padding-top:20px;">
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="网络监测">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="监测数据">
                </form>
            </div>
            <div class="widget-box">
                <div class="widget-title">
                    <h4>历史监测数据：从<?php echo " ".$start_date." ";?>到<?php echo " ".$end_date;?></h4>
                </div>
                <div class="widget-content nopadding">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>新闻</th>
                            <th>标签</th>
                        </tr>
                        <?php while($row = mysql_fetch_array($result_keyword1_news)){  ?>
                        <tr>
                            <td><?php echo $row['content']; ?></td>
                            <td><?php echo $keyword1->keyword; ?></td>
                        </tr>
                        <?php } ?>
                        <?php while($row = mysql_fetch_array($result_keyword2_news)){  ?>
                        <tr>
                            <td><?php echo $row['content']; ?></td>
                            <td><?php echo $keyword2->keyword; ?></td>
                        </tr>
                        <?php } ?>
                    </table>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>论坛</th>
                            <th>标签</th>
                        </tr>
                        <?php while($row = mysql_fetch_array($result_keyword1_forum)){  ?>
                        <tr>
                            <td><?php echo $row['content']; ?></td>
                            <td><?php echo $keyword1->keyword; ?></td>
                        </tr>
                        <?php } ?>
                        <?php while($row = mysql_fetch_array($result_keyword2_forum)){  ?>
                        <tr>
                            <td><?php echo $row['content']; ?></td>
                            <td><?php echo $keyword2->keyword; ?></td>
                        </tr>
                        <?php } ?>
                    </table>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>微博</th>
                            <th>标签</th>
                        </tr>
                        <?php while($row = mysql_fetch_array($result_keyword1_weibo)){  ?>
                        <tr>
                            <td><?php echo $row['content']; ?></td>
                            <td><?php echo $keyword1->keyword; ?></td>
                        </tr>
                        <?php } ?>
                        <?php while($row = mysql_fetch_array($result_keyword2_weibo)){  ?>
                        <tr>
                            <td><?php echo $row['content']; ?></td>
                            <td><?php echo $keyword2->keyword; ?></td>
                        </tr>
                        <?php } ?>
                    </table>
                    <div class="linkbtns">
                        <form action="/monitor/exportsheet">
                            <input type="submit" class="btn btn-primary" value="导出excel报表">
                        </form>
                    </div>
                    <div>
                        <form action="/monitor/exportreport">
                            <input type="submit" class="btn btn-primary" value="导出分析报告">
                        </form>
                    </div>
                </div>
                <div>
                    <a href="/monitor/data">最近监测数据</a>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
