<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_enterprise.phtml'; 
        ?>
        <div id="mid" class="span9 mid"  style="padding-top:20px;">
            <div class="linkbtns">
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="网络监测">
                </form>
            </div>
            <div>
                <form action="#">
                    <input type="submit" class="btn btn-primary linkbtn" value="监测订制">
                </form>
            </div>
            <div>
                <table>
                    <tr>
                        <td><span>正在监测的您的APP产品1：</span></td>
                        <td>
                            <?php echo $self1->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>正在监测的您的APP产品2：</span></td>
                        <td>
                            <?php echo $self2->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>正在监测的您的APP产品3：</span></td>
                        <td>
                            <?php echo $self3->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><span>正在监测的竞争APP产品1：</span></td>
                        <td>
                            <?php echo $competitor1->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>正在监测的竞争APP产品2：</span></td>
                        <td>
                            <?php echo $competitor2->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>正在监测的竞争APP产品3：</span></td>
                        <td>
                            <?php echo $competitor3->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>正在监测的竞争APP产品4：</span></td>
                        <td>
                            <?php echo $competitor4->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span>正在监测的竞争APP产品5：</span></td>
                        <td>
                            <?php echo $competitor5->keyword; ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <form action="/monitor/configure">
                                <input type="submit" class="btn btn-primary" value="订制">
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user,.mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 80%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
