<div id="indexpage" class="indexpage">
    <div id="main" class="container"> 
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px">
            <div>
                <div class="linkbtns">
                    <form action="/media/mediainfo">
                        <input type="submit" class="btn btn-primary linkbtn" value="企业资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/media/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <!--
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>-->
                <div>
                    <form action="/media/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="userinfo">
                        <table id="tbuserinfo">
                            <tr>
                                <td>
                                    用户信息——
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    用户名：
                                    <?php echo $user;?>&nbsp;&nbsp;<a href="">修改密码</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    电子邮箱：
                                </td>
                                <td>
                                    <?php echo $email;?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                    <div id="addmediainfo" style="display:<?php echo $addmediainfo;?>;">
                        请在下表中编辑媒体信息：
                        <table>
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action',$this->url(
                            'media',
                            array(
                                'action' => 'index',
                            )
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('id_media'));
                        ?>
                            <tr>
                                <td class="tdlabel">媒体属性：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('fk_media_type'));?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">媒体名称：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">所在地：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('location')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">通信地址：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('address')); ?>
                                </td>
                            </tr>
                            <!--<tr>
                                <td class="tdlabel">发票信息：</td>
                                <td class="tdlabel">发票抬头：</td>
                                <td class="tdinput">
                                    <?php //echo $this->formRow($form->get('invoice_title')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">发票类型：</td>
                                <td class="tdinput">
                                    <?php //echo $this->formRow($form->get('invoice_type')); ?>
                                </td>
                            </tr>-->
                            <tr>
                                <td class="tdlabel">个人信息：</td>
                                <td class="tdlabel">姓名</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">职位</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_post')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">电话</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_phone')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">邮箱</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_email')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td colspan=2>
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                    <?php echo $this->form()->closeTag(); ?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>