<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px">
            <div>
                <div class="linkbtns">
                    <form action="/">
                        <input type="submit" class="btn btn-primary linkbtn" value="媒体资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/media/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <!--
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>-->
                <div>
                    <form action="/media/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="userinfo">
                        <table id="tbuserinfo">
                            <tr>
                                <td>
                                    用户信息——
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    用户名：
                                    <?php echo $user;?>&nbsp;&nbsp;<a href="/user/changepassword/<?php echo $id_user;?>">修改密码</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    电子邮箱：
                                    <?php echo $email;?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                    <?php 
                    //show the media information if exist.
                    //if not, render the form to create it for the user.
                    $mediainfo = 'none';
                    $addmediainfo = '';
                    if($fk_media)
                    {
                        $mediainfo = '';
                        $addmediainfo = 'none';
                    }
                    ?>
                    <div id="mediainfo" style="display:<?php echo $mediainfo;?>;">
                        <table id="tbmediainfo">
                            <tr>
                                <td>公司信息——</td>
                                <td colspan=2>
                                    &nbsp;&nbsp;<a href="<?php echo $this->url('media',
                                array('action' => 'edit', 'id' => $media->id_media)) ;?>">编辑</a>
                                </td>
                            </tr>
                            <tr>
                                <td>媒体属性：</td>
                                <td colspan=2>
                                    <?php 
                                    $arr_media_type = array(
                                        '1' => '印刷媒体',
                                        '2' => '网络媒体',
                                        '3' => '自媒体人',
                                    );
                                    if(array_key_exists($media->fk_media_type, $arr_media_type)){
                                        echo $arr_media_type[$media->fk_media_type];
                                    }else{
                                        echo "媒体属性错误！";
                                    }                                    
                                    ?>
                                </td>
                            </tr>
                            <tr>
                                <td>媒体名称：</td>
                                <td colspan=2>
                                    <?php echo $media->name;?>
                                </td>
                            </tr>
                            <tr>
                                <td>所在地：</td>
                                <td colspan=2>
                                    <?php echo $media->location;?>
                                </td>
                            </tr>
                            <tr>
                                <td>通信地址：</td>
                                <td colspan=2>
                                    <?php echo $media->address;?>
                                </td>
                            </tr>
                            <!--<tr>
                                <td>发票信息：</td>
                                <td>发票抬头：</td>
                                <td>
                                    <?php //echo $media->invoice_title;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>发票类型：</td>
                                <td>
                                    <?php //echo $media->invoice_type;?>
                                </td>
                            </tr>-->
                            <tr>
                                <td>个人信息：</td>
                                <td>姓名：</td>
                                <td>
                                    <?php echo $media->contacter_name;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>职位：</td>
                                <td>
                                    <?php echo $media->contacter_post;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>电话：</td>
                                <td>
                                    <?php echo $media->contacter_phone;?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>邮箱：</td>
                                <td>
                                    <?php echo $media->contacter_email;?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                    <div id="addmediainfo" style="display:<?php echo $addmediainfo;?>;">
                        未创建媒体公司信息，请在下表中填写：
                        <table>
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action',$this->url(
                            'media',
                            array(
                                'action' => 'index',
                            )
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('id_media'));
                        ?>
                            <tr>
                                <td class="tdlabel">媒体属性：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('fk_media_type'));?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">媒体名称：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">所在地：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('location')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdlabel">通信地址：</td>
                                <td colspan=2 class="tdinput">
                                    <?php echo $this->formRow($form->get('address')); ?>
                                </td>
                            </tr>
                            <!--<tr>
                                <td class="tdlabel">发票信息：</td>
                                <td class="tdlabel">发票抬头：</td>
                                <td class="tdinput">
                                    <?php //echo $this->formRow($form->get('invoice_title')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">发票类型：</td>
                                <td class="tdinput">
                                    <?php //echo $this->formRow($form->get('invoice_type')); ?>
                                </td>
                            </tr>-->
                            <tr>
                                <td class="tdlabel">个人信息：</td>
                                <td class="tdlabel">姓名</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_name')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">职位</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_post')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">电话</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_phone')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdlabel">邮箱</td>
                                <td class="tdinput">
                                    <?php echo $this->formRow($form->get('contacter_email')); ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td colspan=2>
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                    <?php echo $this->form()->closeTag(); ?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>


            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>
