<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
    <h1>媒体用户首页</h1>  
    <div id="header" class="container" style="width:1170px;"> 
    CONTAINER
    <div class="row">
        ROW
        <div id="logo" class="span2 logo">
            APPBUZZ LOGO
        </div>
        <div id="banner" class="span8 banner">
            BANNER
        </div>
    </div>
    </div>
</BR>
    <div id="main" class="container" style="width:1170px;">
        CONTAINER
    <div id="row" class="row">
        ROW
        <div id="left" class="span4 left">
            SPAN4 LEFT
            <div id="user" class="user">
                媒体用户资料
            </div>
            <div id="topicpublish" class="topicpublish">
                <a href="topicpublish">发布选题</a>
            </div>
            <div id="appevaluating" class="appevaluating">
                <a href="appevaluating">评测APP</a>
            </div>
            <div id="appinterview" class="appinterview">
                <a href="appinterview">采访APP</a>
            </div>
            <div id="editor" class="editor">
                <a href="editor">自由撰稿人</a>
            </div>            
        </div>
        <div id="mid" class="span4 mid">
            SPAN4 MID
            <div id="appnewshelper" class="appnewshelper">
                APP新闻助手
            </div>
            <div id="news" class="news">
                APP新闻首页
            </div>
        </div>
        <div id="right" class="span4 right">
            SPAN4 RIGHT
            <div id="mediarank" class="mediarank">
                APP媒体曝光排名
            </div>
            <div id="latestapp" class="latestapp">
                最新注册APP
            </div>
        </div>
    </div>
    </div>
</div>