<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px">
            <div>
                <div class="linkbtns">
                    <form action="/">
                        <input type="submit" class="btn btn-primary linkbtn" value="媒体资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/media/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <!--
                <div class="linkbtns">
                    <form action="/product/index">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的产品">
                    </form>
                </div>-->
                <div>
                    <form action="/media/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>
                    <div id="userinfo">
                        <h4>我的账户：</h4>
                        <table id="tbuserinfo">
                            <tr>
                                <td>用户名：</td>
                                <td><?php echo $user; ?></td>
                                <td>账户余额：</td>
                                <td><?php echo '人民币 '.$credit->amount.' 元'; ?></td>
                            </tr>                            
                        </table>
                    </div>
                </div>
                <div id="creditlog" style="display:<?php echo ($creditlog)?'':'none';?>;" class="widget-box">
                    <div class="widget-title">
                        <h4>最近交易记录：</h4>
                    </div>
                    <div class="widget-content nopadding">
                        <?php 
                        $arr_service_type = array(
                            '1' => '充值',
                            '2' => '新闻发布(单篇)',
                            '3' => '新闻发布(打包)',
                            '4' => '产品评测',
                            '5' => '媒体评测',
                            '20' => '收款',
                        );
                        ?>
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th>订单号</th>
                                <th>交易类型</th>
                                <th>交易金额</th>
                                <th>交易日期</th>
                                <th>经办人</th>
                            </tr>
                            <?php foreach($creditlog as $log): ?>
                            <tr>
                                <td><?php echo $log->order_no; ?></td>
                                <td><?php echo $arr_service_type[$log->fk_service_type]; ?></td>
                                <td>
                                    <?php 
                                    $sign = '';
                                    if($log->fk_service_type==1){
                                        $sign = '+';
                                    }
                                    echo $sign.$log->amount.'元'; 
                                    ?>
                                </td>
                                <td><?php echo $log->date_time; ?></td>
                                <td><?php echo $log->created_by; ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                    <div class="linkbtns">
                        <form action="/credit/exportlog/<?php echo $credit->id_credit ;?>">
                            <input type="submit" class="btn btn-primary" value="导出全部交易记录">
                        </form>
                    </div>
                    <div class="linkbtns">
                        <form action="/credit/withdraw/<?php echo $credit->id_credit ;?>">
                            <input type="submit" class="btn btn-primary" value="申请收款">
                        </form>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>