<div id="indexpage" class="indexpage">
    <div id="main" class="container" >
    <div id="row" class="row">
        <?php 
        set_include_path("public/include");        
        include 'sidebar_media.phtml'; 
        ?>
        <div id="mid" class="span9 mid" style="padding-top:20px">
            <div>
                <div class="linkbtns">
                    <form action="/">
                        <input type="submit" class="btn btn-primary linkbtn" value="媒体资料">
                    </form>
                </div>
                <div class="linkbtns">
                    <form action="/media/myaccount">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的账户">
                    </form>
                </div>
                <div>
                    <form action="/media/myorder">
                        <input type="submit" class="btn btn-primary linkbtn" value="我的订单">
                    </form>
                </div>
                <div>                    
                    <div id="evamedia" class="widget-box">
                        <div class="widget-title">
                            <h4>最新订单——</h4>
                        </div>
                        <div class="widget-content nopadding">
                            <?php
                            $arr_id_user = array();
                            foreach($all_users as $au)
                            {
                                $arr_id_user[$au->id] = $au->username;
                            }
                            $arr_id_evaluate = array();
                            foreach($evaluates as $eva)
                            {
                                $arr_id_evaluate[$eva->id_evaluate] = $eva;
                            }
                            $arr_id_product = array();
                            foreach($products as $pd)
                            {
                                $arr_id_product[$pd->id_product] = $pd;
                            }
                            ?>
                            <?php 
                            $arr_evamedia_status = array(
                                '1' => '新订单',
                                '2' => '媒体拒绝',
                                '3' => '媒体接受',
                                '4' => '企业拒绝',
                                '5' => '企业接受',
                                '6' => '订单完成',
                            );
                            $arr_wrtmedia_status = array(
                                '1' => '新订单',
                                '2' => '媒体拒绝',
                                '3' => '媒体接受',
                                '4' => '企业拒绝',
                                '5' => '企业接受',
                                '6' => '初稿提交',
                                '7' => '初稿修改',
                                '8' => '终稿提交',
                                '9' => '稿件通过',
                                '10' => '订单终止',
                            );
                            $arr_topic_status = array(
                                '1' => '待发布',
                                '2' => '征集中',
                                '3' => '已结束',
                            );
                            $arr_interview_status = array(
                                '1' => '发出邀请',
                                '2' => '企业接受',
                                '3' => '企业拒绝',
                                '4' => '媒体取消',
                                '5' => '采访结束',
                            );
                            ?>
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th>订单号</th>
                                    <th>订单类型</th>
                                    <!--<th>APP产品</th>
                                    <th>企业名称</th>
                                    <th>有效日期</th>-->
                                    <th>订单状态</th>
                                    <th>创建日期</th>
                                    <th>操作</th>
                                </tr>                                
                                <?php foreach($evamedia5 as $em): ?>
                                <tr>
                                    <td>
                                        <a href="/evaluate/evainfo/<?php echo $em->fk_evaluate; ?>">
                                            <?php echo $em->order_no; ?>
                                        </a>
                                    </td>
                                    <td>产品评测</td>
                                    <!--<td><?php echo $arr_id_product[$arr_id_evaluate[$em->fk_evaluate]->fk_product]->name; ?></td>
                                    <td><?php echo $arr_id_user[$em->fk_enterprise_user]; ?></td>
                                    <td><?php echo $arr_id_evaluate[$em->fk_evaluate]->due_date; ?></td>-->
                                    <td>
                                        <?php
                                        if(array_key_exists($em->fk_evamedia_status, $arr_evamedia_status)){
                                            echo $arr_evamedia_status[$em->fk_evamedia_status];
                                        }
                                        
                                        ?>
                                    </td>
                                    <td><?php echo $em->created_by;?></td>
                                    <td>
                                        <a href="/evaluate/evainfo/<?php echo $em->fk_evaluate; ?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            <?php
                            $arr_id_writer = array();
                            foreach($writers as $wt)
                            {
                                $arr_id_writer[$wt->id_writer] = $wt;
                            }
                            ?>    
                                <?php foreach($wrtmedia5 as $wm): ?>
                                <tr>
                                    <td>
                                        <a href="/writer/wrtinfo/<?php echo $wm->fk_writer; ?>">
                                            <?php echo $wm->order_no; ?>
                                        </a>
                                    </td>
                                    <td>自由撰稿人</td>
                                    <!--<td><?php echo $arr_id_product[$arr_id_writer[$wm->fk_writer]->fk_product]->name; ?></td>
                                    <td><?php echo $arr_id_user[$wm->fk_enterprise_user]; ?></td>-->
                                    <td>
                                        <?php 
                                        if(array_key_exists($wm->fk_wrtmedia_status, $arr_wrtmedia_status)){
                                            echo $arr_wrtmedia_status[$wm->fk_wrtmedia_status]; 
                                        }                                        
                                        ?>
                                    </td>
                                    <td><?php echo $wm->created_at; ?></td>
                                    <td>
                                        <a href="/writer/wrtinfo/<?php echo $wm->fk_writer; ?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                <?php foreach($topic5 as $tp): ?>
                                <tr>
                                    <td>
                                        <a href="/topic/detail/<?php echo $tp->id_topic; ?>">
                                            <?php echo $tp->order_no; ?>
                                        </a>
                                    </td>
                                    <td>选题发布</td>
                                    <td>
                                        <?php
                                        if(array_key_exists($tp->fk_topic_status, $arr_topic_status)){
                                            echo $arr_topic_status[$tp->fk_topic_status];
                                        }
                                        ?>
                                    </td>
                                    <!--<td><?php echo $tp->topic_type; ?></td>
                                    <td><?php echo $tp->app_type; ?></td>
                                    <td><?php echo $tp->due_date; ?></td>-->
                                    <td><?php echo $tp->created_at;?></td>
                                    <td>
                                        <a href="/topic/detail/<?php echo $tp->id_topic; ?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                <?php foreach($interview5 as $itv): ?>
                                <tr>
                                    <td>
                                        <a href="/interview/detail/<?php echo $itv->id_interview; ?>">
                                            <?php echo $itv->order_no; ?>
                                        </a>
                                    </td>
                                    <td>采访邀约</td>
                                    <td>
                                        <?php
                                        if(array_key_exists($itv->fk_interview_status, $arr_interview_status)){
                                            echo $arr_interview_status[$itv->fk_interview_status];
                                        }
                                        ?>
                                    </td>
                                    <!--<td><?php echo $arr_id_product[$itv->fk_product]->name; ?></td>
                                    <td><?php echo $arr_id_user[$itv->fk_enterprise_user]; ?></td>
                                    <td><?php echo $itv->date_time; ?></td>-->
                                    <td><?php echo $itv->created_at;?></td>
                                    <td>
                                        <a href="/interview/detail/<?php echo $itv->id_interview; ?>" class="btn btn-primary btn-mini">
                                            查看详情
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>

<style>
/*
div.user, .mid
{
    border:1px black solid;
}
.logout
{
    text-align: right;
}
table
{
    width: 100%;
}
.tdinput

{
    width: 70%;
}
.tdlabel
{
    vertical-align: top;
}
input[type="text"], textarea
{
    margin-bottom: 5px;
    margin-right: 5px;
    border: 1px #ffffff;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0) inset;
    width: 100%;
}*/
</style>

            <script src="js/excanvas.min.js"></script>
            <script src="js/jquery.min.js"></script>
            <script src="js/jquery.ui.custom.js"></script>
            <script src="js/bootstrap.min.js"></script>
            <script src="js/jquery.flot.min.js"></script>
            <script src="js/jquery.flot.resize.min.js"></script>
            <script src="js/jquery.peity.min.js"></script>
            <script src="js/fullcalendar.min.js"></script>
            <script src="js/unicorn.js"></script>
            <script src="js/unicorn.dashboard.js"></script>