<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/style.css">


<div id="indexpage" class="indexpage">
	<h1>APPBUZZ首页</h1>
	<div id="header" class="container" style="width:1170px;"> 
	CONTAINER
	<div class="row">
		ROW
		<div id="logo" class="span2 logo">
			APPBUZZ LOGO
		</div>
		<div id="banner" class="span8 banner">
			BANNER
		</div>
	</div>
	</div>
</BR>
	<div id="main" class="container" style="width:1170px;">
		CONTAINER
	<div id="row" class="row">
		ROW
		<div id="left" class="span4 left">
			SPAN4 LEFT
			<div id="user" class="user">
				USER
				<div id="enterpriseuser" class="enterpriseuser">
					<a href="/enterprise/index">企业用户</a>
					<form id='login' action="user/checkenterpriseuser" method='post' accept-charset='UTF-8'>
    					<input name="username" type="text" placeholder="用户名"/>
    					<input name="password" type="password" placeholder="密码"/>
    					<div class="remember">
        					<div class="left">
            					<input id="remember_me" type="checkbox">
            					<label for="remember_me">记住我</label>
        					</div>
        					<div class="right">
            					<a href="">忘记密码</a>
        					</div>
    					</div>
    					<input type="submit" class="btn" value="登录"/>
					</form>
				</div>
				<div id="mediauser" class="mediauser">
					<a href="/media/index">媒体用户</a>
					<form id='login' action="user/checkmediauser" method='post' accept-charset='UTF-8'>
    					<input name="username" type="text" placeholder="用户名"/>
    					<input name="password" type="password" placeholder="密码"/>
    					<div class="remember">
        					<div class="left">
            					<input id="remember_me" type="checkbox">
            					<label for="remember_me">记住我</label>
        					</div>
        					<div class="right">
            					<a href="">忘记密码</a>
        					</div>
    					</div>
    					<input type="submit" class="btn" value="登录"/>
					</form>
				</div>
			</div>
			<div id="medialogos" class="medialogos">
				合作媒体
			</div>
		</div>
		<div id="mid" class="span4 mid">
			SPAN4 MID
			<div id="slides" class="slides">
				焦点推荐图
			</div>
			<div id="abstract" class="abstract">
				摘要
			</div>
			<div id="news" class="news">
				新闻与评测
			</div>
		</div>
		<div id="right" class="span4 right">
			SPAN4 RIGHT
			<div id="mediarank" class="mediarank">
				APP媒体曝光排名
			</div>
			<div id="latestapp" class="latestapp">
				最新注册APP
			</div>
		</div>
	</div>
	</div>
</div>