<div>
	<div id="main" class="container"> 
		<div id="row" class="row">
			<?php 
	        set_include_path("public/include");        
	        include 'sidebar.phtml'; 
	        ?>
			<div id="mid" class="span6 mid">
				<div id="slides" class="slides">
					<div id="myCarousel" class="carousel slide">
					  <!--<ol class="carousel-indicators">
					    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
					    <li data-target="#myCarousel" data-slide-to="1"></li>
					    <li data-target="#myCarousel" data-slide-to="2"></li>
					  </ol>-->
					  <!-- Carousel items -->
					  <div class="carousel-inner slideshow">
					    <div class="active item">图片1</div>
					    <div class="item">图片2</div>
					    <div class="item">图片3</div>
					  </div>

					   <!-- Carousel nav -->
						<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
						<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
					</div>
				</div>
				<div id="abstract" class="abstract">
					<h2 class="title">2013突破性科学技术：记录科技创新步伐 </h2>
					<p>你认为突破性科学技术指的是什么？是交互方式，还是实验性设备又或者是对未来的预测，还是新经济增长点？本专题不仅告诉各位读者最近一年取得的巨大技术进步，更多的是庆贺人类在创新道路上的进步。</p>
				</div>
				<div id="news" class="news">
					<?php 
					$arr_articles = array();
					foreach($articles as $artl)
					{
						$arr_articles[$artl->id_article] = $artl; 
					}
					$arr_rank_article = array();
					$arr_rank_article[1] = $arr_articles[$rank->fk_no_1];
					$arr_rank_article[2] = $arr_articles[$rank->fk_no_2];
					$arr_rank_article[3] = $arr_articles[$rank->fk_no_3];
					$arr_rank_article[4] = $arr_articles[$rank->fk_no_4];
					$arr_rank_article[5] = $arr_articles[$rank->fk_no_5];
					$arr_rank_article[6] = $arr_articles[$rank->fk_no_6];
					$arr_rank_article[7] = $arr_articles[$rank->fk_no_7];
					$arr_rank_article[8] = $arr_articles[$rank->fk_no_8];
					$arr_rank_article[9] = $arr_articles[$rank->fk_no_9];
					$arr_rank_article[10] = $arr_articles[$rank->fk_no_10];
					?>
					<ul class="article-list">
						<?php foreach($arr_rank_article as $ara): ?>
						<li>
							<h2 class="title">
								<a href="/article/pubview/<?php echo $ara->id_article; ?>">
									<?php echo $ara->title; ?>
								</a>
							</h2>
							<p>你认为突破性科学技术指的是什么？是交互方式，还是实验性设备又或者是对未来的预测，还是新经济增长点...</p>
						</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
			
			<?php 
	        set_include_path("public/include");        
	        include 'sidebar_right.phtml'; 
	        ?>
		</div>
	</div>
</div>

<script>
function submit_form()
{
	var verify_code_input = document.getElementById("verify_code").value;
	var verify_code_show = "<?php echo $captcha->getWord(); ?>";
	var form_enterprise = document.getElementById("ent_login");
	if(verify_code_show == verify_code_input){
		//alert("验证码正确！");
		form_enterprise.submit();
	}else{
		alert("验证码错误！");
	}
}
function submit_form_med()
{
	var verify_code_input = document.getElementById("verify_code_med").value;
	var verify_code_show = "<?php echo $captcha_med->getWord(); ?>";
	var form_media = document.getElementById("med_login");
	if(verify_code_show == verify_code_input){
		//alert("验证码正确！");
		form_media.submit();
	}else{
		alert("验证码错误！");
	}
}
/*
function ent_alert()
{
	var div_ent = document.getElementById("enterpriseuser");
	var div_med = document.getElementById("mediauser");
	var span_ent = document.getElementById("ent-login");
	var span_med = document.getElementById("med-login");
	div_ent.style.display = "inline";
	div_med.style.display = "none";
	span_ent.style.backgroundColor = "#000000";
	span_med.style.backgroundColor = "grey";
	//alert("企业用户！");	
}
function med_alert()
{
	var div_ent = document.getElementById("enterpriseuser");
	var div_med = document.getElementById("mediauser");
	var span_ent = document.getElementById("ent-login");
	var span_med = document.getElementById("med-login");
	div_ent.style.display = "none";
	div_med.style.display = "inline";
	span_ent.style.backgroundColor = "grey";
	span_med.style.backgroundColor = "#000000";
	//alert("媒体用户！");
}*/

$(function(){

	$('#med-login').click(function(){
		$('#enterpriseuser').hide();
		$('#mediauser').show();
		$(this).css('backgroundColor', '#000');
		$('#ent-login').css('backgroundColor','grey');
	});

	$('#ent-login').click(function(){
		$('#enterpriseuser').show();
		$('#mediauser').hide();
		$(this).css('backgroundColor', '#000');
		$('#med-login').css('backgroundColor','grey');
	});
})

</script>


<style>
/*
.corporate-logo
{
	width:160px;
	margin:10px;
}
div.navbar
{
	display: none;
}
.indexheader
{
	background-color: #f4f4f4;
}
.indexbody
{
	border-top: 4px solid #7c9726;
}
.login
{
	color:#90b33f;
}
span.ent-login
{
	color:#ffffff;
	background-color: #000000;
	cursor: pointer;
	padding: 2px;
}
span.med-login
{
	color:#ffffff;
	background-color: grey;
	cursor: pointer;
	padding: 2px;
}
div.login-inputs, div.login-btns
{
	background-color: #f4f4f4;
}
div.login-inputs
{
	border-top:4px solid #000000;
	margin-left: auto;
	margin-right:auto;
	width:220px;
}
div.user-tabs
{
	margin:0;
}
div.mid-it
{
	margin-left: auto;
	margin-right: auto;
	width: 200px;	
}
div.enterpriseuser, div.mediauser
{	
}
div.mediauser
{
	display: none;
}
div.login-btns
{
	border-top: 1px solid #ffffff;
}
input
{
	width: 100px;
}
td.tdlabel
{
    vertical-align: top;
}
*/
</style>